# Generated by Django 5.2 on 2025-10-27 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rut',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Use formato: 12345678-9 o 12.345.678-9', regex='^(\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]|\\d{7,8}-[\\dkK])$')], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='rut',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Use formato: 12345678-9 o 12.345.678-9', regex='^(\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]|\\d{7,8}-[\\dkK])$')], verbose_name='RUT'),
        ),
    ]
