[phases.setup]
nixPkgs = ['python39']

[phases.install]
cmds = [
    'cd retailmind',
    'python -m pip install -r requirements.txt'
]

[phases.build]
cmds = [
    'cd retailmind',
    'python manage.py collectstatic --noinput'
]

[start]
cmd = 'cd retailmind && gunicorn retailmind.wsgi --log-file -'
