# Generated by Django 5.2 on 2025-12-17 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usuario_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='codigo_2fa',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Código 2FA Temporal'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_codigo_2fa',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Generación Código 2FA'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='requiere_2fa',
            field=models.BooleanField(default=False, verbose_name='Requiere Autenticación en 2 Pasos'),
        ),
    ]
