# Generated by Django 5.2 on 2025-12-17 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_usuario_codigo_2fa_usuario_fecha_codigo_2fa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='requiere_cambio_password',
            field=models.BooleanField(default=False, verbose_name='Requiere Cambio de Contraseña'),
        ),
    ]
