# Generated by Django 5.2 on 2026-01-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_add_requiere_cambio_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('administracion', 'Administración'), ('jefe_local', 'Jefe Local'), ('cajero', 'Cajero'), ('vendedor', 'Vendedor')], default='vendedor', max_length=50, verbose_name='Rol'),
        ),
    ]
