# Generated by Django 5.2 on 2026-01-22 19:15

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_add_foto_perfil_sesiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Imagen de perfil del usuario', null=True, upload_to=users.models.user_profile_photo_path, verbose_name='Foto de Perfil'),
        ),
    ]
