# Generated by Django 5.2 on 2025-12-17 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadisticasAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(help_text='Fecha de las estadísticas', unique=True)),
                ('total_conversaciones', models.IntegerField(default=0)),
                ('total_mensajes', models.IntegerField(default=0)),
                ('total_usuarios_unicos', models.IntegerField(default=0)),
                ('total_tool_calls', models.IntegerField(default=0)),
                ('tools_mas_usadas', models.JSONField(default=dict, help_text='Conteo de uso por herramienta')),
                ('tiempo_respuesta_promedio_ms', models.IntegerField(default=0)),
                ('tasa_exito', models.DecimalField(decimal_places=2, default=100.0, help_text='Porcentaje de respuestas exitosas', max_digits=5)),
                ('total_feedback', models.IntegerField(default=0)),
                ('rating_promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('feedback_positivo', models.IntegerField(default=0)),
                ('feedback_negativo', models.IntegerField(default=0)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Estadísticas del Asistente',
                'verbose_name_plural': 'Estadísticas del Asistente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ConversacionAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(db_index=True, help_text='ID único de la sesión', max_length=100)),
                ('activa', models.BooleanField(default=True, help_text='Si la conversación está activa')),
                ('total_mensajes', models.IntegerField(default=0, help_text='Total de mensajes en la conversación')),
                ('total_tool_calls', models.IntegerField(default=0, help_text='Total de llamadas a herramientas')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultimo_mensaje', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que inició la conversación', on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_asistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación del Asistente',
                'verbose_name_plural': 'Conversaciones del Asistente',
                'ordering': ['-fecha_ultimo_mensaje'],
            },
        ),
        migrations.CreateModel(
            name='MensajeAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Asistente'), ('system', 'Sistema')], help_text='Rol del mensaje', max_length=20)),
                ('contenido', models.TextField(help_text='Contenido del mensaje')),
                ('tools_usadas', models.JSONField(blank=True, help_text='Lista de herramientas usadas en este mensaje', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tiempo_respuesta_ms', models.IntegerField(blank=True, help_text='Tiempo de respuesta en milisegundos', null=True)),
                ('conversacion', models.ForeignKey(help_text='Conversación a la que pertenece', on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='assistant.conversacionasistente')),
            ],
            options={
                'verbose_name': 'Mensaje del Asistente',
                'verbose_name_plural': 'Mensajes del Asistente',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackAsistente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '👎 Muy malo'), (2, '😕 Malo'), (3, '😐 Regular'), (4, '🙂 Bueno'), (5, '👍 Excelente')], help_text='Calificación del 1 al 5')),
                ('tipo_feedback', models.CharField(choices=[('UTIL', 'Respuesta útil'), ('NO_UTIL', 'Respuesta no útil'), ('INCORRECTO', 'Información incorrecta'), ('INCOMPLETO', 'Información incompleta'), ('ERROR', 'Error del sistema'), ('SUGERENCIA', 'Sugerencia de mejora'), ('OTRO', 'Otro')], default='UTIL', help_text='Tipo de feedback', max_length=20)),
                ('comentario', models.TextField(blank=True, help_text='Comentario adicional del usuario', null=True)),
                ('pregunta_usuario', models.TextField(blank=True, help_text='Pregunta que generó la respuesta evaluada', null=True)),
                ('respuesta_asistente', models.TextField(blank=True, help_text='Respuesta del asistente evaluada', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('revisado', models.BooleanField(default=False, help_text='Si el feedback ha sido revisado por el equipo')),
                ('notas_revision', models.TextField(blank=True, help_text='Notas del equipo sobre el feedback', null=True)),
                ('conversacion', models.ForeignKey(blank=True, help_text='Conversación evaluada', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='assistant.conversacionasistente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_asistente', to=settings.AUTH_USER_MODEL)),
                ('mensaje', models.ForeignKey(blank=True, help_text='Mensaje específico evaluado', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='assistant.mensajeasistente')),
            ],
            options={
                'verbose_name': 'Feedback del Asistente',
                'verbose_name_plural': 'Feedback del Asistente',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='conversacionasistente',
            index=models.Index(fields=['usuario', 'activa'], name='assistant_c_usuario_cbb35a_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacionasistente',
            index=models.Index(fields=['session_id'], name='assistant_c_session_3a5e44_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacionasistente',
            index=models.Index(fields=['fecha_inicio'], name='assistant_c_fecha_i_9ccb3c_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeasistente',
            index=models.Index(fields=['conversacion', 'timestamp'], name='assistant_m_convers_e62488_idx'),
        ),
        migrations.AddIndex(
            model_name='mensajeasistente',
            index=models.Index(fields=['rol', 'timestamp'], name='assistant_m_rol_241cda_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackasistente',
            index=models.Index(fields=['usuario', 'fecha'], name='assistant_f_usuario_0084b8_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackasistente',
            index=models.Index(fields=['rating', 'fecha'], name='assistant_f_rating_797afd_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbackasistente',
            index=models.Index(fields=['tipo_feedback', 'revisado'], name='assistant_f_tipo_fe_176257_idx'),
        ),
    ]
