# Generated by Django 5.2 on 2025-04-07 21:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Compras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('correlativo', models.IntegerField()),
                ('responsable', models.CharField(max_length=50)),
                ('temporada', models.CharField(max_length=50)),
                ('fecha', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.IntegerField()),
                ('tipo_documento', models.CharField(choices=[('FACTURA ELECTRONICA', 'Factura Electronica'), ('BOLETA ELECTRONICA', 'Boleta Electronica'), ('GUIA', 'Guía de Despacho'), ('NOTA DE PEDIDO', 'Nota de Pedido'), ('NOTA DE CREDITO', 'Nota de Credito'), ('NOTA DE DEBITO', 'Nota de debito'), ('FACTURA EXENTA', 'Factura Exenta'), ('COTIZACION', 'Cotizacion')], max_length=20)),
                ('monto_con_iva', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado_pago', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido')], max_length=20)),
                ('estado_dte', models.CharField(choices=[('EMITIDO', 'Emitido'), ('RECHAZADO', 'Rechazado'), ('ACEPTADO', 'Aceptado'), ('ANULADO', 'Anulado')], max_length=20)),
                ('responsable', models.CharField(max_length=100)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField()),
                ('bultos', models.IntegerField()),
                ('unidades_productos', models.IntegerField()),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('tipo_transaccion', models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta')], max_length=10)),
                ('referencias', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=20)),
                ('nombre_fantasia', models.CharField(max_length=255)),
                ('razon_social', models.CharField(max_length=255)),
                ('giro', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('comuna', models.CharField(max_length=100)),
                ('ciudad', models.CharField(max_length=100)),
                ('esProveedor', models.BooleanField(default=False)),
                ('correoVendedor', models.CharField(max_length=100)),
                ('correoIntercambio', models.CharField(max_length=100)),
                ('correoAdministrador', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articulo', models.CharField(max_length=200)),
                ('descripcion', models.CharField(max_length=250)),
                ('costo', models.IntegerField()),
                ('sobreprecio', models.IntegerField()),
                ('precioventa', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Productos_Atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('fecha_actualizacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_vendedor', models.CharField(max_length=100)),
                ('rut', models.CharField(max_length=100, null=True)),
                ('nombre', models.CharField(max_length=100, null=True)),
                ('comision', models.IntegerField()),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('correo', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Compras_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('atributo1', models.CharField(max_length=200)),
                ('atributo2', models.CharField(max_length=200)),
                ('atributo3', models.CharField(max_length=200)),
                ('atributo4', models.CharField(max_length=200)),
                ('costo', models.IntegerField()),
                ('precioSugerido', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('compras', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compras')),
            ],
        ),
        migrations.CreateModel(
            name='Compras_Producto_Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('talla', models.CharField(max_length=50)),
                ('compra_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compras_producto')),
            ],
        ),
        migrations.CreateModel(
            name='Dte_Detalle_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(max_length=100)),
                ('tipo_tarjeta', models.CharField(max_length=100, null=True)),
                ('voucher', models.CharField(max_length=50, null=True)),
                ('monto', models.IntegerField()),
                ('dte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dte_asociado', to='app.dte')),
            ],
        ),
        migrations.AddField(
            model_name='dte',
            name='emisor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresa_origen', to='app.empresa'),
        ),
        migrations.AddField(
            model_name='dte',
            name='receptor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='empresa_destino', to='app.empresa'),
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField()),
                ('estado', models.CharField(max_length=50)),
                ('estadoPago', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('fechaCreacion', models.DateField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='compras',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa'),
        ),
        migrations.CreateModel(
            name='EmpresaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto_Talla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('talla', models.CharField(max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_talla', to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Movimientos_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo', models.IntegerField()),
                ('sobreprecio', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('concepto', models.CharField(max_length=50)),
                ('tipo_movimiento', models.CharField(max_length=50)),
                ('responsable', models.CharField(max_length=50)),
                ('dte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dte_movimientos', to='app.dte')),
                ('ProductoTalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_productos_talla', to='app.producto_talla')),
            ],
        ),
        migrations.CreateModel(
            name='Dte_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('costo', models.IntegerField()),
                ('sobreprecio', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('dte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dte_productos', to='app.dte')),
                ('productoTalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_talla_dte', to='app.producto_talla')),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('sobreprecio', models.IntegerField()),
                ('precio', models.IntegerField()),
                ('cotizacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cotizacion')),
                ('producto_talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto_talla')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='atributo1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_productos1', to='app.productos_atributos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='atributo2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_productos2', to='app.productos_atributos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='atributo3',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_productos3', to='app.productos_atributos'),
        ),
        migrations.AddField(
            model_name='producto',
            name='atributo4',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos_productos4', to='app.productos_atributos'),
        ),
        migrations.CreateModel(
            name='Productos_Recepcionados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockArribado', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('compra_producto_talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.compras_producto_talla')),
                ('producto_talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto_talla')),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=100)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.empresa')),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_producto', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='dte',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sucursal'),
        ),
        migrations.CreateModel(
            name='Correlativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_dte', models.CharField(max_length=50)),
                ('inicio', models.IntegerField()),
                ('termino', models.IntegerField()),
                ('fecha_actualizacion', models.DateField(null=True)),
                ('alias', models.CharField(max_length=100)),
                ('responsable', models.CharField(max_length=50)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.sucursal')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlativo', models.IntegerField()),
                ('estado', models.CharField(max_length=20)),
                ('subTotal', models.IntegerField()),
                ('descuento', models.IntegerField(null=True)),
                ('total', models.IntegerField()),
                ('fecha', models.DateField(auto_now=True)),
                ('responsable', models.CharField(max_length=50)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursal_ticket', to='app.sucursal')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vendedor_ticket', to='app.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket_Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField()),
                ('precio', models.CharField(max_length=20)),
                ('ProductoTalla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_productos_talla', to='app.producto_talla')),
                ('idTicket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_productos', to='app.ticket')),
            ],
        ),
        migrations.AddField(
            model_name='dte',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendedor_dte', to='app.vendedor'),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendedor'),
        ),
    ]
