# Generated by Django 5.2 on 2025-04-08 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresauser',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='empresauser',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
