# Generated by Django 5.2 on 2025-04-08 20:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_empresauser_status_alter_empresauser_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresauser',
            name='sucursal',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app.sucursal'),
        ),
    ]
