# Generated by Django 5.2 on 2025-04-08 20:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_empresauser_sucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresauser',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.sucursal'),
        ),
    ]
