# Generated by Django 5.2 on 2025-04-09 19:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_categoria_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras_producto',
            name='descripcion',
            field=models.CharField(default=2, max_length=200),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AtributoOpcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='app.productos_atributos')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoAtributoValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atributo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productos_atributos')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.atributoopcion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='app.producto')),
            ],
        ),
    ]
