# Generated by Django 5.2 on 2025-04-09 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_compras_producto_descripcion_atributoopcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_recepcionados',
            name='dte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='app.dte'),
        ),
        migrations.AlterField(
            model_name='compras_producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
