# Generated by Django 5.2 on 2025-04-09 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productos_recepcionados_dte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dte',
            name='diasCredito',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
