# Generated by Django 5.2 on 2025-04-10 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dte_diascredito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dte_detalle_pago',
            name='dte',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dte_asociado', to='app.dte'),
        ),
    ]
