# Generated by Django 5.2 on 2025-04-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_dte_detalle_pago_dte'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='fechaInicioTemporada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='compras',
            name='fechaTerminoTemporada',
            field=models.DateField(blank=True, null=True),
        ),
    ]
