# Generated by Django 5.2 on 2025-04-11 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_compras_fechainiciotemporada_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_recepcionados',
            name='producto_talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto_talla'),
        ),
    ]
