# Generated by Django 5.2 on 2025-04-11 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_productos_recepcionados_producto_talla'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresauser',
            name='margenPrecioVenta',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresauser',
            name='margenSobreprecio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
