# Generated by Django 5.2 on 2025-04-11 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_empresauser_margenprecioventa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='precioSugerido',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
