# Generated by Django 5.2 on 2025-04-11 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_producto_preciosugerido'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuiaTalla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cl', models.CharField(blank=True, max_length=20, null=True)),
                ('us', models.CharField(blank=True, max_length=20, null=True)),
                ('eu', models.CharField(blank=True, max_length=20, null=True)),
                ('uk', models.CharField(blank=True, max_length=20, null=True)),
                ('br', models.CharField(blank=True, max_length=20, null=True)),
                ('cm', models.CharField(blank=True, max_length=20, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guia_tallas', to='app.productos_atributos')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guias_talla', to='app.producto')),
            ],
            options={
                'ordering': ['orden', 'fecha_creacion'],
            },
        ),
    ]
