# Generated by Django 5.2 on 2025-04-11 23:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_guiatalla'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guiatalla',
            name='br',
        ),
        migrations.RemoveField(
            model_name='guiatalla',
            name='cl',
        ),
        migrations.RemoveField(
            model_name='guiatalla',
            name='cm',
        ),
        migrations.RemoveField(
            model_name='guiatalla',
            name='eu',
        ),
        migrations.RemoveField(
            model_name='guiatalla',
            name='uk',
        ),
        migrations.RemoveField(
            model_name='guiatalla',
            name='us',
        ),
        migrations.CreateModel(
            name='GuiaTallaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cl', models.CharField(blank=True, max_length=20, null=True)),
                ('us', models.CharField(blank=True, max_length=20, null=True)),
                ('eu', models.CharField(blank=True, max_length=20, null=True)),
                ('uk', models.CharField(blank=True, max_length=20, null=True)),
                ('br', models.CharField(blank=True, max_length=20, null=True)),
                ('cm', models.CharField(blank=True, max_length=20, null=True)),
                ('orden', models.IntegerField(default=0)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.guiatalla')),
            ],
        ),
    ]
