# Generated by Django 5.2 on 2025-04-16 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_guiatalla_br_remove_guiatalla_cl_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guiatalla',
            options={},
        ),
        migrations.RemoveField(
            model_name='guiatalla',
            name='producto',
        ),
        migrations.AlterField(
            model_name='guiatalla',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guia_tallas', to='app.atributoopcion'),
        ),
        migrations.CreateModel(
            name='GuiaTallaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asociacion', models.DateTimeField(auto_now_add=True)),
                ('guia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.guiatalla')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto')),
            ],
            options={
                'unique_together': {('guia', 'producto')},
            },
        ),
        migrations.AddField(
            model_name='guiatalla',
            name='productos',
            field=models.ManyToManyField(blank=True, related_name='guias_de_talla', through='app.GuiaTallaProducto', to='app.producto'),
        ),
    ]
