# Generated by Django 5.2 on 2025-04-16 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_parametroglobal'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras_producto',
            name='tipo_talla',
            field=models.CharField(choices=[('CL', 'CL'), ('US', 'US'), ('EU', 'EU'), ('UK', 'UK'), ('BR', 'BR'), ('CM', 'CM')], default='CL', max_length=5),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_talla',
            field=models.CharField(choices=[('CL', 'CL'), ('US', 'US'), ('EU', 'EU'), ('UK', 'UK'), ('BR', 'BR'), ('CM', 'CM')], default='CL', max_length=5),
        ),
    ]
