# Generated by Django 5.2 on 2025-06-02 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_compras_producto_tipo_talla_producto_tipo_talla'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='atributo4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos_productos4', to='app.productos_atributos'),
        ),
    ]
