# Generated by Django 5.2 on 2025-06-02 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_producto_atributo4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='atributo1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos_productos1', to='app.productos_atributos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='atributo2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos_productos2', to='app.productos_atributos'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='atributo3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atributos_productos3', to='app.productos_atributos'),
        ),
    ]
