# Generated by Django 5.2 on 2025-06-02 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_producto_atributo1_alter_producto_atributo2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='atributo1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_marca', to='app.atributoopcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='atributo2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_color', to='app.atributoopcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='atributo3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_genero', to='app.atributoopcion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='atributo4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='productos_otro', to='app.atributoopcion'),
        ),
    ]
