# Generated by Django 5.2 on 2025-06-02 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_producto_atributo1_alter_producto_atributo2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='guia_talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_principales', to='app.guiatalla'),
        ),
    ]
