# Generated by Django 5.2 on 2025-07-15 22:52

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_producto_guia_talla'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ajuste', models.IntegerField()),
                ('fecha_ajuste', models.DateField(auto_now_add=True)),
                ('tipo_ajuste', models.CharField(choices=[('POSITIVO', 'Ajuste Positivo'), ('NEGATIVO', 'Ajuste Negativo'), ('INVENTARIO_FISICO', 'Inventario Físico')], max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('COMPLETADO', 'Completado')], default='PENDIENTE', max_length=20)),
                ('solicitante', models.CharField(max_length=50)),
                ('aprobador', models.CharField(blank=True, max_length=50, null=True)),
                ('motivo', models.TextField()),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_ajuste'],
            },
        ),
        migrations.CreateModel(
            name='AjusteInventario_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.IntegerField()),
                ('stock_fisico', models.IntegerField()),
                ('diferencia', models.IntegerField()),
                ('costo', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Traspaso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_traspaso', models.IntegerField()),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('fecha_recepcion', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('EN_TRANSITO', 'En Tránsito'), ('RECIBIDO', 'Recibido'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('solicitante', models.CharField(max_length=50)),
                ('aprobador', models.CharField(blank=True, max_length=50, null=True)),
                ('receptor', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones_solicitud', models.TextField(blank=True, null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, null=True)),
                ('observaciones_recepcion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Traspaso_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.IntegerField()),
                ('cantidad_aprobada', models.IntegerField(blank=True, null=True)),
                ('cantidad_enviada', models.IntegerField(blank=True, null=True)),
                ('cantidad_recibida', models.IntegerField(blank=True, null=True)),
                ('costo', models.IntegerField()),
                ('precio_venta', models.IntegerField()),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='movimientos_producto',
            options={'ordering': ['-fecha', '-hora']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-fecha', '-hora']},
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='aprobado_por',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='cantidad',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado'), ('COMPLETADO', 'Completado')], default='COMPLETADO', max_length=20),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='fecha_aprobacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='referencia_externa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_destino', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='sucursal_origen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_origen', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_movimientos', to='app.ticket'),
        ),
        migrations.AddField(
            model_name='movimientos_producto',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_nombre',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_rut',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='hora',
            field=models.TimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro')], default='EFECTIVO', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket',
            name='observaciones',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ticket_productos',
            name='descuento_unitario',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket_productos',
            name='porcentaje_descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='ticket_productos',
            name='precio_original',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket_productos',
            name='subtotal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='concepto',
            field=models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('RECEPCION_COMPRA', 'Recepción de Compra'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('TRASPASO_ENTRADA', 'Traspaso Entrada'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('DONACION_RECIBIDA', 'Donación Recibida'), ('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('TRASPASO_SALIDA', 'Traspaso Salida'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('PERDIDA_ROBO', 'Pérdida por Robo'), ('PERDIDA_DETERIORO', 'Pérdida por Deterioro'), ('DONACION_ENTREGADA', 'Donación Entregada'), ('DEVOLUCION_PROVEEDOR', 'Devolución a Proveedor'), ('TRASPASO_SUCURSAL', 'Traspaso entre Sucursales'), ('TRASPASO_BODEGA', 'Traspaso a Bodega'), ('TRASPASO_VITRINA', 'Traspaso a Vitrina'), ('CAMBIO_PRODUCTO_SALIDA', 'Cambio de Producto (Salida)'), ('CAMBIO_PRODUCTO_ENTRADA', 'Cambio de Producto (Entrada)')], default='INGRESO_INICIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='precio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='responsable',
            field=models.CharField(default='Sistema', max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='sobreprecio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='tipo_movimiento',
            field=models.CharField(choices=[('INGRESO', 'Ingreso'), ('EGRESO', 'Egreso'), ('TRASPASO', 'Traspaso'), ('AJUSTE', 'Ajuste'), ('DEVOLUCION', 'Devolución'), ('PERDIDA', 'Pérdida'), ('DONACION', 'Donación')], default='INGRESO', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descuento',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ANULADO', 'Anulado'), ('DEVUELTO', 'Devuelto')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='ticket_productos',
            name='precio',
            field=models.IntegerField(),
        ),
        migrations.AlterUniqueTogether(
            name='ticket',
            unique_together={('sucursal', 'correlativo')},
        ),
        migrations.AlterUniqueTogether(
            name='ticket_productos',
            unique_together={('ProductoTalla', 'idTicket')},
        ),
        migrations.AddIndex(
            model_name='movimientos_producto',
            index=models.Index(fields=['fecha', 'tipo_movimiento'], name='app_movimie_fecha_7c3fd8_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientos_producto',
            index=models.Index(fields=['ProductoTalla', 'fecha'], name='app_movimie_Product_747217_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientos_producto',
            index=models.Index(fields=['concepto', 'estado'], name='app_movimie_concept_dc5da8_idx'),
        ),
        migrations.AddField(
            model_name='ajusteinventario',
            name='sucursal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_inventario', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='ajusteinventario_detalle',
            name='ajuste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.ajusteinventario'),
        ),
        migrations.AddField(
            model_name='ajusteinventario_detalle',
            name='producto_talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto_talla'),
        ),
        migrations.AddField(
            model_name='traspaso',
            name='sucursal_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_destino', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='traspaso',
            name='sucursal_origen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='traspasos_origen', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='traspaso_detalle',
            name='producto_talla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.producto_talla'),
        ),
        migrations.AddField(
            model_name='traspaso_detalle',
            name='traspaso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.traspaso'),
        ),
        migrations.AlterUniqueTogether(
            name='ajusteinventario',
            unique_together={('sucursal', 'numero_ajuste')},
        ),
        migrations.AlterUniqueTogether(
            name='ajusteinventario_detalle',
            unique_together={('ajuste', 'producto_talla')},
        ),
        migrations.AlterUniqueTogether(
            name='traspaso',
            unique_together={('sucursal_origen', 'numero_traspaso')},
        ),
        migrations.AlterUniqueTogether(
            name='traspaso_detalle',
            unique_together={('traspaso', 'producto_talla')},
        ),
    ]
