# Generated by Django 5.2 on 2025-07-18 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_ajusteinventario_ajusteinventario_detalle_traspaso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket_productos',
            name='costo_fifo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket_productos',
            name='lotes_utilizados',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LoteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_inicial', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
                ('costo_unitario', models.IntegerField()),
                ('sobreprecio_unitario', models.IntegerField(default=0)),
                ('precio_venta_unitario', models.IntegerField()),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('agotado', models.BooleanField(default=False)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('numero_lote', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_producto', to='app.dte')),
                ('movimiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lotes_generados', to='app.movimientos_producto')),
                ('producto_talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='app.producto_talla')),
            ],
            options={
                'ordering': ['fecha_ingreso'],
                'indexes': [models.Index(fields=['producto_talla', 'fecha_ingreso'], name='app_lotepro_product_31985c_idx'), models.Index(fields=['agotado', 'activo'], name='app_lotepro_agotado_cd7fa4_idx'), models.Index(fields=['fecha_vencimiento'], name='app_lotepro_fecha_v_df78cf_idx')],
            },
        ),
    ]
