# Generated by Django 5.2 on 2025-07-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_ticket_productos_costo_fifo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendedor',
            name='comision',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
