# Generated by Django 5.2 on 2025-09-24 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_alter_vendedor_comision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='correlativo',
            options={'verbose_name': 'Correlativo', 'verbose_name_plural': 'Correlativos'},
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_ciudad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_comuna',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_email_facturacion',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_giro',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente_telefono_secundario',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='observaciones_adicionales',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dte',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA ELECTRONICA', 'Factura Electronica'), ('BOLETA ELECTRONICA', 'Boleta Electronica'), ('GUIA', 'Guía de Despacho'), ('NOTA DE PEDIDO', 'Nota de Pedido'), ('NOTA DE CREDITO', 'Nota de Credito'), ('NOTA DE DEBITO', 'Nota de debito'), ('FACTURA EXENTA', 'Factura Exenta'), ('COTIZACION', 'Cotizacion'), ('COMPRA', 'Compra'), ('TICKET', 'Ticket'), ('TRASPASO', 'Traspaso')], max_length=20),
        ),
        migrations.AlterField(
            model_name='dte',
            name='tipo_transaccion',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('TRASPASO', 'Traspaso')], max_length=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], default='EFECTIVO', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='correlativo',
            unique_together={('sucursal', 'tipo_dte')},
        ),
        migrations.CreateModel(
            name='TicketDetallePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], max_length=50)),
                ('tipo_tarjeta', models.CharField(blank=True, max_length=100, null=True)),
                ('voucher', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.IntegerField()),
                ('notas', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app.ticket')),
            ],
            options={
                'verbose_name': 'Detalle de Pago de Ticket',
                'verbose_name_plural': 'Detalles de Pago de Tickets',
                'ordering': ['creado_en'],
            },
        ),
    ]
