# Generated by Django 5.2 on 2025-09-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_alter_correlativo_options_ticket_cliente_ciudad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='modulo_origen',
            field=models.CharField(choices=[('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('POS', 'Punto de Venta')], default='VENTA_PUBLICO', max_length=20),
        ),
        migrations.AlterField(
            model_name='dte',
            name='tipo_transaccion',
            field=models.CharField(choices=[('COMPRA', 'Compra'), ('VENTA', 'Venta'), ('VENTA_PUBLICO', 'Venta al Público'), ('TRASPASO', 'Traspaso')], max_length=15),
        ),
    ]
