# Generated by Django 5.2 on 2025-09-24 19:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_agregar_modulo_origen_y_tipo_transaccion_publico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArqueoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_arqueo', models.DateField()),
                ('total_visa_mc_amex_teorico', models.IntegerField(default=0)),
                ('total_presto_teorico', models.IntegerField(default=0)),
                ('total_abcdin_teorico', models.IntegerField(default=0)),
                ('total_tricot_teorico', models.IntegerField(default=0)),
                ('total_hites_teorico', models.IntegerField(default=0)),
                ('total_ripley_teorico', models.IntegerField(default=0)),
                ('total_falabella_teorico', models.IntegerField(default=0)),
                ('total_paris_teorico', models.IntegerField(default=0)),
                ('total_tarjetas_comerciales_teorico', models.IntegerField(default=0)),
                ('total_efectivo_teorico', models.IntegerField(default=0)),
                ('total_webpay_teorico', models.IntegerField(default=0)),
                ('total_mercadolibre_teorico', models.IntegerField(default=0)),
                ('total_mercadopago_teorico', models.IntegerField(default=0)),
                ('total_transferencia_internet_teorico', models.IntegerField(default=0)),
                ('total_venta_internet_teorico', models.IntegerField(default=0)),
                ('total_tarjeta_debito_teorico', models.IntegerField(default=0)),
                ('total_tarjeta_credito_teorico', models.IntegerField(default=0)),
                ('total_transbank_teorico', models.IntegerField(default=0)),
                ('total_transferencia_teorico', models.IntegerField(default=0)),
                ('total_cheque_teorico', models.IntegerField(default=0)),
                ('total_convenio_teorico', models.IntegerField(default=0)),
                ('total_tickets_teorico', models.IntegerField(default=0)),
                ('total_boletas_electronicas_teorico', models.IntegerField(default=0)),
                ('total_facturas_teorico', models.IntegerField(default=0)),
                ('total_facturas_exentas_teorico', models.IntegerField(default=0)),
                ('total_notas_credito_teorico', models.IntegerField(default=0)),
                ('cantidad_tickets', models.IntegerField(default=0)),
                ('cantidad_boletas_electronicas', models.IntegerField(default=0)),
                ('cantidad_facturas', models.IntegerField(default=0)),
                ('cantidad_facturas_exentas', models.IntegerField(default=0)),
                ('venta_total_teorica', models.IntegerField(default=0)),
                ('billetes_20000', models.IntegerField(default=0)),
                ('billetes_10000', models.IntegerField(default=0)),
                ('billetes_5000', models.IntegerField(default=0)),
                ('billetes_2000', models.IntegerField(default=0)),
                ('billetes_1000', models.IntegerField(default=0)),
                ('monedas_500', models.IntegerField(default=0)),
                ('monedas_100', models.IntegerField(default=0)),
                ('monedas_50', models.IntegerField(default=0)),
                ('monedas_10', models.IntegerField(default=0)),
                ('monedas_5', models.IntegerField(default=0)),
                ('monedas_1', models.IntegerField(default=0)),
                ('total_efectivo_fisico', models.IntegerField(default=0)),
                ('diferencia_efectivo', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('ABIERTO', 'En Proceso'), ('CERRADO', 'Finalizado'), ('CON_DIFERENCIAS', 'Con Diferencias'), ('REVISADO', 'Revisado por Supervisor')], default='ABIERTO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('observaciones_diferencia', models.TextField(blank=True, null=True)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('observaciones_supervisor', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos_caja', to='app.sucursal')),
                ('supervisor_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arqueos_supervisados', to=settings.AUTH_USER_MODEL)),
                ('usuario_responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arqueos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Arqueo de Caja',
                'verbose_name_plural': 'Arqueos de Caja',
                'ordering': ['-fecha_arqueo', '-fecha_creacion'],
                'indexes': [models.Index(fields=['fecha_arqueo', 'sucursal'], name='app_arqueoc_fecha_a_e3c370_idx'), models.Index(fields=['estado', 'fecha_arqueo'], name='app_arqueoc_estado_8c290a_idx'), models.Index(fields=['diferencia_efectivo'], name='app_arqueoc_diferen_11ba84_idx')],
                'unique_together': {('fecha_arqueo', 'sucursal')},
            },
        ),
    ]
