# Generated by Django 5.2 on 2025-09-24 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_arqueocaja'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_credito', models.CharField(help_text='Número único del crédito', max_length=50, unique=True)),
                ('tipo_credito', models.CharField(choices=[('ANTICIPO_SUELDO', 'Anticipo de Sueldo'), ('PRESTAMO_EMPRESA', 'Préstamo de Empresa'), ('CREDITO_COMPRA', 'Crédito para Compra'), ('EMERGENCIA', 'Crédito de Emergencia'), ('OTRO', 'Otro')], default='PRESTAMO_EMPRESA', max_length=20)),
                ('monto_solicitado', models.DecimalField(decimal_places=2, help_text='Monto solicitado', max_digits=12)),
                ('monto_aprobado', models.DecimalField(blank=True, decimal_places=2, help_text='Monto aprobado', max_digits=12, null=True)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado hasta la fecha', max_digits=12)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateField(help_text='Fecha límite para pago')),
                ('fecha_primer_pago', models.DateField(blank=True, help_text='Fecha del primer pago programado', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Aprobación'), ('APROBADO', 'Aprobado'), ('ACTIVO', 'Activo'), ('PAGADO', 'Pagado Completamente'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado'), ('RECHAZADO', 'Rechazado')], default='PENDIENTE', max_length=20)),
                ('tasa_interes', models.DecimalField(decimal_places=2, default=0, help_text='Tasa de interés mensual (%)', max_digits=5)),
                ('numero_cuotas', models.IntegerField(default=1, help_text='Número de cuotas para el pago')),
                ('valor_cuota', models.DecimalField(blank=True, decimal_places=2, help_text='Valor de cada cuota (calculado automáticamente)', max_digits=12, null=True)),
                ('motivo_solicitud', models.TextField(help_text='Motivo o justificación del crédito')),
                ('observaciones_solicitud', models.TextField(blank=True, null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, null=True)),
                ('observaciones_rechazo', models.TextField(blank=True, null=True)),
                ('requiere_aval', models.BooleanField(default=False)),
                ('aval_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('aval_rut', models.CharField(blank=True, max_length=20, null=True)),
                ('aval_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(blank=True, help_text='Usuario que autorizó el crédito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_autorizados', to=settings.AUTH_USER_MODEL)),
                ('empresa_origen', models.ForeignKey(help_text='Empresa que otorga el crédito', on_delete=django.db.models.deletion.CASCADE, related_name='creditos_otorgados', to='app.empresa')),
                ('solicitado_por', models.ForeignKey(help_text='Usuario que registró la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='creditos_solicitados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(help_text='Sucursal donde se otorga el crédito', on_delete=django.db.models.deletion.CASCADE, related_name='creditos_sucursal', to='app.sucursal')),
                ('trabajador', models.ForeignKey(help_text='Trabajador/Vendedor que recibe el crédito', on_delete=django.db.models.deletion.CASCADE, related_name='creditos_recibidos', to='app.vendedor')),
            ],
            options={
                'verbose_name': 'Crédito de Trabajador',
                'verbose_name_plural': 'Créditos de Trabajadores',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='FirmaCreditoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firmado_por_trabajador', models.BooleanField(default=False)),
                ('fecha_firma_trabajador', models.DateTimeField(blank=True, null=True)),
                ('firma_trabajador_data', models.TextField(blank=True, help_text='Datos de la firma digital del trabajador', null=True)),
                ('firmado_por_autorizador', models.BooleanField(default=False)),
                ('fecha_firma_autorizador', models.DateTimeField(blank=True, null=True)),
                ('firma_autorizador_data', models.TextField(blank=True, help_text='Datos de la firma digital del autorizador', null=True)),
                ('firmado_por_aval', models.BooleanField(default=False)),
                ('fecha_firma_aval', models.DateTimeField(blank=True, null=True)),
                ('firma_aval_data', models.TextField(blank=True, help_text='Datos de la firma digital del aval', null=True)),
                ('ip_firma_trabajador', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_firma_autorizador', models.GenericIPAddressField(blank=True, null=True)),
                ('ip_firma_aval', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credito', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='firma', to='app.creditotrabajador')),
            ],
            options={
                'verbose_name': 'Firma de Crédito',
                'verbose_name_plural': 'Firmas de Créditos',
            },
        ),
        migrations.CreateModel(
            name='PagoCreditoTrabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pago', models.CharField(help_text='Número del pago/abono', max_length=50)),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_pago', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], default='EFECTIVO', max_length=50)),
                ('numero_cuota', models.IntegerField(blank=True, help_text='Número de cuota si aplica', null=True)),
                ('es_pago_total', models.BooleanField(default=False, help_text='Si es el pago total del crédito')),
                ('referencia_pago', models.CharField(blank=True, help_text='Referencia del pago (voucher, etc.)', max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app.creditotrabajador')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_credito_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Crédito',
                'verbose_name_plural': 'Pagos de Créditos',
                'ordering': ['-fecha_pago', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='creditotrabajador',
            index=models.Index(fields=['numero_credito'], name='app_credito_numero__4126a7_idx'),
        ),
        migrations.AddIndex(
            model_name='creditotrabajador',
            index=models.Index(fields=['trabajador', 'estado'], name='app_credito_trabaja_f8800d_idx'),
        ),
        migrations.AddIndex(
            model_name='creditotrabajador',
            index=models.Index(fields=['empresa_origen', 'fecha_solicitud'], name='app_credito_empresa_0a7003_idx'),
        ),
        migrations.AddIndex(
            model_name='creditotrabajador',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='app_credito_estado_0f60e6_idx'),
        ),
        migrations.AddIndex(
            model_name='pagocreditotrabajador',
            index=models.Index(fields=['credito', 'fecha_pago'], name='app_pagocre_credito_9b3421_idx'),
        ),
        migrations.AddIndex(
            model_name='pagocreditotrabajador',
            index=models.Index(fields=['numero_pago'], name='app_pagocre_numero__b0b765_idx'),
        ),
    ]
