# Generated by Django 5.2 on 2025-09-25 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_creditotrabajador_firmacreditotrabajador_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocreditotrabajador',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], default='EFECTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], default='EFECTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketdetallepago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], max_length=50),
        ),
        migrations.CreateModel(
            name='ConfiguracionPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificativo del terminal', max_length=100)),
                ('tipo_pos', models.CharField(choices=[('VERIFONE_VX520', 'Verifone VX520'), ('INGENICO_3500', 'Ingenico 3500'), ('INGENICO_DESK', 'Ingenico DESK'), ('OTRO', 'Otro')], max_length=20)),
                ('puerto_conexion', models.CharField(help_text='Puerto de conexión (COM1, /dev/ttyUSB0, etc.)', max_length=20)),
                ('velocidad_conexion', models.IntegerField(default=115200, help_text='Velocidad de conexión en bps')),
                ('activo', models.BooleanField(default=True)),
                ('es_principal', models.BooleanField(default=False, help_text='Terminal principal para esta sucursal')),
                ('timeout_conexion', models.IntegerField(default=30, help_text='Timeout de conexión en segundos')),
                ('numero_serie', models.CharField(blank=True, max_length=50, null=True)),
                ('version_firmware', models.CharField(blank=True, max_length=20, null=True)),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True)),
                ('estado_conexion', models.CharField(choices=[('CONECTADO', 'Conectado'), ('DESCONECTADO', 'Desconectado'), ('ERROR', 'Error'), ('NO_PROBADO', 'No Probado')], default='NO_PROBADO', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configuraciones_pos', to='app.sucursal')),
            ],
            options={
                'verbose_name': 'Configuración POS',
                'verbose_name_plural': 'Configuraciones POS',
                'ordering': ['sucursal', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_pos', models.CharField(help_text='Ticket único generado para la transacción POS', max_length=50, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo_transaccion', models.CharField(choices=[('VENTA', 'Venta'), ('ANULACION', 'Anulación'), ('DEVOLUCION', 'Devolución')], default='VENTA', max_length=20)),
                ('estado', models.CharField(choices=[('INICIADA', 'Iniciada'), ('ESPERANDO_TARJETA', 'Esperando Tarjeta'), ('PROCESANDO', 'Procesando'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('ANULADA', 'Anulada'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout')], default='INICIADA', max_length=20)),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('fecha_completada', models.DateTimeField(blank=True, null=True)),
                ('codigo_respuesta', models.CharField(blank=True, max_length=10, null=True)),
                ('mensaje_respuesta', models.CharField(blank=True, max_length=200, null=True)),
                ('codigo_autorizacion', models.CharField(blank=True, max_length=20, null=True)),
                ('tipo_tarjeta', models.CharField(blank=True, choices=[('DEBITO', 'Débito'), ('CREDITO', 'Crédito'), ('PREPAGO', 'Prepago'), ('DESCONOCIDO', 'Desconocido')], max_length=20, null=True)),
                ('ultimos_4_digitos', models.CharField(blank=True, max_length=4, null=True)),
                ('nombre_tarjeta', models.CharField(blank=True, max_length=50, null=True)),
                ('numero_operacion', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_cuotas', models.IntegerField(default=1)),
                ('codigo_comercio', models.CharField(blank=True, max_length=20, null=True)),
                ('terminal_id', models.CharField(blank=True, max_length=20, null=True)),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('error_detalle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('configuracion_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='app.configuracionpos')),
                ('detalle_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaccion_pos', to='app.ticketdetallepago')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transacciones_pos', to='app.ticket')),
                ('usuario_operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transacciones_pos_operadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transacción POS',
                'verbose_name_plural': 'Transacciones POS',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('CONEXION', 'Conexión'), ('DESCONEXION', 'Desconexión'), ('COMANDO_ENVIADO', 'Comando Enviado'), ('RESPUESTA_RECIBIDA', 'Respuesta Recibida'), ('ERROR', 'Error'), ('TIMEOUT', 'Timeout'), ('INFO', 'Información')], max_length=20)),
                ('mensaje', models.TextField()),
                ('datos_tecnicos', models.JSONField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('configuracion_pos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.configuracionpos')),
                ('transaccion_pos', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='app.transaccionpos')),
            ],
            options={
                'verbose_name': 'Log POS',
                'verbose_name_plural': 'Logs POS',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='configuracionpos',
            index=models.Index(fields=['sucursal', 'activo'], name='app_configu_sucursa_bbd7ff_idx'),
        ),
        migrations.AddIndex(
            model_name='configuracionpos',
            index=models.Index(fields=['tipo_pos', 'activo'], name='app_configu_tipo_po_8e2f3f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configuracionpos',
            unique_together={('sucursal', 'nombre')},
        ),
        migrations.AddIndex(
            model_name='transaccionpos',
            index=models.Index(fields=['ticket_pos'], name='app_transac_ticket__337f31_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionpos',
            index=models.Index(fields=['configuracion_pos', 'fecha_inicio'], name='app_transac_configu_128753_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionpos',
            index=models.Index(fields=['estado', 'fecha_inicio'], name='app_transac_estado_038ef8_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionpos',
            index=models.Index(fields=['codigo_autorizacion'], name='app_transac_codigo__b929fa_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccionpos',
            index=models.Index(fields=['ticket', 'estado'], name='app_transac_ticket__d5ef8f_idx'),
        ),
        migrations.AddIndex(
            model_name='logpos',
            index=models.Index(fields=['configuracion_pos', 'timestamp'], name='app_logpos_configu_18f623_idx'),
        ),
        migrations.AddIndex(
            model_name='logpos',
            index=models.Index(fields=['tipo_evento', 'timestamp'], name='app_logpos_tipo_ev_45f32a_idx'),
        ),
        migrations.AddIndex(
            model_name='logpos',
            index=models.Index(fields=['transaccion_pos', 'timestamp'], name='app_logpos_transac_ada263_idx'),
        ),
    ]
