# Generated by Django 5.2 on 2025-09-25 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_add_pos_transbank_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.CharField(help_text='Número único de la operación de cambio', max_length=50, unique=True)),
                ('tipo_operacion', models.CharField(choices=[('CAMBIO_SIMPLE', 'Cambio Simple'), ('CAMBIO_CON_DIFERENCIA', 'Cambio con Diferencia de Precio'), ('DEVOLUCION_TOTAL', 'Devolución Total'), ('DEVOLUCION_PARCIAL', 'Devolución Parcial')], help_text='Tipo de operación realizada', max_length=30)),
                ('estado', models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('APROBADO', 'Aprobado'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_completado', models.DateTimeField(blank=True, null=True)),
                ('fecha_limite_cambio', models.DateField(help_text='Fecha límite para realizar el cambio')),
                ('monto_original', models.DecimalField(decimal_places=2, help_text='Monto total del ticket original', max_digits=12)),
                ('monto_nuevo', models.DecimalField(decimal_places=2, default=0, help_text='Monto del nuevo ticket (si aplica)', max_digits=12)),
                ('diferencia_monto', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia de precio (positivo: cliente paga, negativo: se devuelve)', max_digits=12)),
                ('motivo_principal', models.CharField(choices=[('TALLA_INCORRECTA', 'Talla Incorrecta'), ('COLOR_INCORRECTO', 'Color Incorrecto'), ('DEFECTO_PRODUCTO', 'Defecto en el Producto'), ('NO_SATISFACE', 'No Satisface Expectativas'), ('REGALO_NO_DESEADO', 'Regalo No Deseado'), ('CAMBIO_OPINION', 'Cambio de Opinión'), ('PRODUCTO_DAÑADO', 'Producto Dañado en Transporte'), ('OTRO', 'Otro Motivo')], help_text='Motivo principal del cambio', max_length=30)),
                ('observaciones_cliente', models.TextField(blank=True, help_text='Observaciones del cliente', null=True)),
                ('observaciones_vendedor', models.TextField(blank=True, help_text='Observaciones del vendedor', null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, help_text='Observaciones de la aprobación/rechazo', null=True)),
                ('requiere_autorizacion', models.BooleanField(default=False, help_text='Si requiere autorización especial')),
                ('autorizado_excepcion', models.BooleanField(default=False, help_text='Si fue autorizado como excepción a las políticas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('aprobado_por', models.ForeignKey(blank=True, help_text='Usuario que aprobó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_aprobados', to=settings.AUTH_USER_MODEL)),
                ('solicitado_por', models.ForeignKey(help_text='Usuario que registró la solicitud', on_delete=django.db.models.deletion.CASCADE, related_name='cambios_solicitados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_sucursal', to='app.sucursal')),
                ('ticket_nuevo', models.ForeignKey(blank=True, help_text='Nuevo ticket generado por el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_generados', to='app.ticket')),
                ('ticket_original', models.ForeignKey(help_text='Ticket original de la venta', on_delete=django.db.models.deletion.CASCADE, related_name='cambios_devoluciones', to='app.ticket')),
            ],
            options={
                'verbose_name': 'Cambio/Devolución',
                'verbose_name_plural': 'Cambios y Devoluciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='CambioDevolucionDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_original', models.IntegerField(help_text='Cantidad del producto original a cambiar/devolver')),
                ('cantidad_nueva', models.IntegerField(default=0, help_text='Cantidad del nuevo producto')),
                ('precio_nuevo', models.DecimalField(decimal_places=2, default=0, help_text='Precio del nuevo producto', max_digits=10)),
                ('condicion_producto', models.CharField(choices=[('PERFECTO', 'Perfecto Estado'), ('BUENO', 'Buen Estado'), ('REGULAR', 'Estado Regular'), ('DAÑADO', 'Dañado'), ('NO_APTO', 'No Apto para Cambio')], help_text='Condición del producto devuelto', max_length=20)),
                ('apto_para_venta', models.BooleanField(default=True, help_text='Si el producto devuelto está apto para venta')),
                ('precio_original_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario original', max_digits=10)),
                ('diferencia_unitaria', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia de precio por unidad', max_digits=10)),
                ('diferencia_total', models.DecimalField(decimal_places=2, default=0, help_text='Diferencia total para esta línea', max_digits=10)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas de este producto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cambio_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.cambiodevolucion')),
                ('producto_nuevo', models.ForeignKey(blank=True, help_text='Nuevo producto en caso de cambio', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cambios_como_nuevo', to='app.producto_talla')),
                ('producto_original', models.ForeignKey(help_text='Producto del ticket original que se cambia/devuelve', on_delete=django.db.models.deletion.CASCADE, related_name='cambios_como_original', to='app.ticket_productos')),
            ],
            options={
                'verbose_name': 'Detalle de Cambio/Devolución',
                'verbose_name_plural': 'Detalles de Cambios/Devoluciones',
            },
        ),
        migrations.CreateModel(
            name='HistorialCambioDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADO', 'Creado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('MODIFICADO', 'Modificado'), ('PAGO_PROCESADO', 'Pago Procesado'), ('PRODUCTO_EVALUADO', 'Producto Evaluado')], max_length=50)),
                ('estado_anterior', models.CharField(blank=True, max_length=20, null=True)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.TextField(help_text='Descripción de la acción realizada')),
                ('datos_adicionales', models.JSONField(blank=True, help_text='Datos adicionales en formato JSON', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cambio_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app.cambiodevolucion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_cambio_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambio/Devolución',
                'verbose_name_plural': 'Historiales de Cambios/Devoluciones',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='PagoCambioDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(choices=[('PAGO_DIFERENCIA', 'Pago de Diferencia'), ('DEVOLUCION_EFECTIVO', 'Devolución en Efectivo'), ('DEVOLUCION_TARJETA', 'Devolución a Tarjeta'), ('CREDITO_TIENDA', 'Crédito en Tienda')], max_length=20)),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia_pago', models.CharField(blank=True, help_text='Referencia del pago (voucher, autorización, etc.)', max_length=100, null=True)),
                ('numero_autorizacion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento_credito', models.DateField(blank=True, help_text='Fecha de vencimiento si es crédito en tienda', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cambio_devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app.cambiodevolucion')),
                ('procesado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos_cambio_procesados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pago de Cambio/Devolución',
                'verbose_name_plural': 'Pagos de Cambios/Devoluciones',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.AddIndex(
            model_name='cambiodevolucion',
            index=models.Index(fields=['numero_operacion'], name='app_cambiod_numero__e726f8_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiodevolucion',
            index=models.Index(fields=['ticket_original', 'estado'], name='app_cambiod_ticket__f99e40_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiodevolucion',
            index=models.Index(fields=['sucursal', 'fecha_solicitud'], name='app_cambiod_sucursa_15200f_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiodevolucion',
            index=models.Index(fields=['estado', 'fecha_solicitud'], name='app_cambiod_estado_e88ada_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiodevolucion',
            index=models.Index(fields=['tipo_operacion', 'fecha_solicitud'], name='app_cambiod_tipo_op_aa9fdf_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiodevoluciondetalle',
            index=models.Index(fields=['cambio_devolucion', 'producto_original'], name='app_cambiod_cambio__318952_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiodevoluciondetalle',
            index=models.Index(fields=['condicion_producto', 'apto_para_venta'], name='app_cambiod_condici_0f3133_idx'),
        ),
    ]
