# Generated by Django 5.2 on 2025-10-27 14:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_cambiodevolucion_cambiodevoluciondetalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Historial_Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREADA', 'Cotización Creada'), ('MODIFICADA', 'Cotización Modificada'), ('ANULADA', 'Cotización Anulada'), ('FACTURADA', 'Convertida a Factura'), ('ENVIADA', 'Enviada al Cliente'), ('VENCIDA', 'Marcada como Vencida'), ('ITEM_AGREGADO', 'Item Agregado'), ('ITEM_MODIFICADO', 'Item Modificado'), ('ITEM_ELIMINADO', 'Item Eliminado')], max_length=50)),
                ('descripcion', models.TextField(help_text='Descripción de la acción realizada')),
                ('datos_anteriores', models.JSONField(blank=True, help_text='Datos antes del cambio (JSON)', null=True)),
                ('datos_nuevos', models.JSONField(blank=True, help_text='Datos después del cambio (JSON)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Dirección IP desde donde se realizó la acción', null=True)),
            ],
            options={
                'verbose_name': 'Historial de Cotización',
                'verbose_name_plural': 'Historiales de Cotización',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='cotizacion_detalle',
            options={'ordering': ['cotizacion', 'numero_linea'], 'verbose_name': 'Detalle de Cotización', 'verbose_name_plural': 'Detalles de Cotización'},
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='costo',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='precio',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='producto_talla',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='sobreprecio',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='stock',
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Cantidad cotizada'),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='descripcion_producto_pendiente',
            field=models.TextField(blank=True, help_text='Descripción del producto pendiente', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuento', max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado', max_digits=5),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='es_producto_pendiente',
            field=models.BooleanField(default=False, help_text='Indica si el producto aún no está creado en el sistema'),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='fecha_llegada_estimada',
            field=models.DateField(blank=True, help_text='Fecha estimada de llegada si es producto pendiente', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='nombre_producto_pendiente',
            field=models.CharField(blank=True, help_text='Nombre del producto pendiente', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='numero_linea',
            field=models.IntegerField(default=1, help_text='Número de línea del item'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones específicas del item', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Precio unitario comprometido en la cotización', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='producto_existente',
            field=models.ForeignKey(blank=True, help_text='Producto existente en inventario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_asociadas', to='app.producto_talla'),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='sku_producto_pendiente',
            field=models.CharField(blank=True, help_text='SKU esperado del producto pendiente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='stock_disponible',
            field=models.IntegerField(default=0, help_text='Stock disponible al momento de la cotización'),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Subtotal del item (cantidad * precio - descuento)', max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='configuracionpos',
            name='estado_conexion',
            field=models.CharField(choices=[('CONECTADO', 'Conectado'), ('DESCONECTADO', 'Desconectado'), ('DETECTADO', 'Detectado Automáticamente'), ('ERROR', 'Error'), ('NO_PROBADO', 'No Probado')], default='NO_PROBADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='descripcion',
            field=models.TextField(help_text='Descripción del item en la cotización'),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PENDIENTE_RECEPCION', 'Pendiente de Recepción'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado'), ('COMPLETADO', 'Completado')], default='COMPLETADO', max_length=20),
        ),
        migrations.CreateModel(
            name='Cotizacion_Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cotizacion', models.CharField(help_text='Número único de cotización', max_length=20, unique=True)),
                ('fecha_emision', models.DateField(default=django.utils.timezone.now, help_text='Fecha de emisión de la cotización')),
                ('fecha_validez', models.DateField(help_text='Fecha hasta la cual la cotización es válida')),
                ('dias_validez', models.IntegerField(default=30, help_text='Días de validez de la cotización')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general de la cotización', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones, condiciones de pago, notas adicionales', null=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, help_text='Subtotal de la cotización sin impuestos', max_digits=12)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, help_text='Descuento aplicado', max_digits=12)),
                ('impuesto', models.DecimalField(decimal_places=2, default=0, help_text='Impuestos (IVA)', max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, help_text='Total de la cotización', max_digits=12)),
                ('estado', models.CharField(choices=[('VIGENTE', 'Vigente'), ('VENCIDA', 'Vencida'), ('FACTURADA', 'Facturada'), ('ANULADA', 'Anulada')], default='VIGENTE', max_length=20)),
                ('facturada', models.BooleanField(default=False, help_text='Indica si la cotización fue convertida en factura')),
                ('numero_factura', models.CharField(blank=True, help_text='Número de factura si fue facturada', max_length=20, null=True)),
                ('fecha_facturacion', models.DateTimeField(blank=True, help_text='Fecha en que se facturó', null=True)),
                ('archivo_pdf', models.FileField(blank=True, help_text='PDF de la cotización', null=True, upload_to='cotizaciones/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fecha_anulacion', models.DateTimeField(blank=True, null=True)),
                ('motivo_anulacion', models.TextField(blank=True, null=True)),
                ('anulada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_anuladas', to=settings.AUTH_USER_MODEL)),
                ('cliente', models.ForeignKey(help_text='Cliente/Empresa que recibe la cotización', on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_recibidas', to='app.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='app.sucursal')),
                ('usuario_creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='app.vendedor')),
            ],
            options={
                'verbose_name': 'Cotización',
                'verbose_name_plural': 'Cotizaciones',
                'ordering': ['-fecha_emision', '-numero_cotizacion'],
            },
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cotizacion_empresa'),
        ),
        migrations.AddIndex(
            model_name='cotizacion_detalle',
            index=models.Index(fields=['cotizacion', 'numero_linea'], name='app_cotizac_cotizac_afec15_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion_detalle',
            index=models.Index(fields=['producto_existente'], name='app_cotizac_product_257c99_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion_detalle',
            index=models.Index(fields=['es_producto_pendiente'], name='app_cotizac_es_prod_c30e63_idx'),
        ),
        migrations.AddField(
            model_name='historial_cotizacion',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app.cotizacion_empresa'),
        ),
        migrations.AddField(
            model_name='historial_cotizacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_cotizacion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='cotizacion_empresa',
            index=models.Index(fields=['numero_cotizacion'], name='app_cotizac_numero__ed559a_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion_empresa',
            index=models.Index(fields=['sucursal', 'fecha_emision'], name='app_cotizac_sucursa_a7fec4_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion_empresa',
            index=models.Index(fields=['cliente', 'estado'], name='app_cotizac_cliente_615b59_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion_empresa',
            index=models.Index(fields=['fecha_validez', 'estado'], name='app_cotizac_fecha_v_3e9583_idx'),
        ),
    ]
