# Generated by Django 5.2 on 2025-10-27 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_historial_cotizacion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productos_recepcionados',
            options={'verbose_name': 'Producto Recepcionado', 'verbose_name_plural': 'Productos Recepcionados'},
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='cantidad_danada',
            field=models.IntegerField(default=0, help_text='Cantidad con daños'),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='cantidad_esperada',
            field=models.IntegerField(default=0, help_text='Cantidad original esperada'),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='cantidad_faltante',
            field=models.IntegerField(default=0, help_text='Cantidad que no llegó'),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='dte_producto',
            field=models.ForeignKey(blank=True, help_text='Producto específico del DTE', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recepcion', to='app.dte_productos'),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Recepción'), ('RECEPCIONADO_OK', 'Recepcionado OK'), ('RECEPCIONADO_PARCIAL', 'Recepcionado Parcial'), ('RECEPCIONADO_DANADO', 'Recepcionado con Daños'), ('FALTANTE', 'Faltante'), ('EN_REGULARIZACION', 'En Regularización'), ('REGULARIZADO', 'Regularizado')], default='RECEPCIONADO_OK', help_text='Estado de la recepción', max_length=30),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='fecha_recepcion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='fecha_regularizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='observaciones',
            field=models.TextField(blank=True, help_text='Observaciones o problemas', null=True),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='recepcionado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='regularizado_por',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='dte',
            name='estado_dte',
            field=models.CharField(choices=[('EMITIDO', 'Emitido'), ('ACEPTADO', 'Aceptado'), ('RECEPCIONADO_COMPLETO', 'Recepcionado Completo'), ('RECEPCIONADO_PARCIAL', 'Recepcionado Parcial'), ('EN_REGULARIZACION', 'En Regularización'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='productos_recepcionados',
            name='compra_producto_talla',
            field=models.ForeignKey(blank=True, help_text='Para recepciones de compras', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.compras_producto_talla'),
        ),
        migrations.AlterField(
            model_name='productos_recepcionados',
            name='dte',
            field=models.ForeignKey(blank=True, help_text='DTE de traspaso interno', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones', to='app.dte'),
        ),
        migrations.AlterField(
            model_name='productos_recepcionados',
            name='stockArribado',
            field=models.IntegerField(help_text='Cantidad recepcionada (nombre legacy)'),
        ),
        migrations.AddIndex(
            model_name='productos_recepcionados',
            index=models.Index(fields=['dte', 'estado'], name='app_product_dte_id_6dbb28_idx'),
        ),
        migrations.AddIndex(
            model_name='productos_recepcionados',
            index=models.Index(fields=['estado'], name='app_product_estado_97d14b_idx'),
        ),
        migrations.AddIndex(
            model_name='productos_recepcionados',
            index=models.Index(fields=['fecha'], name='app_product_fecha_ae05c1_idx'),
        ),
    ]
