# Generated by Django 5.2 on 2025-10-27 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_alter_productos_recepcionados_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dte',
            name='documento_afectado',
            field=models.ForeignKey(blank=True, help_text='DTE original que se está corrigiendo (solo para NC)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notas_credito_relacionadas', to='app.dte'),
        ),
        migrations.AddField(
            model_name='dte',
            name='es_nota_credito',
            field=models.BooleanField(default=False, help_text='Indica si es una Nota de Crédito'),
        ),
        migrations.AddField(
            model_name='dte',
            name='motivo_nc',
            field=models.TextField(blank=True, help_text='Motivo de la Nota de Crédito', null=True),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='concepto',
            field=models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('RECEPCION_COMPRA', 'Recepción de Compra'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('TRASPASO_ENTRADA', 'Traspaso Entrada'), ('REGULARIZACION_TRASPASO', 'Regularización de Traspaso'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('DONACION_RECIBIDA', 'Donación Recibida'), ('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('TRASPASO_SALIDA', 'Traspaso Salida'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('PERDIDA_ROBO', 'Pérdida por Robo'), ('PERDIDA_DETERIORO', 'Pérdida por Deterioro'), ('DONACION_ENTREGADA', 'Donación Entregada'), ('DEVOLUCION_PROVEEDOR', 'Devolución a Proveedor'), ('TRASPASO_SUCURSAL', 'Traspaso entre Sucursales'), ('TRASPASO_BODEGA', 'Traspaso a Bodega'), ('TRASPASO_VITRINA', 'Traspaso a Vitrina'), ('CAMBIO_PRODUCTO_SALIDA', 'Cambio de Producto (Salida)'), ('CAMBIO_PRODUCTO_ENTRADA', 'Cambio de Producto (Entrada)')], default='INGRESO_INICIAL', max_length=50),
        ),
    ]
