# Generated by Django 5.2 on 2025-10-28 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_dte_documento_afectado_dte_es_nota_credito_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion_Empresa_Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_producto_pendiente', models.BooleanField(default=False, help_text='Indica si el producto aún no está creado en el sistema')),
                ('nombre_producto_pendiente', models.CharField(blank=True, help_text='Nombre del producto pendiente', max_length=255, null=True)),
                ('descripcion_producto_pendiente', models.TextField(blank=True, help_text='Descripción del producto pendiente', null=True)),
                ('sku_producto_pendiente', models.CharField(blank=True, help_text='SKU esperado del producto pendiente', max_length=100, null=True)),
                ('numero_linea', models.IntegerField(help_text='Número de línea del item')),
                ('descripcion', models.TextField(help_text='Descripción del item en la cotización')),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad cotizada')),
                ('precio_unitario', models.DecimalField(decimal_places=2, help_text='Precio unitario comprometido en la cotización', max_digits=12)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de descuento aplicado', max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, help_text='Monto de descuento', max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, help_text='Subtotal del item (cantidad * precio - descuento)', max_digits=12)),
                ('stock_disponible', models.IntegerField(default=0, help_text='Stock disponible al momento de la cotización')),
                ('fecha_llegada_estimada', models.DateField(blank=True, help_text='Fecha estimada de llegada si es producto pendiente', null=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones específicas del item', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Detalle de Cotización',
                'verbose_name_plural': 'Detalles de Cotización',
                'ordering': ['cotizacion', 'numero_linea'],
            },
        ),
        migrations.AlterModelOptions(
            name='cotizacion_detalle',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='cotizacion_detalle',
            name='app_cotizac_cotizac_afec15_idx',
        ),
        migrations.RemoveIndex(
            model_name='cotizacion_detalle',
            name='app_cotizac_product_257c99_idx',
        ),
        migrations.RemoveIndex(
            model_name='cotizacion_detalle',
            name='app_cotizac_es_prod_c30e63_idx',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='descripcion_producto_pendiente',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='descuento_monto',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='descuento_porcentaje',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='es_producto_pendiente',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='fecha_llegada_estimada',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='nombre_producto_pendiente',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='numero_linea',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='producto_existente',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='sku_producto_pendiente',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='stock_disponible',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='subtotal',
        ),
        migrations.RemoveField(
            model_name='cotizacion_detalle',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='costo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='precio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='producto_talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.producto_talla'),
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='sobreprecio',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cotizacion_detalle',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cotizacion'),
        ),
        migrations.AlterField(
            model_name='cotizacion_detalle',
            name='descripcion',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='cotizacion_empresa_detalle',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.cotizacion_empresa'),
        ),
        migrations.AddField(
            model_name='cotizacion_empresa_detalle',
            name='producto_existente',
            field=models.ForeignKey(blank=True, help_text='Producto existente en inventario', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_asociadas', to='app.producto_talla'),
        ),
        migrations.AddIndex(
            model_name='cotizacion_empresa_detalle',
            index=models.Index(fields=['cotizacion', 'numero_linea'], name='app_cotizac_cotizac_5235cb_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion_empresa_detalle',
            index=models.Index(fields=['producto_existente'], name='app_cotizac_product_e5c4c7_idx'),
        ),
        migrations.AddIndex(
            model_name='cotizacion_empresa_detalle',
            index=models.Index(fields=['es_producto_pendiente'], name='app_cotizac_es_prod_b8cb11_idx'),
        ),
    ]
