# Generated by Django 5.2 on 2025-11-03 14:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_cotizacion_empresa_detalle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositoBancario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deposito', models.DateField(help_text='Fecha en que se realizó el depósito bancario')),
                ('monto', models.IntegerField(default=0, help_text='Monto depositado en pesos chilenos')),
                ('banco', models.CharField(choices=[('ESTADO', 'BancoEstado'), ('CHILE', 'Banco de Chile'), ('SANTANDER', 'Santander'), ('BCI', 'BCI'), ('SCOTIABANK', 'Scotiabank'), ('ITAU', 'Itaú'), ('SECURITY', 'Banco Security'), ('FALABELLA', 'Banco Falabella'), ('RIPLEY', 'Banco Ripley'), ('OTRO', 'Otro')], default='ESTADO', help_text='Banco donde se realizó el depósito', max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, help_text='Número del comprobante bancario (opcional)', max_length=50)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre el depósito')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora en que se registró el depósito')),
                ('arqueo', models.ForeignKey(help_text='Arqueo de caja al que pertenece este depósito', on_delete=django.db.models.deletion.CASCADE, related_name='depositos', to='app.arqueocaja')),
                ('registrado_por', models.ForeignKey(help_text='Usuario que registró el depósito', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Depósito Bancario',
                'verbose_name_plural': 'Depósitos Bancarios',
                'db_table': 'deposito_bancario',
                'ordering': ['-fecha_deposito'],
            },
        ),
    ]
