# Generated by Django 5.2 on 2025-11-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_depositobancario'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='cierre_pos_fisico',
            field=models.IntegerField(default=0, help_text='Monto real del cierre de máquina POS'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='diferencia_transbank',
            field=models.IntegerField(default=0, help_text='Diferencia entre cierre POS físico y teórico'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='numero_lote_pos',
            field=models.CharField(blank=True, help_text='Número de lote del cierre POS', max_length=50),
        ),
    ]
