# Generated by Django 5.2 on 2025-11-03 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0037_arqueocaja_cierre_pos_fisico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productos_recepcionados',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Recepción'), ('RECEPCIONADO_OK', 'Recepcionado OK'), ('RECEPCIONADO_PARCIAL', 'Recepcionado Parcial'), ('RECEPCIONADO_DANADO', 'Recepcionado con Daños'), ('FALTANTE', 'Faltante'), ('EN_REGULARIZACION', 'En Regularización'), ('EN_SOLICITUD_REGULARIZACION', 'En Solicitud de Regularización'), ('REGULARIZADO', 'Regularizado')], default='RECEPCIONADO_OK', help_text='Estado de la recepción', max_length=30),
        ),
        migrations.CreateModel(
            name='Solicitud_Regularizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_solicitud', models.CharField(help_text='Número único de la solicitud (ej: SOL-001)', max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora de creación de la solicitud')),
                ('usuario_solicita', models.CharField(help_text='Usuario que crea la solicitud', max_length=100)),
                ('tipo_problema', models.CharField(choices=[('FALTANTE', 'Faltante'), ('DANADO', 'Dañado'), ('PARCIAL', 'Recepción Parcial'), ('INCORRECTO', 'Producto Incorrecto')], help_text='Tipo de problema detectado', max_length=50)),
                ('cantidad_problema', models.IntegerField(help_text='Cantidad de unidades con problema')),
                ('descripcion_problema', models.TextField(help_text='Descripción detallada del problema')),
                ('evidencia_foto', models.FileField(blank=True, help_text='Foto de evidencia (opcional)', null=True, upload_to='evidencias_problemas/')),
                ('tipo_solucion_solicitada', models.CharField(choices=[('NOTA_CREDITO', 'Nota de Crédito'), ('REENVIO', 'Reenvío del mismo producto'), ('CAMBIO_PRODUCTO', 'Cambio por otro producto'), ('AJUSTE_CANTIDAD', 'Ajustar solo cantidad')], help_text='Tipo de solución que solicita el receptor', max_length=50)),
                ('cantidad_cambio_solicitada', models.IntegerField(blank=True, help_text='Cantidad solicitada del producto de cambio', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('EN_REVISION', 'En Revisión por Emisor'), ('APROBADA', 'Aprobada'), ('RECHAZADA', 'Rechazada'), ('EJECUTADA', 'Solución Ejecutada'), ('COMPLETADA', 'Completada y Confirmada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', help_text='Estado actual de la solicitud', max_length=50)),
                ('fecha_revision', models.DateTimeField(blank=True, help_text='Fecha en que el emisor revisó la solicitud', null=True)),
                ('usuario_revisa', models.CharField(blank=True, help_text='Usuario del emisor que revisa', max_length=100, null=True)),
                ('decision_emisor', models.TextField(blank=True, help_text='Observaciones del emisor sobre su decisión', null=True)),
                ('tipo_solucion_aprobada', models.CharField(blank=True, choices=[('NOTA_CREDITO', 'Nota de Crédito'), ('REENVIO', 'Reenvío del mismo producto'), ('CAMBIO_PRODUCTO', 'Cambio por otro producto'), ('AJUSTE_CANTIDAD', 'Ajustar solo cantidad')], help_text='Tipo de solución finalmente aprobada (puede diferir de la solicitada)', max_length=50, null=True)),
                ('cantidad_cambio_aprobada', models.IntegerField(blank=True, help_text='Cantidad finalmente aprobada', null=True)),
                ('fecha_ejecucion', models.DateTimeField(blank=True, help_text='Fecha en que se ejecutó la solución (emisión de documentos)', null=True)),
                ('fecha_confirmacion', models.DateTimeField(blank=True, help_text='Fecha en que el receptor confirmó la solución', null=True)),
                ('usuario_confirma', models.CharField(blank=True, help_text='Usuario que confirmó la recepción de la solución', max_length=100, null=True)),
                ('conformidad', models.BooleanField(blank=True, help_text='Si el receptor quedó conforme con la solución', null=True)),
                ('observaciones_finales', models.TextField(blank=True, help_text='Observaciones finales del receptor', null=True)),
                ('dte_original', models.ForeignKey(help_text='DTE original que tiene el problema', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_regularizacion', to='app.dte')),
                ('dte_solucion', models.ForeignKey(blank=True, help_text='DTE emitido como solución (NC o nuevo DTE con producto de cambio)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='es_solucion_de', to='app.dte')),
                ('nota_credito', models.ForeignKey(blank=True, help_text='Nota de crédito emitida (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_de_solicitud', to='app.dte')),
                ('producto_cambio_aprobado', models.ForeignKey(blank=True, help_text='Producto finalmente aprobado (puede diferir del solicitado)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_aprobadas', to='app.producto_talla')),
                ('producto_cambio_solicitado', models.ForeignKey(blank=True, help_text='Producto que solicita como reemplazo (para CAMBIO_PRODUCTO)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes_como_reemplazo', to='app.producto_talla')),
                ('producto_recepcionado', models.ForeignKey(help_text='Producto recepcionado con problema', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes', to='app.productos_recepcionados')),
                ('sucursal_emisora', models.ForeignKey(help_text='Sucursal que debe APROBAR (emisor del DTE original)', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='app.sucursal')),
                ('sucursal_solicitante', models.ForeignKey(help_text='Sucursal que SOLICITA (receptor del DTE original)', on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='app.sucursal')),
            ],
            options={
                'verbose_name': 'Solicitud de Regularización',
                'verbose_name_plural': 'Solicitudes de Regularización',
                'db_table': 'solicitudes_regularizacion',
                'ordering': ['-fecha_solicitud'],
                'indexes': [models.Index(fields=['sucursal_emisora', 'estado'], name='solicitudes_sucursa_94a4ae_idx'), models.Index(fields=['sucursal_solicitante', 'estado'], name='solicitudes_sucursa_07fbe4_idx'), models.Index(fields=['estado'], name='solicitudes_estado_30a400_idx'), models.Index(fields=['fecha_solicitud'], name='solicitudes_fecha_s_d9901c_idx'), models.Index(fields=['numero_solicitud'], name='solicitudes_numero__0b270d_idx')],
            },
        ),
    ]
