# Generated by Django 5.2 on 2025-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_agregar_modelo_solicitud_regularizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='total_credito_trabajador_teorico',
            field=models.IntegerField(default=0),
        ),
    ]
