# Generated by Django 5.2 on 2025-11-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_add_notas_to_dte_detalle_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagocambiodevolucion',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CREDITO_EXTERNO', 'Crédito Externo'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pagocreditotrabajador',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CREDITO_EXTERNO', 'Crédito Externo'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], default='EFECTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CREDITO_EXTERNO', 'Crédito Externo'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], default='EFECTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketdetallepago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CREDITO_EXTERNO', 'Crédito Externo'), ('CONVENIO', 'Convenio'), ('MULTIPLE', 'Pagos Combinados')], max_length=50),
        ),
    ]
