# Generated by Django 5.2 on 2025-11-05 14:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_alter_pagocambiodevolucion_metodo_pago_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CambioPrecioPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.IntegerField(help_text='Precio antes del cambio')),
                ('precio_nuevo', models.IntegerField(help_text='Precio propuesto')),
                ('diferencia', models.IntegerField(help_text='Diferencia en pesos (nuevo - anterior)')),
                ('porcentaje_cambio', models.DecimalField(decimal_places=2, help_text='Porcentaje de cambio', max_digits=10)),
                ('tipo_cambio', models.CharField(choices=[('INDIVIDUAL', 'Cambio Individual'), ('MASIVO', 'Cambio Masivo'), ('SINCRONIZACION', 'Sincronización Multi-Sucursal'), ('RECOMENDACION', 'Por Recomendación del Sistema')], default='INDIVIDUAL', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Revisión'), ('REVISADO', 'Revisado'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('APLICADO', 'Aplicado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('motivo', models.TextField(blank=True, help_text='Motivo del cambio de precio', null=True)),
                ('recomendacion_sistema', models.JSONField(blank=True, help_text='Datos de la recomendación del sistema (si aplica)', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_revision', models.DateTimeField(blank=True, help_text='Fecha en que fue revisado', null=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, help_text='Fecha en que fue aprobado/rechazado', null=True)),
                ('fecha_aplicacion', models.DateTimeField(blank=True, help_text='Fecha en que se aplicó el cambio', null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, help_text='Fecha límite para aprobar/aplicar', null=True)),
                ('observaciones_revision', models.TextField(blank=True, help_text='Observaciones al revisar', null=True)),
                ('observaciones_aprobacion', models.TextField(blank=True, help_text='Observaciones al aprobar/rechazar', null=True)),
                ('notificado', models.BooleanField(default=False, help_text='Si se notificó a la sucursal')),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('aprobado_por', models.ForeignKey(blank=True, help_text='Usuario que aprobó/rechazó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_precio_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(help_text='Usuario que propuso el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_precio_creados', to=settings.AUTH_USER_MODEL)),
                ('producto_talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cambios_precio_pendientes', to='app.producto_talla')),
                ('revisado_por', models.ForeignKey(blank=True, help_text='Usuario que revisó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_precio_revisados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(help_text='Sucursal afectada por el cambio', on_delete=django.db.models.deletion.CASCADE, related_name='cambios_precio_pendientes', to='app.sucursal')),
            ],
            options={
                'verbose_name': 'Cambio de Precio Pendiente',
                'verbose_name_plural': 'Cambios de Precios Pendientes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionCambioPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVA', 'Nuevo Cambio Propuesto'), ('REVISION', 'Cambio Revisado'), ('APROBACION', 'Cambio Aprobado'), ('RECHAZO', 'Cambio Rechazado'), ('APLICACION', 'Cambio Aplicado'), ('VENCIMIENTO', 'Cambio Próximo a Vencer')], max_length=20)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('cambio_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app.cambiopreciopendiente')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_precio', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de Cambio de Precio',
                'verbose_name_plural': 'Notificaciones de Cambios de Precios',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddIndex(
            model_name='cambiopreciopendiente',
            index=models.Index(fields=['estado', 'sucursal'], name='app_cambiop_estado_a08259_idx'),
        ),
        migrations.AddIndex(
            model_name='cambiopreciopendiente',
            index=models.Index(fields=['fecha_creacion'], name='app_cambiop_fecha_c_1256a3_idx'),
        ),
    ]
