# Generated by Django 5.2 on 2025-11-05 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_cambiopreciopendiente_notificacioncambioprecio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialCambioPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_anterior', models.IntegerField(help_text='Precio antes del cambio')),
                ('precio_nuevo', models.IntegerField(help_text='Precio después del cambio')),
                ('diferencia', models.IntegerField(help_text='Diferencia en pesos')),
                ('porcentaje_cambio', models.DecimalField(decimal_places=2, help_text='Porcentaje de cambio', max_digits=10)),
                ('motivo', models.TextField(blank=True, help_text='Motivo del cambio', null=True)),
                ('tipo_cambio', models.CharField(choices=[('MANUAL', 'Cambio Manual'), ('RECOMENDACION', 'Por Recomendación'), ('MASIVO', 'Cambio Masivo'), ('SINCRONIZACION', 'Sincronización'), ('APROBACION', 'Por Aprobación')], default='MANUAL', max_length=50)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP desde donde se realizó el cambio', null=True)),
                ('tallas_afectadas', models.IntegerField(default=0, help_text='Cantidad de tallas actualizadas')),
                ('lotes_afectados', models.IntegerField(default=0, help_text='Cantidad de lotes actualizados')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_precios', to='app.producto')),
                ('usuario', models.ForeignKey(help_text='Usuario que realizó el cambio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_precio_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Cambio de Precio',
                'verbose_name_plural': 'Historial de Cambios de Precios',
                'ordering': ['-fecha_cambio'],
                'indexes': [models.Index(fields=['producto', '-fecha_cambio'], name='app_histori_product_f2da09_idx'), models.Index(fields=['usuario', '-fecha_cambio'], name='app_histori_usuario_c21b2f_idx')],
            },
        ),
    ]
