# Generated by Django 5.2 on 2025-11-11 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0044_historialcambioprecio'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='acteco',
            field=models.CharField(blank=True, help_text='Código de actividad económica del SII', max_length=20, null=True, verbose_name='Código Acteco'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto1',
            field=models.CharField(blank=True, help_text='Teléfono o email de contacto principal', max_length=100, null=True, verbose_name='Contacto 1'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='contacto2',
            field=models.CharField(blank=True, help_text='Teléfono o email de contacto secundario', max_length=100, null=True, verbose_name='Contacto 2'),
        ),
        migrations.AlterField(
            model_name='dte',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA ELECTRONICA', 'Factura Electrónica'), ('BOLETA ELECTRONICA', 'Boleta Electrónica'), ('GUIA', 'Guía de Despacho'), ('NOTA DE PEDIDO', 'Nota de Pedido'), ('NOTA DE CREDITO', 'Nota de Crédito'), ('NOTA DE DEBITO', 'Nota de Débito'), ('FACTURA EXENTA', 'Factura Exenta'), ('COTIZACION', 'Cotización'), ('COMPRA', 'Compra'), ('TICKET', 'Ticket'), ('TRASPASO', 'Traspaso'), ('AJUSTE', 'Ajuste de Inventario')], max_length=20),
        ),
        migrations.AlterField(
            model_name='producto_talla',
            name='sku',
            field=models.BigIntegerField(),
        ),
    ]
