# Generated by Django 5.2 on 2025-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0045_empresa_acteco_empresa_contacto1_empresa_contacto2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dte_fecha_generacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha Generación DTE'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dte_generado',
            field=models.BooleanField(default=False, verbose_name='DTE Generado'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dte_pdf_url',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='URL PDF'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dte_xml_path',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Ruta XML'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='folio_dte',
            field=models.IntegerField(blank=True, help_text='Folio del documento electrónico generado', null=True, verbose_name='Folio DTE'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='referencia_fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Referencia'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='referencia_folio',
            field=models.CharField(blank=True, help_text='Número de la OC, Guía, etc.', max_length=50, null=True, verbose_name='Folio Referencia'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='referencia_tipo',
            field=models.CharField(blank=True, help_text='801=OC, 52=Guía, 803=Contrato', max_length=10, null=True, verbose_name='Tipo Referencia'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tipo_dte',
            field=models.CharField(blank=True, choices=[('TICKET', 'Ticket (sin DTE)'), ('BOLETA', 'Boleta Manual'), ('BOLETA_ELECTRONICA', 'Boleta Electrónica - 39'), ('FACTURA_ELECTRONICA', 'Factura Electrónica - 33'), ('FACTURA_EXENTA', 'Factura Exenta - 34')], default='TICKET', max_length=20, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
