# Generated by Django 5.2 on 2025-11-12 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0046_ticket_dte_fecha_generacion_ticket_dte_generado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dte',
            name='motivo_rechazo',
            field=models.CharField(blank=True, help_text='Motivo del rechazo del DTE (máximo 100 caracteres)', max_length=100, null=True),
        ),
    ]
