# Generated by Django 5.2 on 2025-11-12 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_dte_motivo_rechazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dte_Incidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('FACTURACION', 'Error de Facturación'), ('MERCADERIA', 'Mercadería Faltante/Incompleta'), ('CALIDAD', 'Productos Dañados/Defectuosos'), ('DESCUENTOS', 'Descuentos Incorrectos'), ('DESCRIPCION', 'Error en Descripción'), ('OTRO', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(help_text='Detalle del problema')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_GESTION', 'En Gestión'), ('RESUELTO', 'Resuelto')], default='PENDIENTE', max_length=15)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True, help_text='Cómo se resolvió la incidencia', null=True)),
                ('dte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidencias', to='app.dte')),
            ],
            options={
                'verbose_name': 'Incidencia DTE',
                'verbose_name_plural': 'Incidencias DTE',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
