# Generated by Django 5.2 on 2025-11-12 20:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_dte_incidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dte',
            name='documento_padre',
            field=models.ForeignKey(blank=True, help_text='Documento previo (cotización/guía) al que regulariza esta factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_hijos', to='app.dte'),
        ),
    ]
