# Generated by Django 5.2 on 2025-11-13 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_dte_documento_padre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cambiodevolucion',
            name='fecha_ejecucion',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se ejecutó el cambio (movimientos de inventario)', null=True),
        ),
        migrations.AddField(
            model_name='cambiodevolucion',
            name='fecha_pago_diferencia',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se cobró la diferencia', null=True),
        ),
        migrations.AddField(
            model_name='cambiodevolucion',
            name='ticket_diferencia',
            field=models.ForeignKey(blank=True, help_text='Ticket de diferencia de precio (cuando cliente debe pagar más)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_diferencia', to='app.ticket'),
        ),
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('APROBADO', 'Aprobado'), ('EJECUTADO', 'Ejecutado'), ('EJECUTADO_COBRO_PENDIENTE', 'Ejecutado - Cobro Pendiente'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado')], default='SOLICITADO', max_length=30),
        ),
    ]
