# Generated by Django 5.2 on 2025-11-14 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_aumentar_max_length_estado_cambio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vendedor',
            options={'verbose_name': 'Vendedor', 'verbose_name_plural': 'Vendedores'},
        ),
        migrations.AddField(
            model_name='vendedor',
            name='sucursales',
            field=models.ManyToManyField(blank=True, related_name='vendedores', to='app.sucursal', verbose_name='Sucursales asignadas'),
        ),
    ]
