# Generated by Django 5.2 on 2025-11-14 21:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0051_alter_vendedor_options_vendedor_sucursales'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dte',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA ELECTRONICA', 'Factura Electrónica'), ('BOLETA ELECTRONICA', 'Boleta Electrónica'), ('BOLETA PAPEL', 'Boleta Papel'), ('GUIA', 'Guía de Despacho'), ('NOTA DE PEDIDO', 'Nota de Pedido'), ('NOTA DE CREDITO', 'Nota de Crédito'), ('NOTA DE DEBITO', 'Nota de Débito'), ('FACTURA EXENTA', 'Factura Exenta'), ('COTIZACION', 'Cotización'), ('COMPRA', 'Compra'), ('TICKET', 'Ticket'), ('TRASPASO', 'Traspaso'), ('AJUSTE', 'Ajuste de Inventario')], max_length=20),
        ),
        migrations.CreateModel(
            name='Requerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_requerimiento', models.CharField(help_text='Número único de requerimiento (autogenerado)', max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('GARANTIA', 'Garantía'), ('DEVOLUCION', 'Devolución'), ('CAMBIO', 'Cambio de Producto'), ('RECLAMO', 'Reclamo'), ('CONSULTA', 'Consulta Técnica')], default='GARANTIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revisión'), ('ESPERANDO_PROVEEDOR', 'Esperando Respuesta Proveedor'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('EN_PROCESO', 'En Proceso'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=30)),
                ('sku', models.CharField(help_text='SKU del producto', max_length=100)),
                ('nombre_producto', models.CharField(help_text='Nombre del producto', max_length=255)),
                ('numero_boleta', models.CharField(blank=True, help_text='Número de boleta o documento de venta', max_length=100, null=True)),
                ('tipo_documento', models.CharField(blank=True, help_text='Tipo de documento (Boleta, Factura, etc.)', max_length=50, null=True)),
                ('fecha_compra', models.DateField(blank=True, help_text='Fecha de compra del producto', null=True)),
                ('cliente_rut', models.CharField(blank=True, help_text='RUT del cliente', max_length=20, null=True)),
                ('cliente_nombre', models.CharField(help_text='Nombre completo del cliente', max_length=255)),
                ('cliente_telefono', models.CharField(blank=True, help_text='Teléfono de contacto', max_length=20, null=True)),
                ('cliente_email', models.EmailField(blank=True, help_text='Email del cliente', max_length=254, null=True)),
                ('motivo', models.TextField(help_text='Descripción del motivo del requerimiento')),
                ('descripcion_problema', models.TextField(blank=True, help_text='Descripción detallada del problema', null=True)),
                ('correo_enviado_proveedor', models.BooleanField(default=False, help_text='Indica si se envió correo al proveedor')),
                ('fecha_envio_proveedor', models.DateTimeField(blank=True, help_text='Fecha en que se envió al proveedor', null=True)),
                ('respuesta_proveedor', models.TextField(blank=True, help_text='Respuesta del proveedor', null=True)),
                ('fecha_respuesta_proveedor', models.DateTimeField(blank=True, help_text='Fecha de respuesta del proveedor', null=True)),
                ('resolucion', models.TextField(blank=True, help_text='Descripción de la resolución final', null=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, help_text='Fecha de resolución del requerimiento', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('prioridad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=10)),
                ('producto_talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos', to='app.producto_talla')),
                ('proveedor', models.ForeignKey(blank=True, help_text='Proveedor al que se envía el requerimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_como_proveedor', to='app.empresa')),
                ('sucursal', models.ForeignKey(help_text='Sucursal que genera el requerimiento', on_delete=django.db.models.deletion.CASCADE, related_name='requerimientos', to='app.sucursal')),
                ('usuario_creador', models.ForeignKey(help_text='Usuario que creó el requerimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_creados', to=settings.AUTH_USER_MODEL)),
                ('usuario_gestor', models.ForeignKey(blank=True, help_text='Usuario que gestiona/administra el requerimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_gestionados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Requerimiento',
                'verbose_name_plural': 'Requerimientos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='HistorialRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(help_text='Tipo de acción realizada', max_length=100)),
                ('estado_anterior', models.CharField(blank=True, help_text='Estado anterior del requerimiento', max_length=30, null=True)),
                ('estado_nuevo', models.CharField(blank=True, help_text='Nuevo estado del requerimiento', max_length=30, null=True)),
                ('comentario', models.TextField(blank=True, help_text='Comentario o descripción de la acción', null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_requerimientos', to=settings.AUTH_USER_MODEL)),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app.requerimiento')),
            ],
            options={
                'verbose_name': 'Historial de Requerimiento',
                'verbose_name_plural': 'Historial de Requerimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='FotoRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Foto del producto o problema', upload_to='requerimientos/fotos/%Y/%m/%d/')),
                ('descripcion', models.CharField(blank=True, help_text='Descripción de la foto', max_length=255, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de la foto (1-5)')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos_requerimientos', to=settings.AUTH_USER_MODEL)),
                ('requerimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='app.requerimiento')),
            ],
            options={
                'verbose_name': 'Foto de Requerimiento',
                'verbose_name_plural': 'Fotos de Requerimientos',
                'ordering': ['orden', 'fecha_subida'],
            },
        ),
        migrations.AddIndex(
            model_name='requerimiento',
            index=models.Index(fields=['numero_requerimiento'], name='app_requeri_numero__c5be81_idx'),
        ),
        migrations.AddIndex(
            model_name='requerimiento',
            index=models.Index(fields=['estado', '-fecha_creacion'], name='app_requeri_estado_e7c35a_idx'),
        ),
        migrations.AddIndex(
            model_name='requerimiento',
            index=models.Index(fields=['sucursal', '-fecha_creacion'], name='app_requeri_sucursa_2711c3_idx'),
        ),
        migrations.AddIndex(
            model_name='requerimiento',
            index=models.Index(fields=['sku'], name='app_requeri_sku_73d91a_idx'),
        ),
    ]
