# Generated by Django 5.2 on 2025-11-17 18:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_alter_dte_tipo_documento_requerimiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='asignado_a',
            field=models.ForeignKey(blank=True, help_text='Usuario responsable de gestionar el requerimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='correo_proveedor_destino',
            field=models.CharField(blank=True, help_text='Email al que se envió el requerimiento', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='decision_proveedor',
            field=models.CharField(blank=True, choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PARCIAL', 'Aprobado Parcial')], help_text='Decisión del proveedor', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='intentos_envio',
            field=models.IntegerField(default=0, help_text='Número de veces que se ha enviado al proveedor'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='ultimo_recordatorio',
            field=models.DateTimeField(blank=True, help_text='Fecha del último recordatorio enviado', null=True),
        ),
    ]
