# Generated by Django 5.2 on 2025-11-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0053_requerimiento_asignado_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='motivo_resolucion',
            field=models.TextField(blank=True, help_text='Motivo visible al usuario de por qué se aprobó o rechazó', null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ESPERANDO_RESPUESTA', 'Esperando Respuesta Proveedor'), ('APROBADO', 'Aprobado por Proveedor'), ('RECHAZADO', 'Rechazado por Proveedor'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=30),
        ),
    ]
