# Generated by Django 5.2 on 2025-11-18 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0054_agregar_motivo_resolucion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo_dte',
            field=models.CharField(blank=True, choices=[('TICKET', 'Ticket (sin DTE)'), ('BOLETA', 'Boleta Manual'), ('BOLETA_ELECTRONICA', 'Boleta Electrónica - 39'), ('FACTURA_ELECTRONICA', 'Factura Electrónica - 33'), ('FACTURA_EXENTA', 'Factura Exenta - 34')], default='TICKET', max_length=30, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
