# Generated by Django 5.2 on 2025-11-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0055_increase_tipo_dte_max_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='tipo_dte',
            field=models.CharField(blank=True, choices=[('TICKET', 'Ticket (sin DTE)'), ('BOLETA', 'Boleta Manual'), ('BOLETA_ELECTRONICA', 'Boleta Electrónica - 39'), ('FACTURA_ELECTRONICA', 'Factura Electrónica - 33'), ('FACTURA_EXENTA', 'Factura Exenta - 34'), ('TICKET_COBRO_CAMBIO', 'Ticket Cobro Cambio'), ('TICKET_DEVOLUCION', 'Ticket Devolución'), ('TICKET_CAMBIO_DIRECTO', 'Ticket Cambio Directo')], default='TICKET', max_length=30, null=True, verbose_name='Tipo de Documento'),
        ),
    ]
