# Generated by Django 5.2 on 2025-11-18 19:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0056_add_tipo_dte_cambio_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuloSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único del módulo (ej: dashboard, ventas, compras)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre descriptivo del módulo', max_length=100)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del módulo', null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del ícono (ej: ri-dashboard-line)', max_length=50, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización en el menú')),
                ('activo', models.BooleanField(default=True, help_text='Si el módulo está activo en el sistema')),
            ],
            options={
                'verbose_name': 'Módulo del Sistema',
                'verbose_name_plural': 'Módulos del Sistema',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionPermisoGlobal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(help_text='Clave de configuración', max_length=100, unique=True)),
                ('valor', models.TextField(help_text='Valor de la configuración')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la configuración', null=True)),
                ('tipo_dato', models.CharField(choices=[('string', 'Texto'), ('integer', 'Número Entero'), ('float', 'Número Decimal'), ('boolean', 'Booleano'), ('json', 'JSON')], default='string', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario_modificacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='configs_modificadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración Global de Permisos',
                'verbose_name_plural': 'Configuraciones Globales de Permisos',
            },
        ),
        migrations.CreateModel(
            name='OpcionMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código único de la opción (ej: dashboard_ventas, pos_dashboard)', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la opción en el menú', max_length=100)),
                ('url_name', models.CharField(blank=True, help_text='Nombre de la URL en Django (para reverse)', max_length=100, null=True)),
                ('url_path', models.CharField(blank=True, help_text='Path directo de la URL (ej: /app/pos-dashboard/)', max_length=200, null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del ícono', max_length=50, null=True)),
                ('orden', models.IntegerField(default=0, help_text='Orden dentro del módulo')),
                ('es_submenu', models.BooleanField(default=False, help_text='Si es un submenú con opciones hijas')),
                ('activo', models.BooleanField(default=True, help_text='Si la opción está activa')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='app.modulosistema')),
                ('padre', models.ForeignKey(blank=True, help_text='Opción padre si es submenú', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='app.opcionmenu')),
            ],
            options={
                'verbose_name': 'Opción de Menú',
                'verbose_name_plural': 'Opciones de Menú',
                'ordering': ['modulo', 'orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='PermisoRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('administrador', 'Administrador'), ('jefe_local', 'Jefe Local'), ('cajero', 'Cajero'), ('vendedor', 'Vendedor')], help_text='Rol de usuario', max_length=50)),
                ('puede_ver', models.BooleanField(default=True, help_text='Puede ver la opción en el menú')),
                ('puede_crear', models.BooleanField(default=False, help_text='Puede crear nuevos registros')),
                ('puede_editar', models.BooleanField(default=False, help_text='Puede editar registros existentes')),
                ('puede_eliminar', models.BooleanField(default=False, help_text='Puede eliminar registros')),
                ('puede_exportar', models.BooleanField(default=False, help_text='Puede exportar datos')),
                ('puede_aprobar', models.BooleanField(default=False, help_text='Puede aprobar operaciones (cambios de precio, devoluciones, etc.)')),
                ('opcion_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='app.opcionmenu')),
            ],
            options={
                'verbose_name': 'Permiso por Rol',
                'verbose_name_plural': 'Permisos por Rol',
                'unique_together': {('rol', 'opcion_menu')},
            },
        ),
    ]
