# Generated by Django 5.2 on 2025-11-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0059_agregar_limite_descuento_rol'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketdetallepago',
            name='numero_orden_compra',
            field=models.CharField(blank=True, help_text='Número de orden de compra del cliente', max_length=100, null=True),
        ),
    ]
