# Generated by Django 5.2 on 2025-11-18 21:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0060_add_numero_orden_compra_to_ticket_pago'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodigoAutorizacionDinamico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=6, unique=True, verbose_name='Código de 6 dígitos')),
                ('fecha_hora_inicio', models.DateTimeField(verbose_name='Fecha y hora de inicio de validez')),
                ('fecha_hora_fin', models.DateTimeField(verbose_name='Fecha y hora de fin de validez')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False, verbose_name='¿Código usado?')),
                ('activo', models.BooleanField(default=True, verbose_name='¿Código activo?')),
            ],
            options={
                'verbose_name': 'Código de Autorización Dinámico',
                'verbose_name_plural': 'Códigos de Autorización Dinámicos',
                'ordering': ['-fecha_hora_inicio'],
                'indexes': [models.Index(fields=['codigo', 'activo'], name='app_codigoa_codigo_a1a19a_idx'), models.Index(fields=['fecha_hora_inicio', 'fecha_hora_fin'], name='app_codigoa_fecha_h_cb5286_idx')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAutorizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('APROBACION_CAMBIO', 'Aprobación de Cambio/Devolución'), ('DESCUENTO_ESPECIAL', 'Descuento Especial'), ('ANULACION_VENTA', 'Anulación de Venta'), ('AJUSTE_PRECIO', 'Ajuste de Precio'), ('OTRO', 'Otro')], max_length=50, verbose_name='Tipo de operación')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción de la operación')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y hora de la autorización')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('datos_adicionales', models.JSONField(blank=True, default=dict, verbose_name='Datos adicionales')),
                ('exitoso', models.BooleanField(default=True, verbose_name='¿Autorización exitosa?')),
                ('cambio_devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones', to='app.cambiodevolucion')),
                ('codigo_usado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.codigoautorizaciondinamico', verbose_name='Código usado')),
                ('usuario_solicitante', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autorizaciones_solicitadas', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que solicitó la autorización')),
            ],
            options={
                'verbose_name': 'Registro de Autorización',
                'verbose_name_plural': 'Registros de Autorizaciones',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='app_registr_fecha_h_e04ee6_idx'), models.Index(fields=['usuario_solicitante', '-fecha_hora'], name='app_registr_usuario_e3ee7e_idx'), models.Index(fields=['tipo_operacion', '-fecha_hora'], name='app_registr_tipo_op_90d4ed_idx')],
            },
        ),
    ]
