# Generated by Django 5.2 on 2025-12-30 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0062_add_tipo_sucursal_y_sobreprecio_traspaso'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sucursal',
            options={'ordering': ['alias'], 'verbose_name': 'Sucursal', 'verbose_name_plural': 'Sucursales'},
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales_app', to='app.empresa'),
        ),
    ]
