# Generated by Django 5.2 on 2026-01-02 20:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0063_alter_sucursal_options_alter_sucursal_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionDTE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DTE_RECIBIDO', 'Nuevo DTE Recibido'), ('ACTUALIZACION_PENDIENTE', 'Actualización de Stock Pendiente'), ('RECEPCION_COMPLETADA', 'Recepción Completada'), ('REGULARIZACION_REQUERIDA', 'Regularización Requerida'), ('VENCIMIENTO_PROXIMO', 'Vencimiento Próximo')], default='DTE_RECIBIDO', max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('procesada', models.BooleanField(default=False, help_text='Indica si el DTE ya fue procesado/recepcionado')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_lectura', models.DateTimeField(blank=True, null=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('dte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app.dte')),
                ('empresa_receptora', models.ForeignKey(help_text='Empresa que recibe la notificación (receptor del DTE)', on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_dte_recibidas', to='app.empresa')),
                ('usuario_que_proceso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dtes_procesados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación de DTE',
                'verbose_name_plural': 'Notificaciones de DTEs',
                'ordering': ['-fecha_creacion'],
                'indexes': [models.Index(fields=['empresa_receptora', 'leida'], name='app_notific_empresa_575f2c_idx'), models.Index(fields=['empresa_receptora', 'procesada'], name='app_notific_empresa_441467_idx'), models.Index(fields=['-fecha_creacion'], name='app_notific_fecha_c_27780d_idx')],
            },
        ),
    ]
