# Generated by Django 5.2 on 2026-01-02 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0064_add_notificacion_dte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='notificaciondte',
            name='detalle_problemas',
            field=models.TextField(blank=True, help_text='Detalle de los problemas reportados', null=True),
        ),
        migrations.AddField(
            model_name='notificaciondte',
            name='productos_problemas',
            field=models.IntegerField(default=0, help_text='Número de productos con problemas'),
        ),
        migrations.AddField(
            model_name='notificaciondte',
            name='sucursal',
            field=models.ForeignKey(blank=True, help_text='Sucursal específica que debe ver esta notificación', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_dte', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='notificaciondte',
            name='sucursal_reportante',
            field=models.ForeignKey(blank=True, help_text='Sucursal que reporta el problema', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notificaciones_enviadas', to='app.sucursal'),
        ),
        migrations.AddIndex(
            model_name='notificaciondte',
            index=models.Index(fields=['sucursal', 'leida'], name='app_notific_sucursa_363462_idx'),
        ),
    ]
