# Generated by Django 5.2 on 2026-01-05 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0065_add_notificacion_dte_sucursal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagocreditotrabajador',
            name='sucursal_cobro',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde se registró el cobro', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_credito_cobrados', to='app.sucursal'),
        ),
    ]
