# Generated by Django 5.2 on 2026-01-05 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0066_add_sucursal_cobro_to_pago_credito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cotizacion_Empresa_Detalle_SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=1, help_text='Cantidad de este SKU asignada al item')),
                ('costo_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Costo unitario al momento de la cotización', max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Precio de venta unitario', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus_asociados', to='app.cotizacion_empresa_detalle')),
                ('producto_talla', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones_detalle_skus', to='app.producto_talla')),
            ],
            options={
                'verbose_name': 'SKU de Detalle de Cotización',
                'verbose_name_plural': 'SKUs de Detalles de Cotización',
                'ordering': ['detalle', 'id'],
            },
        ),
    ]
