# Generated by Django 5.2 on 2026-01-06 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0069_ticket_created_offline_ticket_device_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='cierre_credito_fisico',
            field=models.IntegerField(default=0, help_text='Monto real cierre crédito Transbank'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cierre_debito_fisico',
            field=models.IntegerField(default=0, help_text='Monto real cierre débito Transbank'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='diferencia_credito',
            field=models.IntegerField(default=0, help_text='Diferencia crédito: físico - teórico'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='diferencia_debito',
            field=models.IntegerField(default=0, help_text='Diferencia débito: físico - teórico'),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='cierre_pos_fisico',
            field=models.IntegerField(default=0, help_text='Monto real del cierre de máquina POS (total)'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='modulo_origen',
            field=models.CharField(choices=[('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('POS', 'Punto de Venta'), ('CAMBIO_DEVOLUCION', 'Cambio/Devolución')], default='VENTA_PUBLICO', max_length=30),
        ),
    ]
