# Generated by Django 5.2 on 2026-01-06 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0070_agregar_campos_transbank_arqueo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permisorol',
            name='rol',
            field=models.CharField(choices=[('administrador', 'Administrador'), ('administracion', 'Administración'), ('jefe_local', 'Jefe Local'), ('cajero', 'Cajero'), ('vendedor', 'Vendedor')], help_text='Rol de usuario', max_length=50),
        ),
    ]
