# Generated by Django 5.2 on 2026-01-06 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0071_alter_permisorol_rol'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='depositobancario',
            name='fecha_verificacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='imagen_comprobante',
            field=models.ImageField(blank=True, help_text='Foto o imagen del comprobante bancario', null=True, upload_to='comprobantes_bancarios/'),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='verificado',
            field=models.BooleanField(default=False, help_text='Si el depósito fue verificado por un supervisor'),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='verificado_por',
            field=models.ForeignKey(blank=True, help_text='Supervisor que verificó el depósito', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos_verificados', to=settings.AUTH_USER_MODEL),
        ),
    ]
