# Generated by Django 5.2 on 2026-01-08 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0073_add_toma_inventario_models'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tomainventariodetalle',
            name='unique_inventario_producto',
        ),
        migrations.RenameIndex(
            model_name='tomainventario',
            new_name='app_tomainv_sucursa_a59eac_idx',
            old_name='app_tomai_sucursa_idx',
        ),
        migrations.RenameIndex(
            model_name='tomainventario',
            new_name='app_tomainv_fecha_c_77b7ff_idx',
            old_name='app_tomai_fecha_c_idx',
        ),
        migrations.RenameIndex(
            model_name='tomainventario',
            new_name='app_tomainv_numero__c05044_idx',
            old_name='app_tomai_numero_idx',
        ),
        migrations.RenameIndex(
            model_name='tomainventario',
            new_name='app_tomainv_created_b94da4_idx',
            old_name='app_tomai_created_idx',
        ),
        migrations.RenameIndex(
            model_name='tomainventariodetalle',
            new_name='app_tomainv_toma_in_791e7d_idx',
            old_name='app_tomai_det_contado_idx',
        ),
        migrations.RenameIndex(
            model_name='tomainventariodetalle',
            new_name='app_tomainv_toma_in_15c77d_idx',
            old_name='app_tomai_det_dif_idx',
        ),
        migrations.RenameIndex(
            model_name='tomainventariodetalle',
            new_name='app_tomainv_sku_36dcfa_idx',
            old_name='app_tomai_det_sku_idx',
        ),
        migrations.AlterUniqueTogether(
            name='tomainventariodetalle',
            unique_together={('toma_inventario', 'producto_talla')},
        ),
    ]
