# Generated by Django 5.2 on 2026-01-08 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0074_remove_tomainventariodetalle_unique_inventario_producto_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialImpresionEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_origen', models.CharField(choices=[('DTE_COMPRA', 'DTE Compra'), ('DTE_TRASPASO', 'DTE Traspaso'), ('TRASPASO_INTERNO', 'Traspaso Interno'), ('MANUAL', 'Impresión Manual')], max_length=20)),
                ('documento_id', models.IntegerField(blank=True, help_text='ID del documento origen', null=True)),
                ('numero_documento', models.CharField(blank=True, help_text='Número visible del documento', max_length=50)),
                ('fecha_impresion', models.DateTimeField(auto_now_add=True)),
                ('total_productos', models.IntegerField(default=0)),
                ('total_etiquetas', models.IntegerField(default=0)),
                ('completado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.sucursal')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Impresión',
                'verbose_name_plural': 'Historial de Impresiones',
                'ordering': ['-fecha_impresion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleImpresionEtiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=50)),
                ('articulo', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('marca', models.CharField(blank=True, max_length=50)),
                ('talla', models.CharField(blank=True, max_length=20)),
                ('color', models.CharField(blank=True, max_length=50)),
                ('precio_impreso', models.IntegerField(default=0, help_text='Precio que se imprimió en la etiqueta')),
                ('cantidad_etiquetas', models.IntegerField(default=1)),
                ('producto_talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.producto_talla')),
                ('historial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.historialimpresionetiqueta')),
            ],
            options={
                'verbose_name': 'Detalle de Impresión',
                'verbose_name_plural': 'Detalles de Impresión',
            },
        ),
    ]
