# Generated by Django 5.2 on 2026-01-20 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0078_add_dte_alerta_descartada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requerimiento',
            name='tipo',
            field=models.CharField(choices=[('GARANTIA', 'Garantia Producto'), ('DEVOLUCION', 'Procedimiento Devolucion Proveedor'), ('RECLAMO', 'Reclamo'), ('CONSULTA', 'Consulta Tecnica'), ('OTROS', 'Otros')], default='GARANTIA', max_length=20),
        ),
    ]
