# Generated by Django 5.2 on 2026-01-20 21:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0079_alter_requerimiento_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiodevoluciondetalle',
            name='producto_original',
            field=models.ForeignKey(
                blank=True,
                help_text='Producto del ticket original que se cambia/devuelve (NULL para productos adicionales)',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='cambios_como_original',
                to='app.ticket_productos'
            ),
        ),
        migrations.AlterField(
            model_name='cambiodevoluciondetalle',
            name='cantidad_original',
            field=models.IntegerField(
                default=0,
                help_text='Cantidad del producto original a cambiar/devolver (0 para productos adicionales)'
            ),
        ),
        migrations.AlterField(
            model_name='cambiodevoluciondetalle',
            name='precio_original_unitario',
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text='Precio unitario original (0 para productos adicionales)',
                max_digits=10
            ),
        ),
    ]
