# Generated by Django 5.2 on 2026-01-22 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0082_add_dte_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos_producto',
            name='concepto',
            field=models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('INGRESO_MANUAL', 'Ingreso Manual'), ('RECEPCION_COMPRA', 'Recepción de Compra'), ('REPOSICION_STOCK', 'Reposición de Stock'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('TRASPASO_ENTRADA', 'Traspaso Entrada'), ('REGULARIZACION_TRASPASO', 'Regularización de Traspaso'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('DONACION_RECIBIDA', 'Donación Recibida'), ('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('TRASPASO_SALIDA', 'Traspaso Salida'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('PERDIDA_ROBO', 'Pérdida por Robo'), ('PERDIDA_DETERIORO', 'Pérdida por Deterioro'), ('DONACION_ENTREGADA', 'Donación Entregada'), ('DEVOLUCION_PROVEEDOR', 'Devolución a Proveedor'), ('TRASPASO_SUCURSAL', 'Traspaso entre Sucursales'), ('TRASPASO_BODEGA', 'Traspaso a Bodega'), ('TRASPASO_VITRINA', 'Traspaso a Vitrina'), ('CAMBIO_PRODUCTO_SALIDA', 'Cambio de Producto (Salida)'), ('CAMBIO_PRODUCTO_ENTRADA', 'Cambio de Producto (Entrada)'), ('CORRECCION_STOCK', 'Corrección de Stock'), ('ANULACION_REGULARIZACION', 'Anulación de Regularización')], default='INGRESO_INICIAL', max_length=50),
        ),
        migrations.CreateModel(
            name='PermisoSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilitado', models.BooleanField(default=True, help_text='Si esta opción está habilitada para la sucursal')),
                ('puede_crear', models.BooleanField(default=True, help_text='Puede crear nuevos registros desde esta sucursal')),
                ('puede_editar', models.BooleanField(default=True, help_text='Puede editar registros desde esta sucursal')),
                ('puede_eliminar', models.BooleanField(default=False, help_text='Puede eliminar registros desde esta sucursal')),
                ('puede_exportar', models.BooleanField(default=True, help_text='Puede exportar datos desde esta sucursal')),
                ('puede_aprobar', models.BooleanField(default=False, help_text='Puede aprobar operaciones desde esta sucursal')),
                ('notas', models.TextField(blank=True, help_text='Notas sobre por qué esta restricción está aplicada', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('opcion_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_sucursal', to='app.opcionmenu')),
                ('sucursal', models.ForeignKey(help_text='Sucursal a la que aplica este permiso', on_delete=django.db.models.deletion.CASCADE, related_name='permisos_sucursal', to='app.sucursal')),
            ],
            options={
                'verbose_name': 'Permiso por Sucursal',
                'verbose_name_plural': 'Permisos por Sucursal',
                'ordering': ['sucursal', 'opcion_menu'],
                'unique_together': {('sucursal', 'opcion_menu')},
            },
        ),
    ]
