# Generated by Django 5.2 on 2026-01-24 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0086_add_descartado_cambio_precio'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='movimientos_producto',
            new_name='app_movimie_sucursa_ce69b6_idx',
            old_name='app_movimie_sucursa_7a8b9c_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientos_producto',
            new_name='app_movimie_sucursa_eb04f6_idx',
            old_name='app_movimie_sucursa_1d2e3f_idx',
        ),
        migrations.RenameIndex(
            model_name='movimientos_producto',
            new_name='app_movimie_fecha_cdfa97_idx',
            old_name='app_movimie_fecha_d_4g5h6i_idx',
        ),
        # AddField for movimiento_ingreso removed - column already exists in database
        # (was added by a previous migration that is no longer tracked)
    ]
