# Generated by Django 5.2 on 2026-01-26 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0087_rename_app_movimie_sucursa_7a8b9c_idx_app_movimie_sucursa_ce69b6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productos_recepcionados',
            name='movimiento_ingreso',
            field=models.ForeignKey(blank=True, help_text='Movimiento de ingreso generado por esta recepción', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_asociadas', to='app.movimientos_producto'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='nombre_impresora_acepta',
            field=models.CharField(default='boleta', help_text='Nombre de la impresora configurada en Acepta para DTEs (ej: boleta, factura, termica1)', max_length=100, verbose_name='Nombre Impresora Acepta'),
        ),
    ]
