# Generated by Django 5.2 on 2026-01-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0088_productos_recepcionados_movimiento_ingreso_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sucursal',
            name='nombre_impresora_acepta',
        ),
        migrations.AddField(
            model_name='sucursal',
            name='nombre_impresora_boleta',
            field=models.CharField(default='boleta', help_text='Nombre de la impresora en Acepta para Boletas Electrónicas', max_length=100, verbose_name='Impresora Boleta Electrónica'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='nombre_impresora_factura',
            field=models.CharField(default='factura', help_text='Nombre de la impresora en Acepta para Facturas Electrónicas', max_length=100, verbose_name='Impresora Factura Electrónica'),
        ),
    ]
