# Generated by Django 4.2.2 on 2026-03-23 18:12

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0090_enrich_empresa_sucursal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='Apellido')),
                ('rut', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Formato de RUT inválido. Use formato: 12345678-9 o 12.345.678-9', regex='^(\\d{1,2}\\.\\d{3}\\.\\d{3}-[\\dkK]|\\d{7,8}-[\\dkK])$')], verbose_name='RUT')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('direccion', models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección')),
                ('comuna', models.CharField(blank=True, max_length=100, null=True, verbose_name='Comuna')),
                ('ciudad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True, verbose_name='Género')),
                ('tipo_cliente', models.CharField(choices=[('INDIVIDUAL', 'Cliente Individual'), ('EMPRESARIAL', 'Cliente Empresarial'), ('MAYORISTA', 'Mayorista'), ('DISTRIBUIDOR', 'Distribuidor')], default='INDIVIDUAL', max_length=20, verbose_name='Tipo de Cliente')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_creados_app', to=settings.AUTH_USER_MODEL, verbose_name='Creado por')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_crm', to='app.empresa', verbose_name='Empresa Asociada')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clientes_modificados_app', to=settings.AUTH_USER_MODEL, verbose_name='Modificado por')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(max_length=50, unique=True, verbose_name='Código de Proveedor')),
                ('categoria', models.CharField(blank=True, max_length=100, null=True, verbose_name='Categoría')),
                ('dias_credito', models.IntegerField(default=30, verbose_name='Días de Crédito')),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento (%)')),
                ('calificacion', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True, verbose_name='Calificación')),
                ('observaciones_evaluacion', models.TextField(blank=True, null=True, verbose_name='Observaciones de Evaluación')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_crm', to='app.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['empresa__nombre'],
            },
        ),
        migrations.CreateModel(
            name='ContactoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('cargo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('telefono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('celular', models.CharField(blank=True, max_length=20, null=True, verbose_name='Celular')),
                ('tipo_contacto', models.CharField(choices=[('PRINCIPAL', 'Contacto Principal'), ('COMPRAS', 'Compras'), ('VENTAS', 'Ventas'), ('ADMINISTRACION', 'Administración'), ('FINANZAS', 'Finanzas'), ('TECNICO', 'Técnico'), ('OTRO', 'Otro')], default='PRINCIPAL', max_length=20, verbose_name='Tipo de Contacto')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_crm', to='app.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Contacto de Empresa',
                'verbose_name_plural': 'Contactos de Empresa',
                'ordering': ['empresa', 'tipo_contacto', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='LogEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_crm', to='app.empresa', verbose_name='Empresa')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_empresa_app', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Empresa',
                'verbose_name_plural': 'Logs de Empresa',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['empresa', 'fecha'], name='app_logempr_empresa_02f025_idx'), models.Index(fields=['accion', 'fecha'], name='app_logempr_accion_2e88b3_idx'), models.Index(fields=['usuario', 'fecha'], name='app_logempr_usuario_44ac59_idx')],
            },
        ),
        migrations.CreateModel(
            name='LogCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='Fecha')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('user_agent', models.TextField(blank=True, null=True, verbose_name='User Agent')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_crm', to='app.cliente', verbose_name='Cliente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_cliente_app', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Log de Cliente',
                'verbose_name_plural': 'Logs de Cliente',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['cliente', 'fecha'], name='app_logclie_cliente_5896a7_idx'), models.Index(fields=['accion', 'fecha'], name='app_logclie_accion_a57d54_idx'), models.Index(fields=['usuario', 'fecha'], name='app_logclie_usuario_0b1114_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nombre', 'apellido'], name='app_cliente_nombre_4e9e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['rut'], name='app_cliente_rut_39eba1_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['email'], name='app_cliente_email_0804fa_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['tipo_cliente'], name='app_cliente_tipo_cl_b57c77_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['activo'], name='app_cliente_activo_40a375_idx'),
        ),
    ]
