# Generated by Django 4.2.2 on 2026-03-23 18:14

from django.db import migrations


def migrate_empresa_mgmt_to_app(apps, schema_editor):
    """
    Copy CRM data from empresa_management tables to new app tables.
    Maps empresa_id by matching RUT between empresa_management.Empresa
    and app.Empresa.
    """
    db_alias = schema_editor.connection.alias

    EM_Empresa = apps.get_model('empresa_management', 'Empresa')
    APP_Empresa = apps.get_model('app', 'Empresa')

    EM_ContactoEmpresa = apps.get_model('empresa_management', 'ContactoEmpresa')
    APP_ContactoEmpresa = apps.get_model('app', 'ContactoEmpresa')

    EM_Cliente = apps.get_model('empresa_management', 'Cliente')
    APP_Cliente = apps.get_model('app', 'Cliente')

    EM_Proveedor = apps.get_model('empresa_management', 'Proveedor')
    APP_Proveedor = apps.get_model('app', 'Proveedor')

    EM_LogEmpresa = apps.get_model('empresa_management', 'LogEmpresa')
    APP_LogEmpresa = apps.get_model('app', 'LogEmpresa')

    EM_LogCliente = apps.get_model('empresa_management', 'LogCliente')
    APP_LogCliente = apps.get_model('app', 'LogCliente')

    # Build RUT-to-app.Empresa mapping
    em_to_app = {}
    for em_emp in EM_Empresa.objects.using(db_alias).all():
        rut_clean = (em_emp.rut or '').replace('.', '').replace('-', '').upper()
        if not rut_clean:
            continue
        app_emp = None
        for candidate in APP_Empresa.objects.using(db_alias).all():
            c_rut = (candidate.rut or '').replace('.', '').replace('-', '').upper()
            if c_rut == rut_clean:
                app_emp = candidate
                break
        if app_emp is None:
            app_emp = APP_Empresa.objects.using(db_alias).create(
                nombre=em_emp.nombre or '',
                rut=em_emp.rut or '',
                nombre_fantasia=em_emp.nombre_fantasia or '',
                razon_social=em_emp.razon_social or '',
                giro=em_emp.giro or '',
                direccion=em_emp.direccion or '',
                comuna=em_emp.comuna or '',
                ciudad=em_emp.ciudad or '',
                esProveedor=em_emp.esProveedor,
                correoVendedor=em_emp.correoVendedor or '',
                correoIntercambio=em_emp.correoIntercambio or '',
                correoAdministrador=em_emp.correoAdministrador or '',
            )
        em_to_app[em_emp.pk] = app_emp.pk

    # Migrate ContactoEmpresa
    for obj in EM_ContactoEmpresa.objects.using(db_alias).all():
        app_empresa_id = em_to_app.get(obj.empresa_id)
        if app_empresa_id is None:
            continue
        APP_ContactoEmpresa.objects.using(db_alias).create(
            empresa_id=app_empresa_id,
            nombre=obj.nombre,
            cargo=obj.cargo,
            email=obj.email,
            telefono=obj.telefono,
            celular=obj.celular,
            tipo_contacto=obj.tipo_contacto,
            activo=obj.activo,
        )

    # Migrate Cliente (keep a mapping for LogCliente)
    em_cliente_to_app = {}
    for obj in EM_Cliente.objects.using(db_alias).all():
        app_empresa_id = em_to_app.get(obj.empresa_id) if obj.empresa_id else None
        new_cliente = APP_Cliente.objects.using(db_alias).create(
            nombre=obj.nombre,
            apellido=obj.apellido,
            rut=obj.rut,
            email=obj.email,
            telefono=obj.telefono,
            celular=obj.celular,
            direccion=obj.direccion,
            comuna=obj.comuna,
            ciudad=obj.ciudad,
            fecha_nacimiento=obj.fecha_nacimiento,
            genero=obj.genero,
            tipo_cliente=obj.tipo_cliente,
            empresa_id=app_empresa_id,
            activo=obj.activo,
            observaciones=obj.observaciones,
            created_by_id=obj.created_by_id,
            updated_by_id=obj.updated_by_id,
        )
        em_cliente_to_app[obj.pk] = new_cliente.pk

    # Migrate Proveedor
    for obj in EM_Proveedor.objects.using(db_alias).all():
        app_empresa_id = em_to_app.get(obj.empresa_id)
        if app_empresa_id is None:
            continue
        if APP_Proveedor.objects.using(db_alias).filter(empresa_id=app_empresa_id).exists():
            continue
        APP_Proveedor.objects.using(db_alias).create(
            empresa_id=app_empresa_id,
            codigo_proveedor=obj.codigo_proveedor,
            categoria=obj.categoria,
            dias_credito=obj.dias_credito,
            descuento_porcentaje=obj.descuento_porcentaje,
            calificacion=obj.calificacion,
            observaciones_evaluacion=obj.observaciones_evaluacion,
            activo=obj.activo,
        )

    # Migrate LogEmpresa
    for obj in EM_LogEmpresa.objects.using(db_alias).all():
        app_empresa_id = em_to_app.get(obj.empresa_id)
        if app_empresa_id is None:
            continue
        APP_LogEmpresa.objects.using(db_alias).create(
            empresa_id=app_empresa_id,
            usuario_id=obj.usuario_id,
            accion=obj.accion,
            descripcion=obj.descripcion,
            datos_anteriores=obj.datos_anteriores,
            datos_nuevos=obj.datos_nuevos,
            ip_address=obj.ip_address,
            user_agent=obj.user_agent,
        )

    # Migrate LogCliente
    for obj in EM_LogCliente.objects.using(db_alias).all():
        app_cliente_id = em_cliente_to_app.get(obj.cliente_id)
        if app_cliente_id is None:
            continue
        APP_LogCliente.objects.using(db_alias).create(
            cliente_id=app_cliente_id,
            usuario_id=obj.usuario_id,
            accion=obj.accion,
            descripcion=obj.descripcion,
            datos_anteriores=obj.datos_anteriores,
            datos_nuevos=obj.datos_nuevos,
            ip_address=obj.ip_address,
            user_agent=obj.user_agent,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0091_add_crm_models'),
        ('empresa_management', '0002_alter_cliente_rut_alter_empresa_rut'),
    ]

    operations = [
        migrations.RunPython(
            migrate_empresa_mgmt_to_app,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
