# Generated by Django 4.2.2 on 2026-03-23 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0092_migrate_empresa_mgmt_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras_producto',
            name='es_reposicion',
            field=models.BooleanField(default=False, help_text='True = reposición de stock existente, False = producto nuevo', verbose_name='Es reposición'),
        ),
        migrations.AddField(
            model_name='compras_producto',
            name='precio_anterior',
            field=models.IntegerField(blank=True, help_text='Precio de venta vigente antes de esta compra (solo aplica en reposiciones)', null=True, verbose_name='Precio anterior'),
        ),
        migrations.AddField(
            model_name='compras_producto',
            name='precio_nuevo',
            field=models.IntegerField(blank=True, help_text='Precio de venta que traerá esta compra (si difiere del anterior)', null=True, verbose_name='Precio nuevo'),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='es_reposicion',
            field=models.BooleanField(default=False, help_text='Hereda de Compras_Producto al momento de recepcionar', verbose_name='Es reposición'),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='precio_anterior',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio anterior al momento de recepción'),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='precio_nuevo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Precio nuevo tras recepción'),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='sucursal_destino',
            field=models.ForeignKey(blank=True, help_text='Sucursal donde se recepcionó el producto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recepciones_destino', to='app.sucursal', verbose_name='Sucursal destino'),
        ),
    ]
