# Generated by Django 4.2.2 on 2026-03-24 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0094_add_prediccion_compras'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditotrabajador',
            options={'ordering': ['-fecha_solicitud'], 'verbose_name': 'Crédito', 'verbose_name_plural': 'Créditos'},
        ),
        migrations.RemoveIndex(
            model_name='creditotrabajador',
            name='app_credito_trabaja_f8800d_idx',
        ),
        migrations.AddField(
            model_name='creditotrabajador',
            name='beneficiario',
            field=models.ForeignKey(blank=True, help_text='Cliente que recibe el crédito', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos_recibidos', to='app.cliente'),
        ),
        migrations.AddField(
            model_name='creditotrabajador',
            name='tipo_beneficiario',
            field=models.CharField(choices=[('EMPLEADO', 'Empleado / Trabajador Interno'), ('CLIENTE_EXTERNO', 'Cliente Externo')], default='EMPLEADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('INDIVIDUAL', 'Cliente Individual'), ('EMPRESARIAL', 'Cliente Empresarial'), ('MAYORISTA', 'Mayorista'), ('DISTRIBUIDOR', 'Distribuidor'), ('EMPLEADO', 'Empleado / Trabajador Interno'), ('CREDITO_EXTERNO', 'Cliente con Crédito Externo')], default='INDIVIDUAL', max_length=20, verbose_name='Tipo de Cliente'),
        ),
        migrations.AlterField(
            model_name='creditotrabajador',
            name='trabajador',
            field=models.ForeignKey(blank=True, help_text='DEPRECADO - usar beneficiario', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='creditos_recibidos_legacy', to='app.vendedor'),
        ),
        migrations.AddIndex(
            model_name='creditotrabajador',
            index=models.Index(fields=['beneficiario', 'estado'], name='app_credito_benefic_ce6982_idx'),
        ),
    ]
