# Generated by Django 4.2.2 on 2026-03-24 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0096_migrate_creditos_to_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditotrabajador',
            name='trabajador',
        ),
    ]
