# Generated by Django 4.2.2 on 2026-03-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0097_remove_trabajador_from_credito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertavelocidad',
            name='ratio_velocidad',
            field=models.DecimalField(decimal_places=2, help_text='velocidad_normal / velocidad_real — < 1 = más rápido de lo normal', max_digits=8),
        ),
        migrations.AlterField(
            model_name='alertavelocidad',
            name='semanas_activo',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='alertavelocidad',
            name='semanas_stock_restante',
            field=models.DecimalField(decimal_places=2, help_text='Semanas de stock al ritmo actual', max_digits=8),
        ),
        migrations.AlterField(
            model_name='alertavelocidad',
            name='semanas_temporada_restante',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='alertavelocidad',
            name='velocidad_normal_semanas',
            field=models.DecimalField(decimal_places=2, help_text='Tomada de VelocidadHistorica.velocidad_semanas_p50', max_digits=8),
        ),
        migrations.AlterField(
            model_name='alertavelocidad',
            name='velocidad_real_semanas',
            field=models.DecimalField(decimal_places=2, help_text='Unidades vendidas por semana actualmente', max_digits=8),
        ),
        migrations.AlterField(
            model_name='velocidadhistorica',
            name='velocidad_semanas_p25',
            field=models.DecimalField(decimal_places=2, help_text='Percentil 25: el 25%% rota más rápido que esto', max_digits=8),
        ),
        migrations.AlterField(
            model_name='velocidadhistorica',
            name='velocidad_semanas_p50',
            field=models.DecimalField(decimal_places=2, help_text='Mediana de semanas para agotar stock', max_digits=8),
        ),
        migrations.AlterField(
            model_name='velocidadhistorica',
            name='velocidad_semanas_p75',
            field=models.DecimalField(decimal_places=2, help_text='Percentil 75: rotación lenta', max_digits=8),
        ),
    ]
