# Generated by Django 4.2.2 on 2026-03-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0100_fix_excluir_de_analitica_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='sucursal',
            name='nombre_impresora_termica',
            field=models.CharField(blank=True, default='EPSON TM-T20II', help_text='Nombre exacto como aparece en Windows → Dispositivos e impresoras', max_length=100, null=True, verbose_name='Impresora Térmica (QZ Tray)'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='usar_qz_tray',
            field=models.BooleanField(default=False, help_text='Si está activo usa QZ Tray (impresión silenciosa). Si no, usa window.print()', verbose_name='Usar QZ Tray'),
        ),
    ]
