# Generated by Django 4.2.2 on 2026-03-30 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0102_deposito_bancario_declaracion_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion_empresa',
            name='estado_despacho',
            field=models.CharField(blank=True, choices=[('PENDIENTE', 'Pendiente de Despacho'), ('PARCIAL', 'Despacho Parcial'), ('COMPLETADO', 'Despacho Completado')], help_text='Estado del despacho cuando la cotización tiene ítems sin SKU al facturar', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion_empresa_detalle',
            name='fecha_asignacion_sku',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se asignó el SKU post-factura', null=True),
        ),
        migrations.AddField(
            model_name='cotizacion_empresa_detalle',
            name='sku_asignado_post_factura',
            field=models.BooleanField(default=False, help_text='True cuando un ítem pendiente recibe SKU después de facturar'),
        ),
        migrations.AddField(
            model_name='cotizacion_empresa_detalle',
            name='usuario_asignacion_sku',
            field=models.ForeignKey(blank=True, help_text='Usuario que realizó la asignación de SKU post-factura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_sku_asignados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='dte',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA ELECTRONICA', 'Factura Electrónica'), ('BOLETA ELECTRONICA', 'Boleta Electrónica'), ('BOLETA PAPEL', 'Boleta Papel'), ('GUIA', 'Guía de Despacho'), ('NOTA DE PEDIDO', 'Nota de Pedido'), ('NOTA DE CREDITO', 'Nota de Crédito'), ('NOTA DE DEBITO', 'Nota de Débito'), ('FACTURA EXENTA', 'Factura Exenta'), ('COTIZACION', 'Cotización'), ('COMPRA', 'Compra'), ('TICKET', 'Ticket'), ('TICKET CAMBIO', 'Ticket de Cambio'), ('TRASPASO', 'Traspaso'), ('AJUSTE', 'Ajuste de Inventario')], max_length=20),
        ),
        migrations.AlterField(
            model_name='historialcambiodevolucion',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('APROBADO', 'Aprobado'), ('APROBADO_Y_EJECUTADO', 'Aprobado y Ejecutado'), ('RECHAZADO', 'Rechazado'), ('EJECUTADO', 'Ejecutado'), ('EJECUTADO_COBRO_PENDIENTE', 'Ejecutado - Cobro Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('MODIFICADO', 'Modificado'), ('PAGO_PROCESADO', 'Pago Procesado'), ('PRODUCTO_EVALUADO', 'Producto Evaluado')], max_length=50),
        ),
    ]
