# Generated by Django 4.2.2 on 2026-03-30 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0103_cotizacion_despacho_diferido'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ticket_productos',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dte_productos',
            name='es_pendiente_despacho',
            field=models.BooleanField(default=False, help_text='True cuando corresponde a un ítem de cotización sin SKU asignado'),
        ),
        migrations.AddField(
            model_name='ticket_productos',
            name='cotizacion_detalle_id',
            field=models.IntegerField(blank=True, help_text='ID de Cotizacion_Empresa_Detalle si aplica', null=True),
        ),
        migrations.AddField(
            model_name='ticket_productos',
            name='descripcion_linea',
            field=models.CharField(blank=True, help_text='Descripción para ítems sin SKU (despacho diferido o líneas manuales)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket_productos',
            name='es_pendiente_despacho',
            field=models.BooleanField(default=False, help_text='True cuando el ítem viene de una cotización sin SKU asignado'),
        ),
        migrations.AlterField(
            model_name='dte_productos',
            name='costo',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dte_productos',
            name='descripcion',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dte_productos',
            name='productoTalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='producto_talla_dte', to='app.producto_talla'),
        ),
        migrations.AlterField(
            model_name='dte_productos',
            name='sobreprecio',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='historial_cotizacion',
            name='accion',
            field=models.CharField(choices=[('CREADA', 'Cotización Creada'), ('MODIFICADA', 'Cotización Modificada'), ('ANULADA', 'Cotización Anulada'), ('FACTURADA', 'Convertida a Factura'), ('ENVIADA', 'Enviada al Cliente'), ('VENCIDA', 'Marcada como Vencida'), ('ITEM_AGREGADO', 'Item Agregado'), ('ITEM_MODIFICADO', 'Item Modificado'), ('ITEM_ELIMINADO', 'Item Eliminado'), ('SKU_ASIGNADO', 'SKU Asignado Post-Factura'), ('DESPACHO_COMPLETADO', 'Despacho Completado')], max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='concepto',
            field=models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('INGRESO_MANUAL', 'Ingreso Manual'), ('RECEPCION_COMPRA', 'Recepción de Compra'), ('REPOSICION_STOCK', 'Reposición de Stock'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('TRASPASO_ENTRADA', 'Traspaso Entrada'), ('REGULARIZACION_TRASPASO', 'Regularización de Traspaso'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('DONACION_RECIBIDA', 'Donación Recibida'), ('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('TRASPASO_SALIDA', 'Traspaso Salida'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('PERDIDA_ROBO', 'Pérdida por Robo'), ('PERDIDA_DETERIORO', 'Pérdida por Deterioro'), ('DONACION_ENTREGADA', 'Donación Entregada'), ('DEVOLUCION_PROVEEDOR', 'Devolución a Proveedor'), ('TRASPASO_SUCURSAL', 'Traspaso entre Sucursales'), ('TRASPASO_BODEGA', 'Traspaso a Bodega'), ('TRASPASO_VITRINA', 'Traspaso a Vitrina'), ('CAMBIO_PRODUCTO_SALIDA', 'Cambio de Producto (Salida)'), ('CAMBIO_PRODUCTO_ENTRADA', 'Cambio de Producto (Entrada)'), ('CORRECCION_STOCK', 'Corrección de Stock'), ('ANULACION_REGULARIZACION', 'Anulación de Regularización'), ('DESPACHO_COTIZACION', 'Despacho de Cotización')], default='INGRESO_INICIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket_productos',
            name='ProductoTalla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_productos_talla', to='app.producto_talla'),
        ),
    ]
