# Generated by Django 4.2.2 on 2026-03-30 22:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0104_cotizacion_despacho_diferido'),
    ]

    operations = [
        migrations.CreateModel(
            name='TareaAplicacionAjustes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En proceso'), ('COMPLETADO', 'Completado'), ('ERROR', 'Error')], default='PENDIENTE', max_length=20)),
                ('total', models.IntegerField(default=0)),
                ('procesados', models.IntegerField(default=0)),
                ('errores', models.JSONField(default=list)),
                ('iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('finalizada_en', models.DateTimeField(blank=True, null=True)),
                ('creada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('inventario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarea_ajustes', to='app.tomainventario')),
            ],
            options={
                'verbose_name': 'Tarea de Aplicación de Ajustes',
                'verbose_name_plural': 'Tareas de Aplicación de Ajustes',
            },
        ),
    ]
