# Generated by Django 4.2.2 on 2026-03-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0106_pedido_ecommerce'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pedidoecommerce',
            new_name='app_pedido__estado_b9861a_idx',
            old_name='app_pe_estado_fecha_idx',
        ),
        migrations.RenameIndex(
            model_name='pedidoecommerce',
            new_name='app_pedido__canal_o_fe7139_idx',
            old_name='app_pe_canal_estado_idx',
        ),
        migrations.RenameIndex(
            model_name='pedidoecommerce',
            new_name='app_pedido__sucursa_c35a34_idx',
            old_name='app_pe_suc_estado_idx',
        ),
        migrations.AlterField(
            model_name='historialcambioprecio',
            name='tipo_cambio',
            field=models.CharField(choices=[('MANUAL', 'Cambio Manual'), ('RECOMENDACION', 'Por Recomendación'), ('MASIVO', 'Cambio Masivo'), ('SINCRONIZACION', 'Sincronización'), ('APROBACION', 'Por Aprobación'), ('ACTUALIZACION_RECEPCION', 'Actualización por Recepción'), ('ACTUALIZACION_MANUAL', 'Actualización Manual')], default='MANUAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='concepto',
            field=models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('INGRESO_MANUAL', 'Ingreso Manual'), ('RECEPCION_COMPRA', 'Recepción de Compra'), ('REPOSICION_STOCK', 'Reposición de Stock'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('TRASPASO_ENTRADA', 'Traspaso Entrada'), ('REGULARIZACION_TRASPASO', 'Regularización de Traspaso'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('DONACION_RECIBIDA', 'Donación Recibida'), ('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('TRASPASO_SALIDA', 'Traspaso Salida'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('PERDIDA_ROBO', 'Pérdida por Robo'), ('PERDIDA_DETERIORO', 'Pérdida por Deterioro'), ('DONACION_ENTREGADA', 'Donación Entregada'), ('DEVOLUCION_PROVEEDOR', 'Devolución a Proveedor'), ('TRASPASO_SUCURSAL', 'Traspaso entre Sucursales'), ('TRASPASO_BODEGA', 'Traspaso a Bodega'), ('TRASPASO_VITRINA', 'Traspaso a Vitrina'), ('CAMBIO_PRODUCTO_SALIDA', 'Cambio de Producto (Salida)'), ('CAMBIO_PRODUCTO_ENTRADA', 'Cambio de Producto (Entrada)'), ('CORRECCION_STOCK', 'Corrección de Stock'), ('ANULACION_REGULARIZACION', 'Anulación de Regularización'), ('AJUSTE_INVENTARIO_ENTRADA', 'Ajuste Inventario - Entrada (Sobrante)'), ('AJUSTE_INVENTARIO_SALIDA', 'Ajuste Inventario - Salida (Faltante)'), ('DESPACHO_COTIZACION', 'Despacho de Cotización')], default='INGRESO_INICIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='pedidoecommerce',
            name='cliente_documento',
            field=models.CharField(blank=True, help_text='RUT o documento para emisión de DTE', max_length=20, verbose_name='RUT/Doc.'),
        ),
        migrations.AlterField(
            model_name='pedidoecommerce',
            name='items',
            field=models.JSONField(blank=True, default=list, help_text='Lista de productos: [{sku, nombre, cantidad, precio_unitario, ...}]', verbose_name='Ítems'),
        ),
        migrations.AlterField(
            model_name='pedidoecommerce',
            name='numero_pedido_canal',
            field=models.CharField(db_index=True, help_text='ID/número del pedido en el marketplace de origen', max_length=255, verbose_name='N° Pedido Canal'),
        ),
    ]
