# Generated by Django 4.2.2 on 2026-04-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0109_add_producto_articulo_sku_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='articulo',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='producto_talla',
            name='sku',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='modulo_origen',
            field=models.CharField(choices=[('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('POS', 'Punto de Venta'), ('CAMBIO_DEVOLUCION', 'Cambio/Devolución'), ('ECOMMERCE', 'Venta Ecommerce')], default='VENTA_PUBLICO', max_length=30),
        ),
    ]
