# Generated by Django 4.2.2 on 2026-04-06 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0110_alter_producto_articulo_alter_producto_talla_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='estado',
            field=models.CharField(choices=[('SOLICITADO', 'Solicitado'), ('EN_PROCESO', 'En Proceso'), ('APROBADO', 'Aprobado'), ('EJECUTADO', 'Ejecutado'), ('EJECUTADO_COBRO_PENDIENTE', 'Ejecutado - Cobro Pendiente'), ('COMPLETADO', 'Completado'), ('RECHAZADO', 'Rechazado'), ('CANCELADO', 'Cancelado'), ('REVERTIDO', 'Revertido')], default='SOLICITADO', max_length=30),
        ),
        migrations.AlterField(
            model_name='historialcambiodevolucion',
            name='accion',
            field=models.CharField(choices=[('CREADO', 'Creado'), ('APROBADO', 'Aprobado'), ('APROBADO_Y_EJECUTADO', 'Aprobado y Ejecutado'), ('RECHAZADO', 'Rechazado'), ('EJECUTADO', 'Ejecutado'), ('EJECUTADO_COBRO_PENDIENTE', 'Ejecutado - Cobro Pendiente'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado'), ('MODIFICADO', 'Modificado'), ('PAGO_PROCESADO', 'Pago Procesado'), ('PRODUCTO_EVALUADO', 'Producto Evaluado'), ('REVERTIDO', 'Revertido'), ('COBRO_DIFERENCIA', 'Cobro de Diferencia')], max_length=50),
        ),
    ]
