# Generated by Django 4.2.2 on 2026-04-06 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0111_add_revertido_state_cambios'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoDeposito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_deposito', models.DateField(help_text='Fecha en que se realizó el depósito bancario')),
                ('monto_total', models.IntegerField(help_text='Monto total del comprobante bancario')),
                ('banco', models.CharField(choices=[('ESTADO', 'BancoEstado'), ('CHILE', 'Banco de Chile'), ('SANTANDER', 'Santander'), ('BCI', 'BCI'), ('SCOTIABANK', 'Scotiabank'), ('ITAU', 'Itaú'), ('SECURITY', 'Banco Security'), ('FALABELLA', 'Banco Falabella'), ('RIPLEY', 'Banco Ripley'), ('OTRO', 'Otro')], default='ESTADO', max_length=20)),
                ('numero_comprobante', models.CharField(blank=True, max_length=50)),
                ('imagen_comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes_bancarios/')),
                ('observaciones', models.TextField(blank=True)),
                ('verificado', models.BooleanField(default=False)),
                ('fecha_verificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grupos_deposito_registrados', to=settings.AUTH_USER_MODEL)),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos_deposito', to='app.sucursal')),
                ('verificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grupos_deposito_verificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Grupo de Depósito',
                'verbose_name_plural': 'Grupos de Depósito',
                'db_table': 'grupo_deposito',
                'ordering': ['-fecha_deposito'],
            },
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='grupo',
            field=models.ForeignKey(blank=True, help_text='Grupo de depósito cuando un solo comprobante cubre varios días', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depositos', to='app.grupodeposito'),
        ),
    ]
