# Generated by Django 4.2.2 on 2026-04-07 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0112_grupo_deposito_multidia'),
    ]

    operations = [
        migrations.AddField(
            model_name='dte_productos',
            name='descuento_monto',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='Monto descuento total linea', max_digits=18, null=True),
        ),
        migrations.AddField(
            model_name='dte_productos',
            name='descuento_pct',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de descuento por item (solo factura)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='dte_productos',
            name='monto_item',
            field=models.IntegerField(default=0, help_text='Monto final de la linea (PrcItem*QtyItem - DescuentoMonto)'),
        ),
        migrations.AddField(
            model_name='dte_productos',
            name='precio_unitario',
            field=models.IntegerField(default=0, help_text='Precio unitario neto (factura) o IVA-inclusive (boleta)'),
        ),
        migrations.CreateModel(
            name='DescuentoRecargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_linea', models.PositiveIntegerField()),
                ('tpo_mov', models.CharField(choices=[('D', 'Descuento'), ('R', 'Recargo')], max_length=1)),
                ('glosa_dr', models.CharField(max_length=45)),
                ('tpo_valor', models.CharField(choices=[('%', 'Porcentaje'), ('$', 'Monto')], max_length=1)),
                ('valor_dr', models.DecimalField(decimal_places=2, max_digits=18)),
                ('ind_exe_dr', models.IntegerField(blank=True, choices=[(1, 'Exento/No afecto'), (2, 'No facturable')], null=True)),
                ('valor_dr_otra_mnda', models.DecimalField(blank=True, decimal_places=6, help_text='Solo facturas: valor en otra moneda', max_digits=18, null=True)),
                ('dte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos_recargos', to='app.dte')),
            ],
            options={
                'verbose_name': 'Descuento/Recargo DTE',
                'verbose_name_plural': 'Descuentos/Recargos DTE',
                'ordering': ['nro_linea'],
                'unique_together': {('dte', 'nro_linea')},
            },
        ),
    ]
