# Generated by Django 4.2.2 on 2026-04-07 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0115_add_ejecutado_devol_pendiente_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicciondemanda',
            name='metodo_usado',
            field=models.CharField(choices=[('similitud', 'Por artículos similares'), ('demanda_observada', 'Demanda observada con corrección censura'), ('promedio_movil_ponderado', 'Promedio móvil ponderado'), ('regresion_lineal', 'Regresión lineal'), ('holt_winters', 'Holt-Winters')], max_length=50),
        ),
    ]
