# Generated by Django 4.2.2 on 2026-04-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0116_update_prediccion_metodo_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predicciondemanda',
            name='metodo_usado',
            field=models.CharField(choices=[('similitud', 'Por artículos similares'), ('demanda_observada', 'Demanda observada con corrección censura'), ('promedio_movil_ponderado', 'Promedio móvil ponderado'), ('regresion_lineal', 'Regresión lineal'), ('holt_winters', 'Holt-Winters'), ('croston_sba', 'Croston SBA (demanda intermitente)')], max_length=50),
        ),
    ]
