# Generated by Django 4.2.2 on 2026-04-09 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0117_add_croston_sba_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoFotoRequerimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion_guia', models.TextField(help_text='Instruccion mostrada al usuario sobre que debe capturar la foto')),
                ('icono', models.CharField(default='ri-image-line', max_length=50)),
                ('tipos_requerimiento', models.JSONField(default=list, help_text='Lista de codigos TIPO_REQUERIMIENTO donde aplica esta foto')),
                ('es_obligatorio', models.BooleanField(default=False)),
                ('orden', models.IntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Foto de Requerimiento',
                'verbose_name_plural': 'Tipos de Foto de Requerimiento',
                'ordering': ['orden'],
            },
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='condicion_producto',
            field=models.CharField(blank=True, choices=[('NUEVO_SIN_USO', 'Nuevo sin uso'), ('USADO_POCO', 'Usado poco tiempo'), ('USADO_NORMAL', 'Uso normal')], help_text='Condicion del producto al momento del reclamo', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='fotos_completas',
            field=models.BooleanField(default=False, help_text='Indica si todas las fotos obligatorias fueron subidas'),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='notas_internas',
            field=models.TextField(blank=True, help_text='Notas internas solo visibles para admin/supervisor', null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='producto_esperado',
            field=models.CharField(blank=True, help_text='Producto/talla/color que se esperaba recibir (para errores de despacho)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='severidad_defecto',
            field=models.CharField(blank=True, choices=[('LEVE', 'Leve - Estetico, no afecta uso'), ('MODERADO', 'Moderado - Afecta uso parcialmente'), ('GRAVE', 'Grave - Producto inutilizable')], help_text='Severidad del defecto (solo para PRODUCTO_FALLADO)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='requerimiento',
            name='subtipo',
            field=models.CharField(blank=True, help_text='Subtipo especifico (depende del tipo principal)', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='fotorequerimiento',
            name='descripcion',
            field=models.CharField(blank=True, help_text='Descripcion de la foto', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='fotorequerimiento',
            name='orden',
            field=models.IntegerField(default=0, help_text='Orden de la foto (1-8)'),
        ),
        migrations.AlterField(
            model_name='historialrequerimiento',
            name='accion',
            field=models.CharField(help_text='Tipo de accion realizada', max_length=100),
        ),
        migrations.AlterField(
            model_name='historialrequerimiento',
            name='comentario',
            field=models.TextField(blank=True, help_text='Comentario o descripcion de la accion', null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='cliente_telefono',
            field=models.CharField(blank=True, help_text='Telefono de contacto', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='correo_enviado_proveedor',
            field=models.BooleanField(default=False, help_text='Indica si se envio correo al proveedor'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='correo_proveedor_destino',
            field=models.CharField(blank=True, help_text='Email al que se envio el requerimiento', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='decision_proveedor',
            field=models.CharField(blank=True, choices=[('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado'), ('PARCIAL', 'Aprobado Parcial')], help_text='Decision del proveedor', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='descripcion_problema',
            field=models.TextField(blank=True, help_text='Descripcion detallada del problema', null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En Revision'), ('ESPERANDO_RESPUESTA', 'Esperando Respuesta Proveedor'), ('APROBADO', 'Aprobado por Proveedor'), ('RECHAZADO', 'Rechazado por Proveedor'), ('EN_PROCESO', 'En Proceso de Resolucion'), ('COMPLETADO', 'Completado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=30),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='fecha_envio_proveedor',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se envio al proveedor', null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, help_text='Fecha de resolucion del requerimiento', null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='intentos_envio',
            field=models.IntegerField(default=0, help_text='Numero de veces que se ha enviado al proveedor'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='motivo',
            field=models.TextField(help_text='Descripcion del motivo del requerimiento'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='motivo_resolucion',
            field=models.TextField(blank=True, help_text='Motivo visible al usuario de por que se aprobo o rechazo', null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='numero_boleta',
            field=models.CharField(blank=True, help_text='Numero de boleta o documento de venta', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='numero_requerimiento',
            field=models.CharField(help_text='Numero unico de requerimiento (autogenerado)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='proveedor',
            field=models.ForeignKey(blank=True, help_text='Proveedor al que se envia el requerimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_como_proveedor', to='app.empresa'),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='resolucion',
            field=models.TextField(blank=True, help_text='Descripcion de la resolucion final', null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='tipo',
            field=models.CharField(choices=[('PRODUCTO_FALLADO', 'Producto Fallado / Defectuoso'), ('ERROR_DESPACHO', 'Error de Despacho'), ('GARANTIA', 'Garantia Producto'), ('DEVOLUCION', 'Devolucion a Proveedor'), ('RECLAMO', 'Reclamo'), ('CONSULTA', 'Consulta Tecnica'), ('OTROS', 'Otros')], default='GARANTIA', max_length=30),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='ultimo_recordatorio',
            field=models.DateTimeField(blank=True, help_text='Fecha del ultimo recordatorio enviado', null=True),
        ),
        migrations.AlterField(
            model_name='requerimiento',
            name='usuario_creador',
            field=models.ForeignKey(help_text='Usuario que creo el requerimiento', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimientos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='requerimiento',
            index=models.Index(fields=['tipo', 'subtipo'], name='app_requeri_tipo_a5f958_idx'),
        ),
        migrations.AddField(
            model_name='fotorequerimiento',
            name='tipo_foto',
            field=models.ForeignKey(blank=True, help_text='Tipo/proposito de esta foto', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fotos', to='app.tipofotorequerimiento'),
        ),
    ]
