# Generated by Django 4.2.2 on 2026-04-09 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0119_seed_tipos_foto_requerimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermisoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puede_ver', models.BooleanField(blank=True, default=None, help_text='True=otorgar, False=denegar, None=usar rol', null=True)),
                ('puede_crear', models.BooleanField(blank=True, default=None, help_text='True=otorgar, False=denegar, None=usar rol', null=True)),
                ('puede_editar', models.BooleanField(blank=True, default=None, help_text='True=otorgar, False=denegar, None=usar rol', null=True)),
                ('puede_eliminar', models.BooleanField(blank=True, default=None, help_text='True=otorgar, False=denegar, None=usar rol', null=True)),
                ('puede_exportar', models.BooleanField(blank=True, default=None, help_text='True=otorgar, False=denegar, None=usar rol', null=True)),
                ('puede_aprobar', models.BooleanField(blank=True, default=None, help_text='True=otorgar, False=denegar, None=usar rol', null=True)),
                ('limite_descuento_override', models.DecimalField(blank=True, decimal_places=2, help_text='Override del límite de descuento. None=usar límite del rol', max_digits=5, null=True)),
                ('puede_ver_todas_sucursales', models.BooleanField(default=False, help_text='Si True, el usuario puede ver datos de todas las sucursales en reportes y listados')),
                ('notas', models.TextField(blank=True, help_text='Razón del override o notas administrativas', null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('opcion_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to='app.opcionmenu')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permiso por Usuario',
                'verbose_name_plural': 'Permisos por Usuario',
                'ordering': ['usuario', 'opcion_menu'],
                'unique_together': {('usuario', 'opcion_menu')},
            },
        ),
    ]
