# Generated by Django 4.2.2 on 2026-04-10 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0120_add_permiso_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='depositobancario',
            name='observaciones_supervisor',
            field=models.TextField(blank=True, help_text='Observaciones del supervisor al confirmar o rechazar el depósito'),
        ),
        migrations.AddField(
            model_name='depositobancario',
            name='tipo_medio',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('CHEQUE', 'Cheque')], default='EFECTIVO', help_text='Tipo de medio depositado (efectivo o cheque)', max_length=20),
        ),
        migrations.AlterField(
            model_name='arqueocaja',
            name='estado',
            field=models.CharField(choices=[('ABIERTO', 'En Proceso'), ('CERRADO', 'Cerrado'), ('CON_DIFERENCIAS', 'Con Diferencias'), ('DEPOSITO_DECLARADO', 'Depósito Declarado'), ('DEPOSITO_CONFIRMADO', 'Depósito Confirmado'), ('REVISADO', 'Revisado por Supervisor')], default='ABIERTO', max_length=20),
        ),
        migrations.CreateModel(
            name='HistorialReaperturaArqueo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reapertura', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(max_length=20)),
                ('justificacion', models.TextField(help_text='Motivo de la reapertura')),
                ('arqueo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_reaperturas', to='app.arqueocaja')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reaperturas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Reapertura',
                'verbose_name_plural': 'Historial de Reaperturas',
                'ordering': ['-fecha_reapertura'],
            },
        ),
    ]
