# Generated by Django 4.2.2 on 2026-04-10 19:44

from django.db import migrations


def crear_parametros_reapertura(apps, schema_editor):
    ParametroGlobal = apps.get_model('app', 'ParametroGlobal')
    ParametroGlobal.objects.get_or_create(
        nombre='DIAS_TOLERANCIA_REAPERTURA_JEFE_LOCAL',
        defaults={'valor_entero': 2},
    )
    ParametroGlobal.objects.get_or_create(
        nombre='DIAS_TOLERANCIA_REAPERTURA_ADMIN',
        defaults={'valor_entero': 0},  # 0 = ilimitado
    )


def revertir_parametros(apps, schema_editor):
    ParametroGlobal = apps.get_model('app', 'ParametroGlobal')
    ParametroGlobal.objects.filter(
        nombre__in=['DIAS_TOLERANCIA_REAPERTURA_JEFE_LOCAL', 'DIAS_TOLERANCIA_REAPERTURA_ADMIN']
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0121_mejora_cuadratura_caja'),
    ]

    operations = [
        migrations.RunPython(crear_parametros_reapertura, revertir_parametros),
    ]
