# Generated by Django 4.2.2 on 2026-04-10 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0122_seed_parametros_reapertura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcambiodevolucion',
            name='estado_anterior',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='historialcambiodevolucion',
            name='estado_nuevo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
