# Generated by Django 4.2.2 on 2026-04-11 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0123_fix_historial_estado_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPedidoEcommerce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(blank=True, max_length=20)),
                ('estado_nuevo', models.CharField(blank=True, max_length=20)),
                ('sub_estado_anterior', models.CharField(blank=True, max_length=30)),
                ('sub_estado_nuevo', models.CharField(blank=True, max_length=30)),
                ('motivo', models.TextField(blank=True)),
                ('tipo_evento', models.CharField(choices=[('CAMBIO_ESTADO', 'Cambio de estado'), ('REASIGNACION', 'Reasignación de sucursal'), ('FACTURACION', 'Facturación'), ('ERROR', 'Error')], default='CAMBIO_ESTADO', max_length=30)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Historial Pedido Ecommerce',
                'verbose_name_plural': 'Historial Pedidos Ecommerce',
                'db_table': 'app_historial_pedido_ecommerce',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='MetricaAsignacionPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fue_reasignado', models.BooleanField(default=False)),
                ('motivo_reasignacion', models.CharField(blank=True, choices=[('SIN_STOCK', 'Sin stock en sucursal'), ('MANUAL', 'Reasignación manual'), ('DISTRIBUCION_AUTO', 'Distribución automática')], max_length=50)),
                ('todos_items_con_stock', models.BooleanField(default=True)),
                ('items_sin_stock', models.IntegerField(default=0)),
                ('tiempo_procesamiento_min', models.IntegerField(blank=True, help_text='Minutos desde recepción hasta facturación', null=True, verbose_name='Tiempo procesamiento (min)')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Métrica Asignación Pedido',
                'verbose_name_plural': 'Métricas Asignación Pedidos',
                'db_table': 'app_metrica_asignacion_pedido',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='pedidoecommerce',
            name='asignado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_ecommerce_asignados', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por'),
        ),
        migrations.AddField(
            model_name='pedidoecommerce',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha asignación'),
        ),
        migrations.AddField(
            model_name='pedidoecommerce',
            name='prioridad',
            field=models.IntegerField(choices=[(0, 'Normal'), (1, 'Alta'), (2, 'Urgente')], default=0, verbose_name='Prioridad'),
        ),
        migrations.AddField(
            model_name='pedidoecommerce',
            name='sub_estado',
            field=models.CharField(choices=[('RECIBIDO', 'Recibido'), ('ASIGNADO', 'Asignado a Sucursal'), ('EN_PREPARACION', 'En Preparación'), ('LISTO_DESPACHO', 'Listo para Despacho'), ('FACTURADO_OK', 'Facturado OK'), ('CANCELADO_CLIENTE', 'Cancelado por Cliente'), ('CANCELADO_SIN_STOCK', 'Cancelado por Sin Stock'), ('ERROR_STOCK', 'Error de Stock'), ('ERROR_DTE', 'Error al Generar DTE')], db_index=True, default='RECIBIDO', max_length=30, verbose_name='Sub-estado'),
        ),
        migrations.AddField(
            model_name='pedidoecommerce',
            name='sucursal_original',
            field=models.ForeignKey(blank=True, help_text='Primera sucursal asignada al recibir el pedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_ecommerce_originales', to='app.sucursal', verbose_name='Sucursal original'),
        ),
        migrations.AddIndex(
            model_name='pedidoecommerce',
            index=models.Index(fields=['sub_estado', 'fecha_recepcion'], name='app_pedido__sub_est_7690f8_idx'),
        ),
        migrations.AddField(
            model_name='metricaasignacionpedido',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_asignacion', to='app.pedidoecommerce'),
        ),
        migrations.AddField(
            model_name='metricaasignacionpedido',
            name='sucursal_asignada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_asignacion_pedidos', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='historialpedidoecommerce',
            name='pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='app.pedidoecommerce'),
        ),
        migrations.AddField(
            model_name='historialpedidoecommerce',
            name='sucursal_anterior',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='historialpedidoecommerce',
            name='sucursal_nueva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='app.sucursal'),
        ),
        migrations.AddField(
            model_name='historialpedidoecommerce',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='metricaasignacionpedido',
            index=models.Index(fields=['sucursal_asignada', 'fecha'], name='app_metrica_sucursa_11ba8e_idx'),
        ),
    ]
