# Generated by Django 4.2.2 on 2026-04-11 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0126_cambios_devoluciones_overhaul'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAccionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('VER_CUADRATURA', 'Visualizar Cuadratura'), ('GENERAR_CUADRATURA', 'Generar Cuadratura'), ('GUARDAR_CONTEO', 'Guardar Conteo Físico'), ('CERRAR_ARQUEO', 'Cerrar Arqueo'), ('ELIMINAR_ARQUEO', 'Eliminar Arqueo'), ('REABRIR_ARQUEO', 'Reabrir Arqueo'), ('CORREGIR_EXPRESS', 'Corrección Express'), ('DECLARAR_DEPOSITO', 'Declarar Depósito'), ('CONFIRMAR_DEPOSITO', 'Confirmar Depósito'), ('REVISAR_ARQUEO', 'Revisar Arqueo')], max_length=30)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('datos_extra', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Acción de Caja',
                'verbose_name_plural': 'Logs de Acciones de Caja',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveIndex(
            model_name='cambiodevolucion',
            name='idx_cambio_fuera_plazo',
        ),
        migrations.RemoveIndex(
            model_name='cambiodevolucion',
            name='idx_cambio_cross_branch',
        ),
        migrations.RemoveIndex(
            model_name='cambiodevolucion',
            name='idx_cambio_tipo_especial',
        ),
        migrations.RemoveIndex(
            model_name='cambiodevolucion',
            name='idx_cambio_revision_ger',
        ),
        migrations.RemoveIndex(
            model_name='registroautorizacion',
            name='idx_auth_cross_branch',
        ),
        migrations.RemoveIndex(
            model_name='registroautorizacion',
            name='idx_auth_revision',
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='categoria_diferencia',
            field=models.CharField(blank=True, choices=[('ERROR_VUELTO', 'Error de vuelto'), ('BILLETE_FALSO', 'Billete falso'), ('DIFERENCIA_POS', 'Diferencia POS'), ('FALTANTE_SIN_EXPLICAR', 'Faltante sin explicar'), ('SOBRANTE', 'Sobrante'), ('OTRO', 'Otro')], help_text='Categoría de la diferencia (obligatorio si >$5,000)', max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='fondo_fijo_snapshot',
            field=models.IntegerField(default=0, help_text='Snapshot del fondo fijo de caja chica al momento del cierre'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='modo_conteo',
            field=models.CharField(choices=[('DETALLADO', 'Detallado'), ('EXPRESS', 'Express')], default='DETALLADO', help_text='Modo usado para el conteo físico', max_length=10),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='requiere_revision_express',
            field=models.BooleanField(default=False, help_text='True si el conteo fue en modo express (revisión recomendada)'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='timestamp_conteo_fisico',
            field=models.DateTimeField(blank=True, help_text='Momento exacto en que se guardó el conteo físico', null=True),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='cantidad_sobrante',
            field=models.IntegerField(default=0, help_text='Cantidad que llegó de más respecto a lo esperado'),
        ),
        migrations.AddField(
            model_name='sucursal',
            name='fondo_fijo_caja',
            field=models.IntegerField(default=0, help_text='Monto fijo que siempre permanece en caja (pesos). No se deposita.', verbose_name='Fondo Fijo Caja Chica'),
        ),
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='autorizado_por_usuario',
            field=models.ForeignKey(blank=True, help_text='Supervisor que autorizó la operación (distinto de aprobado_por)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cambios_autorizados_excepcion', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='concepto_descripcion',
            field=models.TextField(blank=True, help_text='Descripción del concepto del cambio (para datos migrados)', null=True),
        ),
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='es_cambio_concepto',
            field=models.BooleanField(default=False, help_text='Si es un cambio por concepto (sin mapeo de productos específicos)'),
        ),
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='requiere_revision_gerencial',
            field=models.BooleanField(default=False, help_text='Si requiere revisión de gerencia (auto-escalamiento)'),
        ),
        migrations.AlterField(
            model_name='cambiodevolucion',
            name='tipo_cambio_especial',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FUERA_PLAZO', 'Fuera de Plazo'), ('CONCEPTO', 'Por Concepto'), ('LEGACY', 'Legacy')], default='NORMAL', help_text='Tipo especial de cambio: normal, fuera de plazo, por concepto, legacy', max_length=20),
        ),
        migrations.AlterField(
            model_name='cambiodevoluciondetalle',
            name='descripcion_concepto',
            field=models.CharField(blank=True, help_text='Descripción del ítem por concepto (reemplaza producto_original)', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cambiodevoluciondetalle',
            name='es_linea_concepto',
            field=models.BooleanField(default=False, help_text='Si es una línea de cambio por concepto (sin producto específico)'),
        ),
        migrations.AlterField(
            model_name='codigoautorizaciondinamico',
            name='operacion_asociada',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Operación asociada (para códigos por transacción)'),
        ),
        migrations.AlterField(
            model_name='dte',
            name='estado_dte',
            field=models.CharField(choices=[('EMITIDO', 'Emitido'), ('ACEPTADO', 'Aceptado'), ('RECEPCIONADO_COMPLETO', 'Recepcionado Completo'), ('RECEPCIONADO_PARCIAL', 'Recepcionado Parcial'), ('RECEPCIONADO_SOBRANTE', 'Recepcionado con Sobrantes'), ('EN_REGULARIZACION', 'En Regularización'), ('RECHAZADO', 'Rechazado'), ('ANULADO', 'Anulado'), ('CANCELADO', 'Cancelado')], max_length=30),
        ),
        migrations.AlterField(
            model_name='movimientos_producto',
            name='concepto',
            field=models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('INGRESO_MANUAL', 'Ingreso Manual'), ('RECEPCION_COMPRA', 'Recepción de Compra'), ('REPOSICION_STOCK', 'Reposición de Stock'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('TRASPASO_ENTRADA', 'Traspaso Entrada'), ('REGULARIZACION_TRASPASO', 'Regularización de Traspaso'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('DONACION_RECIBIDA', 'Donación Recibida'), ('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('TRASPASO_SALIDA', 'Traspaso Salida'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('PERDIDA_ROBO', 'Pérdida por Robo'), ('PERDIDA_DETERIORO', 'Pérdida por Deterioro'), ('DONACION_ENTREGADA', 'Donación Entregada'), ('DEVOLUCION_PROVEEDOR', 'Devolución a Proveedor'), ('TRASPASO_SUCURSAL', 'Traspaso entre Sucursales'), ('TRASPASO_BODEGA', 'Traspaso a Bodega'), ('TRASPASO_VITRINA', 'Traspaso a Vitrina'), ('CAMBIO_PRODUCTO_SALIDA', 'Cambio de Producto (Salida)'), ('CAMBIO_PRODUCTO_ENTRADA', 'Cambio de Producto (Entrada)'), ('CORRECCION_STOCK', 'Corrección de Stock'), ('ANULACION_REGULARIZACION', 'Anulación de Regularización'), ('ANULACION', 'Anulación de DTE'), ('CANCELACION', 'Cancelación de DTE'), ('AJUSTE_INVENTARIO_ENTRADA', 'Ajuste Inventario - Entrada (Sobrante)'), ('AJUSTE_INVENTARIO_SALIDA', 'Ajuste Inventario - Salida (Faltante)'), ('DESPACHO_COTIZACION', 'Despacho de Cotización'), ('RECEPCION_SOBRANTE', 'Recepción de Sobrante (Pendiente Decisión)'), ('SOBRANTE_INGRESO', 'Sobrante Aceptado - Ingreso a Inventario'), ('SOBRANTE_DEVUELTO', 'Sobrante Devuelto a Origen'), ('DEVOLUCION_NC', 'Devolución por Nota de Crédito')], default='INGRESO_INICIAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='productos_recepcionados',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente de Recepción'), ('RECEPCIONADO_OK', 'Recepcionado OK'), ('RECEPCIONADO_PARCIAL', 'Recepcionado Parcial'), ('RECEPCIONADO_DANADO', 'Recepcionado con Daños'), ('FALTANTE', 'Faltante'), ('EN_REGULARIZACION', 'En Regularización'), ('EN_SOLICITUD_REGULARIZACION', 'En Solicitud de Regularización'), ('REGULARIZADO', 'Regularizado'), ('RECEPCIONADO_SOBRANTE', 'Recepcionado con Sobrantes'), ('SOBRANTE_PENDIENTE', 'Sobrante Pendiente de Decisión')], default='RECEPCIONADO_OK', help_text='Estado de la recepción', max_length=30),
        ),
        migrations.AlterField(
            model_name='solicitud_regularizacion',
            name='tipo_problema',
            field=models.CharField(choices=[('FALTANTE', 'Faltante'), ('DANADO', 'Dañado'), ('PARCIAL', 'Recepción Parcial'), ('INCORRECTO', 'Producto Incorrecto'), ('SOBRANTE', 'Sobrante')], help_text='Tipo de problema detectado', max_length=50),
        ),
        migrations.AlterField(
            model_name='solicitud_regularizacion',
            name='tipo_solucion_aprobada',
            field=models.CharField(blank=True, choices=[('NOTA_CREDITO', 'Nota de Crédito'), ('REENVIO', 'Reenvío del mismo producto'), ('CAMBIO_PRODUCTO', 'Cambio por otro producto'), ('AJUSTE_CANTIDAD', 'Ajustar solo cantidad'), ('DEVOLUCION_SOBRANTE', 'Devolución de Sobrante a Origen'), ('ACEPTAR_SOBRANTE', 'Aceptar Sobrante en Inventario')], help_text='Tipo de solución finalmente aprobada (puede diferir de la solicitada)', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='solicitud_regularizacion',
            name='tipo_solucion_solicitada',
            field=models.CharField(choices=[('NOTA_CREDITO', 'Nota de Crédito'), ('REENVIO', 'Reenvío del mismo producto'), ('CAMBIO_PRODUCTO', 'Cambio por otro producto'), ('AJUSTE_CANTIDAD', 'Ajustar solo cantidad'), ('DEVOLUCION_SOBRANTE', 'Devolución de Sobrante a Origen'), ('ACEPTAR_SOBRANTE', 'Aceptar Sobrante en Inventario')], help_text='Tipo de solución que solicita el receptor', max_length=50),
        ),
        migrations.AddField(
            model_name='logaccioncaja',
            name='arqueo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to='app.arqueocaja'),
        ),
        migrations.AddField(
            model_name='logaccioncaja',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_caja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='logaccioncaja',
            index=models.Index(fields=['usuario', 'timestamp'], name='app_logacci_usuario_f9a9d7_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccioncaja',
            index=models.Index(fields=['accion', 'timestamp'], name='app_logacci_accion_d5fe36_idx'),
        ),
        migrations.AddIndex(
            model_name='logaccioncaja',
            index=models.Index(fields=['arqueo', 'timestamp'], name='app_logacci_arqueo__32e803_idx'),
        ),
    ]
