# Generated by Django 4.2.2 on 2026-04-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0131_movimientos_fecha_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciondte',
            name='tipo',
            field=models.CharField(choices=[('DTE_RECIBIDO', 'Nuevo DTE Recibido'), ('ACTUALIZACION_PENDIENTE', 'Actualización de Stock Pendiente'), ('RECEPCION_COMPLETADA', 'Recepción Completada'), ('REGULARIZACION_REQUERIDA', 'Regularización Requerida'), ('RECHAZO_DTE', 'DTE Rechazado por Destino'), ('VENCIMIENTO_PROXIMO', 'Vencimiento Próximo')], default='DTE_RECIBIDO', max_length=30),
        ),
    ]
