# Generated by Django 4.2.2 on 2026-04-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0133_correccion_recepcion_notificacion_tipo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='codigoautorizaciondinamico',
            name='app_codigoa_codigo_a1a19a_idx',
        ),
        migrations.AlterField(
            model_name='codigoautorizaciondinamico',
            name='codigo',
            field=models.CharField(db_index=True, max_length=6, verbose_name='Código de 6 dígitos'),
        ),
        migrations.AddIndex(
            model_name='codigoautorizaciondinamico',
            index=models.Index(fields=['codigo', 'activo', 'usado'], name='app_codigoa_codigo_3c103b_idx'),
        ),
        migrations.AddIndex(
            model_name='codigoautorizaciondinamico',
            index=models.Index(fields=['generado_por', 'activo', 'usado'], name='app_codigoa_generad_2f9c7a_idx'),
        ),
    ]
