# Generated by Django 4.2.2 on 2026-04-17 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0136_producto_timestamps'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dte',
            options={'ordering': ['-fecha_emision', '-id']},
        ),
        migrations.AddIndex(
            model_name='depositobancario',
            index=models.Index(fields=['arqueo', 'verificado'], name='depbanc_arq_verif_idx'),
        ),
        migrations.AddIndex(
            model_name='depositobancario',
            index=models.Index(fields=['arqueo', 'tipo_medio', 'verificado'], name='depbanc_arq_med_ver_idx'),
        ),
        migrations.AddIndex(
            model_name='depositobancario',
            index=models.Index(fields=['verificado', 'fecha_deposito'], name='depbanc_ver_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='dte',
            index=models.Index(fields=['sucursal', '-fecha_emision'], name='dte_suc_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='dte',
            index=models.Index(fields=['sucursal', 'tipo_transaccion', '-fecha_emision'], name='dte_suc_trans_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='dte',
            index=models.Index(fields=['sucursal', 'estado_dte', '-fecha_emision'], name='dte_suc_estado_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='dte',
            index=models.Index(fields=['sucursal', 'tipo_documento', '-fecha_emision'], name='dte_suc_tipo_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='dte',
            index=models.Index(fields=['receptor'], name='dte_receptor_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sucursal', '-fecha'], name='ticket_suc_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sucursal', '-created_at'], name='ticket_suc_created_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sucursal', 'estado', '-fecha'], name='ticket_suc_est_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['sucursal', 'modulo_origen', 'estado'], name='ticket_suc_mod_est_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['vendedor', '-fecha'], name='ticket_vend_fecha_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketdetallepago',
            index=models.Index(fields=['ticket', 'metodo_pago'], name='ticketpago_tic_met_idx'),
        ),
        migrations.AddIndex(
            model_name='ticketdetallepago',
            index=models.Index(fields=['metodo_pago'], name='ticketpago_metodo_idx'),
        ),
    ]
