# Generated by Django 4.2.2 on 2026-04-17 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0137_indices_ventas_listados'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='cache_depositos_actualizado',
            field=models.DateTimeField(blank=True, help_text='Última vez que el signal recalculó los contadores', null=True),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cache_depositos_confirmados',
            field=models.IntegerField(default=0, help_text='Cantidad de depósitos con verificado=True'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cache_depositos_declarados',
            field=models.IntegerField(default=0, help_text='Cantidad de depósitos con monto_declarado > 0'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cache_depositos_pendientes',
            field=models.IntegerField(default=0, help_text='Cantidad de depósitos verificado=False y monto_declarado > 0'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cache_total_dep_cheque_verif',
            field=models.IntegerField(default=0, help_text='Total depósitos cheque verificados (monto_confirmado)'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cache_total_dep_efectivo_verif',
            field=models.IntegerField(default=0, help_text='Total depósitos efectivo verificados (monto_confirmado)'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cache_total_dep_verificado',
            field=models.IntegerField(default=0, help_text='Suma de `depositos.monto_confirmado` verificados'),
        ),
        migrations.AddField(
            model_name='arqueocaja',
            name='cache_total_depositos',
            field=models.IntegerField(default=0, help_text='Suma de `depositos.monto` — actualizado por signal'),
        ),
    ]
