# Generated by Django 4.2.2 on 2026-04-20 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0141_compras_producto_sucursal_destino'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurvaDistribucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('genero', models.ForeignKey(blank=True, help_text='Opcional. Misma lógica que marca pero para género/sexo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curvas_distribucion_por_genero', to='app.atributoopcion')),
                ('guia_talla', models.ForeignKey(blank=True, help_text='Guía de tallas usada como base (opcional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curvas_distribucion', to='app.guiatalla')),
                ('marca', models.ForeignKey(blank=True, help_text='Opcional. Si se indica, la curva aparecerá como sugerencia al distribuir productos de esta marca.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='curvas_distribucion_por_marca', to='app.atributoopcion')),
            ],
            options={
                'verbose_name': 'Curva de distribución de tallas',
                'verbose_name_plural': 'Curvas de distribución de tallas',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='compras_producto_talla',
            name='pendiente_distribuir',
            field=models.BooleanField(default=False, help_text='True cuando la fila es el total provisorio de una compra importada sin desglose de tallas. Al aplicar la guía de tallas esta fila se reemplaza por filas reales.', verbose_name='Pendiente de distribuir por guía'),
        ),
        migrations.CreateModel(
            name='CurvaDistribucionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talla', models.CharField(max_length=50)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('orden', models.IntegerField(default=0)),
                ('curva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.curvadistribucion')),
            ],
            options={
                'ordering': ['orden', 'id'],
                'unique_together': {('curva', 'talla')},
            },
        ),
    ]
