# Generated by Django 4.2.2 on 2026-04-21 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0142_curvadistribucion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendienteDespacho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(default=0)),
                ('cantidad_despachada', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PARCIAL', 'Parcialmente despachado'), ('DESPACHADO', 'Despachado'), ('ANULADO', 'Anulado')], default='PENDIENTE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('compra_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendientes_despacho', to='app.compras_producto')),
                ('dte_origen', models.ForeignKey(blank=True, help_text='DTE de la compra que generó este pendiente (trazabilidad).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pendientes_despacho_origen', to='app.dte')),
                ('producto_talla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pendientes_despacho', to='app.producto_talla')),
                ('sucursal_destino', models.ForeignKey(help_text='Sucursal a la que hay que despachar la mercadería.', on_delete=django.db.models.deletion.CASCADE, related_name='despachos_destino_pendientes', to='app.sucursal')),
                ('sucursal_origen', models.ForeignKey(help_text='Sucursal donde vive el stock (casi siempre EDEL / casa matriz).', on_delete=django.db.models.deletion.CASCADE, related_name='despachos_origen_pendientes', to='app.sucursal')),
            ],
            options={
                'verbose_name': 'Pendiente de Despacho',
                'verbose_name_plural': 'Pendientes de Despacho',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sucursal_destino', 'estado'], name='app_pendien_sucursa_71796a_idx'), models.Index(fields=['producto_talla', 'estado'], name='app_pendien_product_d4756b_idx'), models.Index(fields=['estado', '-created_at'], name='app_pendien_estado_88c589_idx')],
            },
        ),
    ]
