# Generated by Django 4.2.2 on 2026-04-22 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0143_pendientedespacho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dte',
            name='tipo_documento',
            field=models.CharField(choices=[('FACTURA ELECTRONICA', 'Factura Electrónica'), ('BOLETA ELECTRONICA', 'Boleta Electrónica'), ('BOLETA PAPEL', 'Boleta Papel'), ('GUIA', 'Guía de Despacho'), ('NOTA DE PEDIDO', 'Nota de Pedido'), ('NOTA DE CREDITO', 'Nota de Crédito'), ('NOTA DE DEBITO', 'Nota de Débito'), ('FACTURA EXENTA', 'Factura Exenta'), ('COTIZACION', 'Cotización'), ('COMPRA', 'Compra'), ('TICKET', 'Ticket'), ('TICKET CAMBIO', 'Ticket de Cambio'), ('TRASPASO', 'Traspaso'), ('AJUSTE', 'Ajuste de Inventario'), ('AJUSTE TRASPASO', 'Ajuste de Traspaso (emisor)')], max_length=20),
        ),
    ]
