# Generated by Django 4.2.2 on 2026-05-12 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0154_rename_fecha_cheque_to_fecha_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='compras',
            name='es_historica',
            field=models.BooleanField(default=False, help_text='True = compra cargada retroactivamente, solo para reportes (no toca stock).'),
        ),
        migrations.AddField(
            model_name='productos_recepcionados',
            name='es_historica',
            field=models.BooleanField(default=False, help_text='True = recepción de compra histórica vinculada retroactivamente, sin movimiento de stock.'),
        ),
        migrations.AlterField(
            model_name='dte_detalle_pago',
            name='fecha_pago',
            field=models.DateField(blank=True, help_text='Fecha en que se realizó el pago. Aplica a todos los métodos. Permite fechas pasadas (retroactivos) y futuras (cheques a fecha).', null=True),
        ),
    ]
