# Generated by Django 4.2.2 on 2026-06-02 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0157_opcion_menu_integraciones_ecommerce'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='credencialesecommerce',
            new_name='app_credenc_activo_626f55_idx',
            old_name='app_credenc_activo_idx',
        ),
        migrations.RenameIndex(
            model_name='credencialesecommerce',
            new_name='app_credenc_tipo_c0f943_idx',
            old_name='app_credenc_tipo_idx',
        ),
        migrations.RenameIndex(
            model_name='fotoportadaarticulo',
            new_name='app_fotopor_articul_ff5043_idx',
            old_name='app_fotopor_art_prin_idx',
        ),
        migrations.AddField(
            model_name='pedidoecommerce',
            name='numero_pedido_origen',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Correlativo interno del pedido en AllConnected (ej. MP-000123)', max_length=50, verbose_name='N° Pedido (AllConnected)'),
        ),
    ]
