# Generated by Django 4.2.2 on 2026-06-06 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0160_cambiodevolucion_condonacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='dte',
            name='comprobante_enviado_a',
            field=models.CharField(blank=True, help_text='Correo al que se envió el último comprobante de pago', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dte',
            name='comprobante_enviado_en',
            field=models.DateTimeField(blank=True, help_text='Fecha/hora del último envío del comprobante de pago al proveedor por correo', null=True),
        ),
    ]
