# Generated by Django 4.2.2 on 2026-06-13 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0162_pedidoecommerce_impuestos_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidoecommerce',
            name='canal_origen',
            field=models.CharField(choices=[('SHOPIFY', 'Shopify'), ('PARIS', 'Paris'), ('RIPLEY', 'Ripley'), ('WALMART', 'Walmart'), ('REALSPORT', 'Realsport'), ('PAOLA', 'Paola'), ('OTRO', 'Otro')], db_index=True, max_length=20, verbose_name='Canal origen'),
        ),
    ]
