# Generated by Django 4.2.2 on 2026-06-15 22:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0163_alter_pedidoecommerce_canal_origen'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_puntos', models.IntegerField(db_index=True, default=0, help_text='Saldo disponible (cache; derivado del ledger)')),
                ('activa', models.BooleanField(default=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_puntos', to='app.cliente')),
            ],
            options={
                'verbose_name': 'Cuenta de Puntos',
                'verbose_name_plural': 'Cuentas de Puntos',
                'ordering': ['-saldo_puntos'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='app.cliente'),
        ),
        migrations.AlterField(
            model_name='pagocambiodevolucion',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CREDITO_EXTERNO', 'Crédito Externo'), ('CONVENIO', 'Convenio'), ('GIFTCARD', 'Gift Card'), ('MULTIPLE', 'Pagos Combinados')], max_length=50),
        ),
        migrations.AlterField(
            model_name='pagocreditotrabajador',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CREDITO_EXTERNO', 'Crédito Externo'), ('CONVENIO', 'Convenio'), ('GIFTCARD', 'Gift Card'), ('MULTIPLE', 'Pagos Combinados')], default='EFECTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CREDITO_EXTERNO', 'Crédito Externo'), ('CONVENIO', 'Convenio'), ('GIFTCARD', 'Gift Card'), ('MULTIPLE', 'Pagos Combinados')], default='EFECTIVO', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketdetallepago',
            name='metodo_pago',
            field=models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('TARJETA_DEBITO', 'Tarjeta Débito'), ('TARJETA_CREDITO', 'Tarjeta Crédito'), ('TRANSFERENCIA', 'Transferencia'), ('CHEQUE', 'Cheque'), ('OTRO', 'Otro'), ('TBK_POS_INTEGRADO', 'Transbank POS Integrado'), ('TBK_MANUAL', 'Transbank Manual'), ('TBK_DEBITO_POS', 'Transbank Débito POS'), ('TBK_CREDITO_POS', 'Transbank Crédito POS'), ('TBK_PREPAGO_POS', 'Transbank Prepago POS'), ('TARJETA_COMERCIAL', 'Tarjeta Comercial'), ('VENTA_INTERNET', 'Venta por Internet'), ('ORDEN_COMPRA', 'Orden de Compra'), ('CREDITO_TRABAJADOR', 'Crédito Trabajador'), ('CREDITO_EXTERNO', 'Crédito Externo'), ('CONVENIO', 'Convenio'), ('GIFTCARD', 'Gift Card'), ('MULTIPLE', 'Pagos Combinados')], max_length=50),
        ),
        migrations.CreateModel(
            name='ProgramaFidelizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Programa de Puntos', max_length=100)),
                ('puntos_por_monto', models.IntegerField(default=1, help_text='Puntos otorgados por cada `monto_base_acumulacion` pesos')),
                ('monto_base_acumulacion', models.IntegerField(default=1000, help_text='Monto en pesos que otorga `puntos_por_monto` puntos')),
                ('acumula_sobre', models.CharField(choices=[('TOTAL', 'Total de la venta (con impuestos)'), ('NETO', 'Neto (sin impuestos)')], default='TOTAL', max_length=10)),
                ('redondeo', models.CharField(choices=[('FLOOR', 'Hacia abajo (trunca)'), ('ROUND', 'Al más cercano'), ('CEIL', 'Hacia arriba')], default='FLOOR', max_length=10)),
                ('valor_punto_en_pesos', models.IntegerField(default=10, help_text='Cuántos pesos de descuento vale 1 punto al canjear')),
                ('minimo_canje_puntos', models.IntegerField(default=50, help_text='Puntos mínimos para poder canjear')),
                ('vigencia_dias', models.IntegerField(default=365, help_text='Días hasta que un lote de puntos expira')),
                ('puntos_bienvenida', models.IntegerField(default=20, help_text='Puntos al crear la cuenta del cliente (0 = sin bono)')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='programas_fidelizacion_modificados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Programa de Fidelización',
                'verbose_name_plural': 'Programas de Fidelización',
                'ordering': ['-activo', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, help_text='Código legible único (GC-XXXX-XXXX-XXXX)', max_length=30, unique=True)),
                ('pin', models.CharField(blank=True, help_text='PIN opcional de redención (no obligatorio para arrancar)', max_length=8, null=True)),
                ('saldo_inicial', models.IntegerField(help_text='Monto con que se emitió')),
                ('saldo_actual', models.IntegerField(db_index=True, default=0, help_text='Saldo disponible (cache; derivado del ledger)')),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('AGOTADA', 'Agotada'), ('ANULADA', 'Anulada'), ('VENCIDA', 'Vencida'), ('BLOQUEADA', 'Bloqueada')], db_index=True, default='ACTIVA', max_length=20)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField(blank=True, help_text='Fecha límite de uso (null = sin vencimiento)', null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, help_text='Cliente comprador / titular (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards', to='app.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards_creadas', to=settings.AUTH_USER_MODEL)),
                ('sucursal_emision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards_emitidas', to='app.sucursal')),
                ('ticket_emision', models.ForeignKey(blank=True, help_text='Venta en la que se vendió esta giftcard', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards_vendidas', to='app.ticket')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards_modificadas', to=settings.AUTH_USER_MODEL)),
                ('vendedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='giftcards_vendidas', to='app.vendedor')),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ACUMULACION', 'Acumulación por compra'), ('CANJE', 'Canje (descuento)'), ('EXPIRACION', 'Expiración de puntos'), ('AJUSTE', 'Ajuste manual'), ('REVERSA', 'Reversa (devolución/anulación de venta)'), ('BIENVENIDA', 'Bono de bienvenida')], max_length=20)),
                ('puntos', models.IntegerField(help_text='Positivo = acumula/bienvenida/reversa+; negativo = canje/expira')),
                ('saldo_resultante', models.IntegerField(help_text='Saldo de la cuenta tras aplicar este movimiento')),
                ('fecha_expiracion', models.DateField(blank=True, db_index=True, help_text='Solo en lotes (ACUMULACION/BIENVENIDA): cuándo expira', null=True)),
                ('puntos_consumidos_del_lote', models.IntegerField(default=0, help_text='Cuánto del lote ya se gastó/expiró (solo en lotes)')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.cuentapuntos')),
                ('lote_origen', models.ForeignKey(blank=True, help_text='Lote que consume este CANJE/EXPIRACION', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumos', to='app.movimientopuntos')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_puntos', to='app.sucursal')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_puntos', to='app.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_puntos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Puntos',
                'verbose_name_plural': 'Movimientos de Puntos',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['cuenta', 'fecha'], name='app_movimie_cuenta__fa3873_idx'), models.Index(fields=['cuenta', 'fecha_expiracion'], name='app_movimie_cuenta__f3d064_idx'), models.Index(fields=['ticket'], name='app_movimie_ticket__e603a3_idx'), models.Index(fields=['idempotency_key'], name='app_movimie_idempot_68beaa_idx')],
            },
        ),
        migrations.CreateModel(
            name='MovimientoGiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('EMISION', 'Emisión'), ('CARGA', 'Carga / Recarga'), ('CONSUMO', 'Consumo (pago de venta)'), ('ANULACION', 'Anulación'), ('AJUSTE', 'Ajuste manual'), ('REVERSA', 'Reversa (devolución/anulación de venta)')], max_length=20)),
                ('monto', models.IntegerField(help_text='Positivo = carga/emisión/reversa; negativo = consumo/anulación')),
                ('saldo_resultante', models.IntegerField(help_text='Saldo de la giftcard tras aplicar este movimiento')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('giftcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app.giftcard')),
                ('pago_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_giftcard', to='app.ticketdetallepago')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_giftcard', to='app.sucursal')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_giftcard', to='app.ticket')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_giftcard', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Gift Card',
                'verbose_name_plural': 'Movimientos de Gift Card',
                'ordering': ['fecha'],
                'indexes': [models.Index(fields=['giftcard', 'fecha'], name='app_movimie_giftcar_2f6792_idx'), models.Index(fields=['ticket'], name='app_movimie_ticket__a29a0e_idx'), models.Index(fields=['idempotency_key'], name='app_movimie_idempot_7cc187_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['codigo'], name='app_giftcar_codigo_e9a73a_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='app_giftcar_estado_b5921b_idx'),
        ),
        migrations.AddIndex(
            model_name='giftcard',
            index=models.Index(fields=['cliente', 'estado'], name='app_giftcar_cliente_ca8bcc_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentapuntos',
            index=models.Index(fields=['saldo_puntos'], name='app_cuentap_saldo_p_4f7e44_idx'),
        ),
    ]
