# Generated by Django 4.2.2 on 2026-06-17 17:18

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0166_dte_referencia_comercial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuentaClienteApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_verificado', models.BooleanField(default=False)),
                ('celular_verificado', models.BooleanField(default=False)),
                ('activa', models.BooleanField(db_index=True, default=True)),
                ('ultimo_login', models.DateTimeField(blank=True, null=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intentos_fallidos', models.IntegerField(default=0)),
                ('bloqueada_hasta', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_app', to='app.cliente')),
            ],
            options={
                'verbose_name': 'Cuenta de Cliente (App)',
                'verbose_name_plural': 'Cuentas de Cliente (App)',
                'ordering': ['-fecha_alta'],
            },
        ),
        migrations.AlterField(
            model_name='dte',
            name='tipo_precio_externo',
            field=models.CharField(blank=True, choices=[('COSTO', 'Solo Costo'), ('SOBREPRECIO', 'Costo + Sobreprecio'), ('CUSTOM_PCT', 'Porcentaje Custom'), ('PRECIO_VENTA', 'Precio de Venta')], help_text='Modo de precio usado en despacho externo', max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='RefreshTokenClienteApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token_hash', models.CharField(max_length=128, unique=True)),
                ('familia_id', models.UUIDField(db_index=True, default=uuid.uuid4, help_text='Todos los tokens de una misma sesión comparten familia')),
                ('revocado', models.BooleanField(default=False)),
                ('utilizado', models.BooleanField(default=False, help_text='True si ya fue usado para generar un nuevo token')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='app.cuentaclienteapp')),
            ],
            options={
                'verbose_name': 'Refresh Token Cliente (App)',
                'verbose_name_plural': 'Refresh Tokens Cliente (App)',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['familia_id'], name='app_refresh_familia_eb03cb_idx'), models.Index(fields=['token_hash'], name='app_refresh_token_h_bb8812_idx'), models.Index(fields=['expires_at'], name='app_refresh_expires_dc31c2_idx')],
            },
        ),
        migrations.CreateModel(
            name='CodigoOTPCliente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo_hash', models.CharField(db_index=True, max_length=64)),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('SMS', 'SMS')], default='EMAIL', max_length=10)),
                ('destino', models.CharField(help_text='Email/celular al que se envió (auditoría)', max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('intentos', models.IntegerField(default=0)),
                ('usado', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps_app', to='app.cliente')),
            ],
            options={
                'verbose_name': 'Código OTP de Cliente',
                'verbose_name_plural': 'Códigos OTP de Cliente',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['cliente', 'usado', 'expires_at'], name='app_codigoo_cliente_902f1c_idx'), models.Index(fields=['codigo_hash'], name='app_codigoo_codigo__0bcb9b_idx')],
            },
        ),
    ]
