# Generated by Django 4.2.2 on 2026-06-17 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0168_giftcard_tipo_tarjeta_codigo_fisico'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReservaPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos_reservados', models.IntegerField()),
                ('valor_pesos', models.IntegerField(help_text='Valor en pesos de los puntos reservados (snapshot al reservar)')),
                ('tienda', models.CharField(help_text='Código de la tienda/ecommerce destino (realsport/paola)', max_length=20)),
                ('codigo_cupon', models.CharField(blank=True, db_index=True, help_text='Código del cupón creado en el ecommerce (PTS-<id>)', max_length=40, null=True, unique=True)),
                ('estado', models.CharField(choices=[('RESERVADA', 'Reservada'), ('CONFIRMADA', 'Confirmada'), ('LIBERADA', 'Liberada'), ('EXPIRADA', 'Expirada')], db_index=True, default='RESERVADA', max_length=12)),
                ('puntos_consumidos', models.IntegerField(default=0, help_text='Puntos realmente debitados al confirmar (por el descuento real)')),
                ('order_number', models.CharField(blank=True, default='', help_text='Número del pedido del ecommerce que usó la reserva', max_length=80)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas_puntos', to='app.cliente')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='app.cuentapuntos')),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas_puntos', to='app.empresa')),
            ],
            options={
                'verbose_name': 'Reserva de Puntos',
                'verbose_name_plural': 'Reservas de Puntos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', 'expira_en'], name='app_reserva_estado_ee89f4_idx'), models.Index(fields=['cuenta', 'estado'], name='app_reserva_cuenta__346a02_idx')],
            },
        ),
    ]
