# Generated by Django 4.2.2 on 2026-06-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0169_reservapuntos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoecommerce',
            name='coupon_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Código de cupón del pedido. PTS-<id> = cupón de puntos de la app móvil.', max_length=50, verbose_name='Cupón'),
        ),
        migrations.AddField(
            model_name='pedidoecommerce',
            name='from_app',
            field=models.BooleanField(db_index=True, default=False, help_text='El pedido se originó en la app móvil de fidelización (acumula puntos por la parte en dinero).', verbose_name='Compra desde app'),
        ),
    ]
