# Generated by Django 4.2.2 on 2026-06-18 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0170_pedidoecommerce_coupon_code_pedidoecommerce_from_app'),
    ]

    operations = [
        migrations.CreateModel(
            name='CanjeVale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(help_text='Puntos que canjea el vale')),
                ('valor_pesos', models.IntegerField(help_text='Valor en pesos del vale (snapshot al generarse)')),
                ('codigo', models.CharField(db_index=True, help_text='Código de un solo uso que el cliente presenta en tienda', max_length=24, unique=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de canje'), ('CANJEADO', 'Canjeado'), ('EXPIRADO', 'Expirado'), ('ANULADO', 'Anulado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('canjeado_en', models.DateTimeField(blank=True, null=True)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_canje', to='app.cliente')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vales_canje', to='app.cuentapuntos')),
                ('empresa', models.ForeignKey(blank=True, help_text='Empresa/holding donde puede canjearse (opcional: global si vacío)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales_canje', to='app.empresa')),
                ('sucursal_canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales_canjeados', to='app.sucursal')),
                ('ticket', models.ForeignKey(blank=True, help_text='Venta donde se aplicó el vale', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales_canje', to='app.ticket')),
                ('usuario_canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vales_canjeados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vale de Canje',
                'verbose_name_plural': 'Vales de Canje',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', 'expira_en'], name='app_canjeva_estado_17d0cd_idx'), models.Index(fields=['cuenta', 'estado'], name='app_canjeva_cuenta__d440d5_idx')],
            },
        ),
    ]
