# Generated by Django 4.2.2 on 2026-06-23 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0172_programafidelizacion_punto_peso_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentapuntos',
            name='anio_ultimo_bono_cumpleanos',
            field=models.IntegerField(blank=True, help_text='Año en que se otorgó el último bono de cumpleaños (evita duplicar)', null=True),
        ),
        migrations.AddField(
            model_name='cuentapuntos',
            name='gasto_12_meses',
            field=models.IntegerField(default=0, help_text='Cache de gasto acumulado en los últimos 12 meses (pesos)'),
        ),
        migrations.AddField(
            model_name='cuentapuntos',
            name='nivel',
            field=models.CharField(choices=[('PLATA', 'Plata'), ('ORO', 'Oro'), ('PLATINO', 'Platino')], db_index=True, default='PLATA', help_text='Nivel del cliente (Plata/Oro/Platino) según gasto 12 meses', max_length=10),
        ),
        migrations.AddField(
            model_name='cuentapuntos',
            name='nivel_actualizado',
            field=models.DateTimeField(blank=True, help_text='Última vez que se recalculó el nivel', null=True),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='incremento_canje',
            field=models.IntegerField(default=100, help_text='El canje debe ser múltiplo de este valor (0 = sin restricción)'),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='puntos_cumpleanos',
            field=models.IntegerField(default=3000, help_text='Puntos de regalo en el mes de cumpleaños (0 = sin bono)'),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='tasa_oro',
            field=models.DecimalField(decimal_places=2, default=4.0, help_text='% de cashback en puntos para nivel Oro', max_digits=5),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='tasa_plata',
            field=models.DecimalField(decimal_places=2, default=3.0, help_text='% de cashback en puntos para nivel Plata', max_digits=5),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='tasa_platino',
            field=models.DecimalField(decimal_places=2, default=5.0, help_text='% de cashback en puntos para nivel Platino', max_digits=5),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='umbral_oro',
            field=models.IntegerField(default=300000, help_text='Gasto acumulado en 12 meses (pesos) para alcanzar nivel Oro'),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='umbral_platino',
            field=models.IntegerField(default=800000, help_text='Gasto acumulado en 12 meses (pesos) para alcanzar nivel Platino'),
        ),
        migrations.AlterField(
            model_name='movimientopuntos',
            name='tipo',
            field=models.CharField(choices=[('ACUMULACION', 'Acumulación por compra'), ('CANJE', 'Canje (descuento)'), ('EXPIRACION', 'Expiración de puntos'), ('AJUSTE', 'Ajuste manual'), ('REVERSA', 'Reversa (devolución/anulación de venta)'), ('BIENVENIDA', 'Bono de bienvenida'), ('CUMPLEANOS', 'Bono de cumpleaños')], max_length=20),
        ),
        migrations.AlterField(
            model_name='programafidelizacion',
            name='puntos_bienvenida',
            field=models.IntegerField(default=3000, help_text='Puntos al crear la cuenta del cliente (0 = sin bono)'),
        ),
    ]
