# Generated by Django 4.2.2 on 2026-06-23 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0173_niveles_fidelizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientopuntos',
            name='canal',
            field=models.CharField(choices=[('POS', 'Caja POS'), ('APP', 'App Móvil'), ('WEB', 'Ecommerce'), ('MANUAL', 'Ajuste Manual'), ('AUTO', 'Automático')], db_index=True, default='POS', help_text='Canal que originó el movimiento (POS/APP/WEB/MANUAL/AUTO)', max_length=10),
        ),
        migrations.AddField(
            model_name='movimientopuntos',
            name='rut_cliente',
            field=models.CharField(blank=True, db_index=True, help_text='RUT denormalizado del cliente (reportes sin join, prueba de presentación)', max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='movimientopuntos',
            index=models.Index(fields=['rut_cliente', 'tipo'], name='app_movimie_rut_cli_8ae98d_idx'),
        ),
    ]
