# Generated by Django 4.2.2 on 2026-06-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0174_rut_canal_movimientos_fidelizacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='arqueocaja',
            name='total_descuento_puntos_teorico',
            field=models.IntegerField(default=0, help_text='Suma de descuentos por puntos canjeados en el período (fidelización)'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='descuento_fidelizacion',
            field=models.IntegerField(blank=True, help_text='Descuento aplicado por canje de vale de puntos (pesos brutos, IVA incluido)', null=True),
        ),
    ]
