# Generated by Django 4.2.2 on 2026-07-02 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0178_correlativo_rango_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DevolucionGarantia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(default='Garantía aprobada', help_text='Motivo de la devolución de dinero')),
                ('estado', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('NC_GENERADA', 'NC Generada'), ('ANULADA', 'Anulada')], default='REGISTRADA', max_length=20)),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('numero_operacion', models.CharField(help_text='DG-<sucursal>-<YYYYMM>-<correlativo>', max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('autorizado_por', models.ForeignKey(help_text='Jefe de local o administrador que ejecutó/autorizó la devolución', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_garantia_autorizadas', to=settings.AUTH_USER_MODEL)),
                ('dte_original', models.ForeignKey(help_text='Boleta/factura original con el producto fallado', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_garantia', to='app.dte')),
                ('nota_credito', models.ForeignKey(blank=True, help_text='Nota de Crédito (DTE 61) generada por esta devolución', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucion_garantia_origen', to='app.dte')),
                ('receptor', models.ForeignKey(help_text='Empresa (cliente real) resuelta/creada por RUT, usada como receptor de la NC', on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_garantia_receptor', to='app.empresa')),
                ('sucursal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones_garantia', to='app.sucursal')),
            ],
            options={
                'verbose_name': 'Devolución por Garantía',
                'verbose_name_plural': 'Devoluciones por Garantía',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DevolucionGarantiaDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.devoluciongarantia')),
                ('dte_producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devoluciones_garantia_detalle', to='app.dte_productos')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución por Garantía',
                'verbose_name_plural': 'Detalles de Devolución por Garantía',
            },
        ),
        migrations.AddIndex(
            model_name='devoluciongarantia',
            index=models.Index(fields=['numero_operacion'], name='app_devoluc_numero__67dfad_idx'),
        ),
        migrations.AddIndex(
            model_name='devoluciongarantia',
            index=models.Index(fields=['sucursal', '-created_at'], name='app_devoluc_sucursa_a11ee6_idx'),
        ),
        migrations.AddIndex(
            model_name='devoluciongarantia',
            index=models.Index(fields=['estado'], name='app_devoluc_estado_2843e8_idx'),
        ),
    ]
