# Generated by Django 4.2.2 on 2026-07-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0179_devoluciongarantia_devoluciongarantiadetalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='dte_error_detalle',
            field=models.TextField(blank=True, help_text='Traza del último error al intentar generar el DTE', null=True, verbose_name='Detalle Error DTE'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='dte_generacion_fallida',
            field=models.BooleanField(default=False, help_text='True si el ticket quedó PAGADO pero generar_dte_desde_ticket falló; requiere reintento manual', verbose_name='Generación DTE Fallida'),
        ),
    ]
