# Generated by Django 4.2.2 on 2026-07-02 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0180_ticket_dte_error_detalle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='requerimiento',
            name='devolucion_garantia',
            field=models.ForeignKey(blank=True, help_text='Devolucion de dinero generada a partir de este requerimiento (si se uso el puente de UI)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requerimiento_origen', to='app.devoluciongarantia'),
        ),
    ]
