# Generated by Django 4.2.2 on 2026-07-06 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0182_alter_movimientos_producto_concepto'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesafioPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, help_text='Texto que ve el cliente en la app')),
                ('tipo', models.CharField(choices=[('COMPRAS_N', 'Cantidad de compras en el período'), ('MONTO_ACUMULADO', 'Monto comprado en el período ($)')], max_length=20)),
                ('meta_valor', models.IntegerField(help_text='COMPRAS_N: nº de compras · MONTO_ACUMULADO: pesos')),
                ('bono_puntos', models.IntegerField(help_text='Puntos de premio al completar')),
                ('fecha_inicio', models.DateField(db_index=True)),
                ('fecha_fin', models.DateField(db_index=True, help_text='Inclusive')),
                ('nivel_objetivo', models.CharField(blank=True, choices=[('PLATA', 'Plata'), ('ORO', 'Oro'), ('PLATINO', 'Platino')], default='', help_text='Vacío = para todos los niveles', max_length=10)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desafío / Promoción',
                'verbose_name_plural': 'Desafíos / Promociones',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='cuentapuntos',
            name='codigo_referido',
            field=models.CharField(blank=True, help_text='Código para invitar amigos (se genera al primer uso)', max_length=12, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='bono_referido_ahijado',
            field=models.IntegerField(default=2000, help_text='Puntos para el invitado, al concretarse su 1ª compra'),
        ),
        migrations.AddField(
            model_name='programafidelizacion',
            name='bono_referido_padrino',
            field=models.IntegerField(default=2000, help_text='Puntos para quien invita, al concretarse la 1ª compra del invitado (0 = referidos desactivados)'),
        ),
        migrations.AlterField(
            model_name='movimientopuntos',
            name='tipo',
            field=models.CharField(choices=[('ACUMULACION', 'Acumulación por compra'), ('CANJE', 'Canje (descuento)'), ('EXPIRACION', 'Expiración de puntos'), ('AJUSTE', 'Ajuste manual'), ('REVERSA', 'Reversa (devolución/anulación de venta)'), ('BIENVENIDA', 'Bono de bienvenida'), ('CUMPLEANOS', 'Bono de cumpleaños'), ('REFERIDO', 'Bono por referido'), ('DESAFIO', 'Bono por desafío/promoción')], max_length=20),
        ),
        migrations.CreateModel(
            name='Referido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado (espera 1ª compra)'), ('PAGADO', 'Bonos pagados'), ('ANULADO', 'Anulado')], db_index=True, default='REGISTRADO', max_length=12)),
                ('puntos_padrino', models.IntegerField(default=0)),
                ('puntos_ahijado', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pagado_at', models.DateTimeField(blank=True, null=True)),
                ('ahijado', models.OneToOneField(help_text='El invitado: solo puede ser referido una vez', on_delete=django.db.models.deletion.CASCADE, related_name='referido_recibido', to='app.cliente')),
                ('padrino', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referidos_hechos', to='app.cliente')),
            ],
            options={
                'verbose_name': 'Referido',
                'verbose_name_plural': 'Referidos',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['padrino', 'estado'], name='app_referid_padrino_db15cf_idx')],
            },
        ),
        migrations.CreateModel(
            name='DispositivoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(help_text='Token FCM del dispositivo', max_length=512, unique=True)),
                ('plataforma', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=10)),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Última vez que la app refrescó/confirmó el token')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos', to='app.cliente')),
            ],
            options={
                'verbose_name': 'Dispositivo de Cliente (push)',
                'verbose_name_plural': 'Dispositivos de Clientes (push)',
                'ordering': ['-last_seen'],
                'indexes': [models.Index(fields=['cliente', 'activo'], name='app_disposi_cliente_91d8a9_idx')],
            },
        ),
    ]
