# Generated by Django 4.2.2 on 2026-07-23 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0187_backfill_devolucion_garantia_solicitante'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaLiquidacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], db_index=True, default='BORRADOR', max_length=12)),
                ('tipo_regla', models.CharField(choices=[('PORCENTAJE', '% Descuento'), ('PRECIO_FIJO', 'Precio fijo'), ('NXM', 'Promo NxM (2x1, 3x2…)')], max_length=12)),
                ('valor_porcentaje', models.DecimalField(blank=True, decimal_places=2, help_text='% de descuento (1-99) para tipo PORCENTAJE', max_digits=5, null=True)),
                ('valor_precio_fijo', models.IntegerField(blank=True, help_text='Precio fijo para tipo PRECIO_FIJO', null=True)),
                ('nxm_n', models.PositiveSmallIntegerField(blank=True, help_text='NxM: unidades que lleva (2x1 → 2)', null=True)),
                ('nxm_m', models.PositiveSmallIntegerField(blank=True, help_text='NxM: unidades que paga (2x1 → 1)', null=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField(blank=True, help_text='Vacío = sin término automático (cierre manual)', null=True)),
                ('respetar_piso_costo', models.BooleanField(default=True, help_text='No dejar el precio por debajo de costo×1.1')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_activacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_liquidacion_cerradas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_liquidacion_creadas', to=settings.AUTH_USER_MODEL)),
                ('sucursales', models.ManyToManyField(blank=True, related_name='campanas_liquidacion', to='app.sucursal')),
            ],
            options={
                'verbose_name': 'Campaña de Liquidación',
                'verbose_name_plural': 'Campañas de Liquidación',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AlterField(
            model_name='historialcambioprecio',
            name='tipo_cambio',
            field=models.CharField(choices=[('MANUAL', 'Cambio Manual'), ('RECOMENDACION', 'Por Recomendación'), ('MASIVO', 'Cambio Masivo'), ('SINCRONIZACION', 'Sincronización'), ('APROBACION', 'Por Aprobación'), ('ACTUALIZACION_RECEPCION', 'Actualización por Recepción'), ('ACTUALIZACION_MANUAL', 'Actualización Manual'), ('CAMPANA_LIQUIDACION', 'Campaña de Liquidación'), ('REVERSION_CAMPANA', 'Reversión de Campaña')], default='MANUAL', max_length=50),
        ),
        migrations.AddField(
            model_name='ticket_productos',
            name='promo_campana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lineas_ticket', to='app.campanaliquidacion'),
        ),
        migrations.CreateModel(
            name='CampanaLiquidacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_original', models.IntegerField(default=0, help_text='Precio antes de aplicar (snapshot al ACTIVAR)')),
                ('precio_liquidacion', models.IntegerField(blank=True, help_text='Precio ya con descuento (null en NXM: no cambia precio)', null=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('APLICADO', 'Aplicado'), ('REVERTIDO', 'Revertido'), ('CONFLICTO', 'Conflicto de precio'), ('EXCLUIDO', 'Excluido')], default='PENDIENTE', max_length=12)),
                ('activo', models.BooleanField(default=False, help_text='True mientras la campaña está aplicada sobre este producto')),
                ('fecha_aplicacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_reversion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.campanaliquidacion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_campana_liquidacion', to='app.producto')),
            ],
            options={
                'verbose_name': 'Producto de Campaña de Liquidación',
                'verbose_name_plural': 'Productos de Campañas de Liquidación',
                'indexes': [models.Index(fields=['producto', 'activo'], name='app_campana_product_167f2a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='campanaliquidacionproducto',
            constraint=models.UniqueConstraint(fields=('campana', 'producto'), name='uniq_campana_producto'),
        ),
        migrations.AddConstraint(
            model_name='campanaliquidacionproducto',
            constraint=models.UniqueConstraint(condition=models.Q(('activo', True)), fields=('producto',), name='uniq_producto_en_campana_activa'),
        ),
        migrations.AddIndex(
            model_name='campanaliquidacion',
            index=models.Index(fields=['estado', 'fecha_fin'], name='app_campana_estado_764581_idx'),
        ),
    ]
