# Generated by Django 4.2.2 on 2026-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0188_plan_liquidacion_campanas'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcard',
            name='descripcion',
            field=models.CharField(blank=True, help_text="Descripción / nombre libre (ej. 'Regalo corporativo Empresa X')", max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='giftcard',
            name='motivo',
            field=models.CharField(choices=[('PROMOCION', 'Promoción'), ('COMPENSACION', 'Compensación'), ('REGALO_CORP', 'Regalo corporativo'), ('VENTA', 'Venta'), ('OTRO', 'Otro')], db_index=True, default='OTRO', help_text='Propósito de la gift card (para filtrar y reportar)', max_length=20),
        ),
        migrations.AlterField(
            model_name='movimientogiftcard',
            name='tipo',
            field=models.CharField(choices=[('EMISION', 'Emisión'), ('CARGA', 'Carga / Recarga'), ('CONSUMO', 'Consumo (pago de venta)'), ('ANULACION', 'Anulación'), ('AJUSTE', 'Ajuste manual'), ('REVERSA', 'Reversa (devolución/anulación de venta)'), ('BLOQUEO', 'Bloqueo'), ('DESBLOQUEO', 'Desbloqueo')], max_length=20),
        ),
    ]
