# Generated by Django 4.2.2 on 2026-07-24 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0189_giftcard_descripcion_giftcard_motivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion_empresa',
            name='dte',
            field=models.ForeignKey(blank=True, help_text='Documento tributario emitido al facturar. `numero_factura` guarda solo el número, que se repite entre tipos de DTE y sucursales: esta FK es la que identifica el documento de verdad.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cotizaciones', to='app.dte'),
        ),
        migrations.AddField(
            model_name='dte_productos',
            name='cotizacion_detalle_id',
            field=models.IntegerField(blank=True, db_index=True, help_text='ID del Cotizacion_Empresa_Detalle que originó la línea. Espejo del campo homónimo de Ticket_Productos: permite localizar esta línea cuando se asigna el SKU después de facturar (despacho diferido).', null=True),
        ),
    ]
