# Generated by Django 4.2.2 on 2026-07-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0193_login_movil_pin_correo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientos_producto',
            name='concepto',
            field=models.CharField(choices=[('INGRESO_INICIAL', 'Ingreso Inicial'), ('INGRESO_MANUAL', 'Ingreso Manual'), ('RECEPCION_COMPRA', 'Recepción de Compra'), ('REPOSICION_STOCK', 'Reposición de Stock'), ('DEVOLUCION_CLIENTE', 'Devolución de Cliente'), ('TRASPASO_ENTRADA', 'Traspaso Entrada'), ('REGULARIZACION_TRASPASO', 'Regularización de Traspaso'), ('AJUSTE_POSITIVO', 'Ajuste Positivo'), ('DONACION_RECIBIDA', 'Donación Recibida'), ('VENTA_PUBLICO', 'Venta al Público'), ('VENTA_MAYORISTA', 'Venta Mayorista'), ('TRASPASO_SALIDA', 'Traspaso Salida'), ('AJUSTE_NEGATIVO', 'Ajuste Negativo'), ('PERDIDA_ROBO', 'Pérdida por Robo'), ('PERDIDA_DETERIORO', 'Pérdida por Deterioro'), ('DONACION_ENTREGADA', 'Donación Entregada'), ('DEVOLUCION_PROVEEDOR', 'Devolución a Proveedor'), ('TRASPASO_SUCURSAL', 'Traspaso entre Sucursales'), ('TRASPASO_BODEGA', 'Traspaso a Bodega'), ('TRASPASO_VITRINA', 'Traspaso a Vitrina'), ('CAMBIO_PRODUCTO_SALIDA', 'Cambio de Producto (Salida)'), ('CAMBIO_PRODUCTO_ENTRADA', 'Cambio de Producto (Entrada)'), ('CORRECCION_STOCK', 'Corrección de Stock'), ('ANULACION_REGULARIZACION', 'Anulación de Regularización'), ('ANULACION', 'Anulación de DTE'), ('CANCELACION', 'Cancelación de DTE'), ('REASIGNACION_DESTINO', 'Reasignación de Destino de Traspaso'), ('AJUSTE_INVENTARIO_ENTRADA', 'Ajuste Inventario - Entrada (Sobrante)'), ('AJUSTE_INVENTARIO_SALIDA', 'Ajuste Inventario - Salida (Faltante)'), ('DESPACHO_COTIZACION', 'Despacho de Cotización'), ('RECEPCION_SOBRANTE', 'Recepción de Sobrante (Pendiente Decisión)'), ('SOBRANTE_INGRESO', 'Sobrante Aceptado - Ingreso a Inventario'), ('SOBRANTE_DEVUELTO', 'Sobrante Devuelto a Origen'), ('DEVOLUCION_NC', 'Devolución por Nota de Crédito'), ('DEVOLUCION_NC_POST_RECEPCION', 'Devolución NC tras recepción'), ('DEVOLUCION_NC_PENDIENTE_DESPACHO', 'Devolución NC - Pendiente despacho físico desde destino'), ('SOBRANTE_ABSORBIDO_ORIGEN', 'NC sin devolución - mercadería queda en destino'), ('REPARACION_STOCK_HISTORICO', 'Reparación Stock Histórico (NC sin movimientos)'), ('AJUSTE_INVENTARIO', 'Ajuste de Inventario (legacy)'), ('VENTA_DIRECTA', 'Venta Directa (fallback POS)'), ('ANULACION_TICKET', 'Anulación de Ticket POS'), ('REVERSION_CAMBIO', 'Reversión de Cambio de Producto'), ('DEVOLUCION_NO_APTA', 'Devolución No Apta (sin ingreso a stock)')], default='INGRESO_INICIAL', max_length=50),
        ),
    ]
