# Generated by Django 4.2.2 on 2026-08-05 15:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0201_pedido_ecommerce_facturado_externo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorProductoEquivalencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_externo', models.CharField(help_text='VlrCodigo del CdgItem tal como viene en el XML del proveedor.', max_length=50)),
                ('tipo_codigo', models.CharField(blank=True, help_text='TpoCodigo informado por el proveedor (INT1, EAN, SKU…). Es texto libre no validado por el SII: se guarda solo como referencia, NO forma parte de la clave.', max_length=10)),
                ('descripcion_externa', models.CharField(blank=True, help_text='NmbItem/DscItem con que el proveedor describió el producto la primera vez. Sirve para que un humano audite la equivalencia.', max_length=255)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('veces_usada', models.IntegerField(default=0, help_text='Cuántas veces esta equivalencia resolvió sola una línea. Un contador alto es señal de que la equivalencia es correcta; uno en 0 después de varias facturas, de que sobra.')),
                ('creado_por', models.ForeignKey(blank=True, help_text='Usuario que resolvió la línea a mano.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equivalencias_proveedor_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa_proveedor', models.ForeignKey(help_text='Proveedor (emisor del DTE) dueño de este código.', on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_productos', to='app.empresa')),
                ('producto_talla', models.ForeignKey(help_text='Producto/talla nuestro al que corresponde el código.', on_delete=django.db.models.deletion.CASCADE, related_name='equivalencias_proveedor', to='app.producto_talla')),
            ],
            options={
                'verbose_name': 'Equivalencia de producto del proveedor',
                'verbose_name_plural': 'Equivalencias de productos de proveedores',
                'ordering': ['empresa_proveedor__nombre', 'codigo_externo'],
                'indexes': [models.Index(fields=['codigo_externo'], name='provequiv_codext_idx')],
                'unique_together': {('empresa_proveedor', 'codigo_externo')},
            },
        ),
    ]
