# Generated by Django 4.2.2 on 2026-08-05 21:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0204_pedido_ecommerce_estado_logistica_canal'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampanaCupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('tipo_valor', models.CharField(choices=[('PORCENTAJE', '% sobre el total'), ('MONTO', 'Monto fijo ($)')], default='PORCENTAJE', max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, help_text='5.00 = 5% (PORCENTAJE) o $5.000 (MONTO)', max_digits=7)),
                ('tope_descuento', models.IntegerField(blank=True, help_text='Techo en pesos del descuento (sólo PORCENTAJE). Vacío = sin techo', null=True)),
                ('monto_minimo', models.IntegerField(default=0, help_text='Compra mínima en pesos para poder usar el cupón')),
                ('vigencia_dias', models.IntegerField(default=30, help_text='Días que vive cada cupón desde que se emite')),
                ('fecha_inicio', models.DateField(db_index=True, help_text='Desde cuándo se pueden EMITIR cupones')),
                ('fecha_fin', models.DateField(db_index=True, help_text='Hasta cuándo se pueden emitir (inclusive)')),
                ('activo', models.BooleanField(db_index=True, default=True)),
                ('uno_vivo_por_cliente', models.BooleanField(default=True, help_text='Impide emitir un 2º cupón a un cliente que ya tiene uno sin usar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campanas_cupon_creadas', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='campanas_cupon', to='app.empresa')),
            ],
            options={
                'verbose_name': 'Campaña de Cupones',
                'verbose_name_plural': 'Campañas de Cupones',
                'ordering': ['-fecha_inicio', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='descuento_cupon',
            field=models.IntegerField(blank=True, help_text='Descuento aplicado por cupón nominativo (pesos brutos, IVA incluido)', null=True),
        ),
        migrations.CreateModel(
            name='CuponCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_cliente', models.CharField(db_index=True, max_length=20)),
                ('codigo', models.CharField(db_index=True, help_text='Código de un solo uso que el cliente presenta en caja', max_length=24, unique=True)),
                ('tipo_valor', models.CharField(choices=[('PORCENTAJE', '% sobre el total'), ('MONTO', 'Monto fijo ($)')], max_length=12)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=7)),
                ('tope_descuento', models.IntegerField(blank=True, null=True)),
                ('monto_minimo', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de uso'), ('CANJEADO', 'Canjeado'), ('EXPIRADO', 'Expirado'), ('ANULADO', 'Anulado')], db_index=True, default='PENDIENTE', max_length=12)),
                ('expira_en', models.DateTimeField(db_index=True)),
                ('monto_descuento', models.IntegerField(default=0, help_text='Pesos realmente descontados al canjear')),
                ('canjeado_en', models.DateTimeField(blank=True, null=True)),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cupones', to='app.campanacupon')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupones_descuento', to='app.cliente')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_emitidos', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(help_text='Copia de campana.empresa: permite validar en caja sin join', on_delete=django.db.models.deletion.PROTECT, related_name='cupones_cliente', to='app.empresa')),
                ('sucursal_canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_canjeados', to='app.sucursal')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_descuento', to='app.ticket')),
                ('usuario_canje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupones_canjeados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cupón de Cliente',
                'verbose_name_plural': 'Cupones de Clientes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['estado', 'expira_en'], name='app_cuponcl_estado_c71e8b_idx'), models.Index(fields=['cliente', 'estado'], name='app_cuponcl_cliente_8c6606_idx'), models.Index(fields=['rut_cliente', 'estado'], name='app_cuponcl_rut_cli_dfb61b_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='cuponcliente',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'PENDIENTE')), fields=('campana', 'cliente'), name='uniq_cupon_vivo_por_cliente'),
        ),
        migrations.AddConstraint(
            model_name='cuponcliente',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'CANJEADO')), fields=('ticket',), name='uniq_cupon_canjeado_por_ticket'),
        ),
        migrations.AddIndex(
            model_name='campanacupon',
            index=models.Index(fields=['activo', 'fecha_inicio', 'fecha_fin'], name='app_campana_activo_eff0e4_idx'),
        ),
        migrations.AddIndex(
            model_name='campanacupon',
            index=models.Index(fields=['empresa', 'activo'], name='app_campana_empresa_da84f9_idx'),
        ),
    ]
