# Generated by Django 4.2.2 on 2026-08-17 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0212_requerimiento_decision_interna'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCompraLegacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(help_text='SKU denormalizado: el buscador entra por acá', max_length=100)),
                ('numero_documento', models.CharField(help_text='N° tal como lo escribió el sistema anterior', max_length=50)),
                ('fecha_movimiento', models.DateField(blank=True, help_text='Fecha del ingreso en el kardex legacy', null=True)),
                ('cantidad', models.IntegerField(default=0)),
                ('costo', models.IntegerField(default=0)),
                ('concepto', models.CharField(blank=True, max_length=50, null=True)),
                ('marca_legacy', models.CharField(blank=True, help_text='Marca que traía el movimiento: pista del proveedor', max_length=100, null=True)),
                ('movimiento_origen_id', models.BigIntegerField(help_text='Movimiento del que se recuperó el dato (evita duplicar)', unique=True)),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
                ('dte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_compra_legacy', to='app.dte')),
                ('producto_talla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documentos_compra_legacy', to='app.producto_talla')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_compra_legacy', to='app.empresa')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_compra_legacy', to='app.sucursal')),
            ],
            options={
                'verbose_name': 'Documento de compra legacy',
                'verbose_name_plural': 'Documentos de compra legacy',
                'indexes': [models.Index(fields=['sku'], name='app_documen_sku_318e89_idx'), models.Index(fields=['producto_talla', '-fecha_movimiento'], name='app_documen_product_de068a_idx'), models.Index(fields=['numero_documento'], name='app_documen_numero__dcb125_idx')],
            },
        ),
    ]
