# Generated by Django 4.2.2 on 2026-08-25 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0216_giftcard_estado_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoecommerce',
            name='es_retiro_local',
            field=models.BooleanField(db_index=True, default=False, help_text='El cliente retira en la sucursal (no se despacha). Flag informado por AllConnected en la ingesta.', verbose_name='Retiro en tienda'),
        ),
    ]
