# Generated by Django 4.2.2 on 2026-08-27 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0219_bitacora_correo'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='enviocorreo',
            new_name='app_envio_c_modulo_822c48_idx',
            old_name='app_envio_c_modulo_9c1f3d_idx',
        ),
        migrations.RenameIndex(
            model_name='enviocorreo',
            new_name='app_envio_c_estado_f5b771_idx',
            old_name='app_envio_c_estado_4b7a21_idx',
        ),
    ]
