"""
Django settings for retailmind project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Cargar variables de entorno desde archivo .env (ruta por defecto)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Cargar .env desde el directorio del proyecto (funciona aunque se ejecute desde otra ruta)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-u6k00%6(jlc5r(j2l34j7d=1mn8&_xaam4^t_*c3=oa7%_e-_7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# DigitalOcean
ALLOWED_HOSTS.append('retail-ap-mh3y2.ondigitalocean.app')
ALLOWED_HOSTS.append('*.ondigitalocean.app')

# Railway specific
if 'RAILWAY_ENVIRONMENT' in os.environ:
    ALLOWED_HOSTS.append(os.environ.get('RAILWAY_PUBLIC_DOMAIN', ''))
    ALLOWED_HOSTS.append('*.railway.app')
    ALLOWED_HOSTS.append('*.up.railway.app')
    ALLOWED_HOSTS.append('retail.webappsolutions.cl')

# Para desarrollo/testing - permite todos los hosts
if ALLOWED_HOSTS == ['*']:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',  # CORS para App Desktop Tauri
    'rest_framework',  # Django REST Framework
    'rest_framework_simplejwt',  # JWT para API Desktop
    'rest_framework_simplejwt.token_blacklist',  # Blacklist de tokens
    'users',  # Nueva aplicación de usuarios
    'app',
    'empresa_management',
    'assistant',  # Asistente Conversacional con Claude
]

# django-silk: profiler de queries/tiempo SOLO en DEBUG, opt-in via env
ENABLE_SILK = DEBUG and os.environ.get('ENABLE_SILK', 'False').lower() == 'true'
if ENABLE_SILK:
    INSTALLED_APPS.append('silk')

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS - DEBE IR PRIMERO
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'app.middleware_session_timeout.SessionTimeoutMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware_permisos.PermisosMenuMiddleware',  # Verificación de permisos de menú
]

if ENABLE_SILK:
    # silk debe ir lo antes posible (después de Session) para medir todo
    MIDDLEWARE.insert(
        MIDDLEWARE.index('django.contrib.sessions.middleware.SessionMiddleware') + 1,
        'silk.middleware.SilkyMiddleware',
    )
    SILKY_PYTHON_PROFILER = False
    SILKY_META = True

ROOT_URLCONF = 'retailmind.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [BASE_DIR / 'templates'],
        # En producción usamos cached.Loader (ver OPTIONS.loaders) → APP_DIRS
        # no puede coexistir con loaders custom, lo forzamos a False ahí.
        'APP_DIRS': DEBUG,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.ecommerce_context',
                'app.context_processors.pos_kiosk_context',
            ],
            # En producción: cachear plantillas parseadas (evita reparsear
            # ticket_venta.html de 165KB y generacionVentas.html de 545KB en cada
            # request). En DEBUG usamos APP_DIRS=True arriba y sin loaders.
            **(
                {}
                if DEBUG
                else {
                    'loaders': [
                        (
                            'django.template.loaders.cached.Loader',
                            [
                                'django.template.loaders.filesystem.Loader',
                                'django.template.loaders.app_directories.Loader',
                            ],
                        ),
                    ],
                }
            ),
        },
    },
]

WSGI_APPLICATION = 'retailmind.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Configuración del modelo de usuario personalizado
AUTH_USER_MODEL = 'users.Usuario'

# Database configuration
if os.environ.get('DATABASE_URL'):
    # Production (Railway / DigitalOcean)
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local development - PostgreSQL local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('PG_DATABASE', 'retailmind'),
            'USER': os.environ.get('PG_USER', 'postgres'),
            'PASSWORD': os.environ.get('PG_PASSWORD', 'admin'),
            'HOST': os.environ.get('PG_HOST', 'localhost'),
            'PORT': os.environ.get('PG_PORT', '5432'),
        }
    }

# Nota: Las variables MYSQL_* se usan en migrate_from_laravel.py para conectar
# al servidor MySQL remoto (holdingtebes.cl) desde donde se migran los datos

 

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'



USE_I18N = True

USE_TZ = True  # (esto usualmente ya está activado)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_NAME = 'retailmind'

# ========== POS KIOSK MODE ==========
# True  → TODO el sistema arranca en modo POS táctil (viewport 1920,
#         pos-kiosk.css, sidebar oculto, hovers reemplazados por :active).
#         Se puede desactivar puntualmente con `?kiosk=0` en la URL
#         (útil para tareas de backoffice en la misma instalación).
# False → Modo admin tradicional; el POS se activa sólo con `?kiosk=1`.
POS_KIOSK_DEFAULT = os.environ.get('POS_KIOSK_DEFAULT', 'True').lower() == 'true'



STATICFILES_DIRS = [
    BASE_DIR / 'app' / 'static',  # Archivos estáticos de la app
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# ========== EMAIL configurado más abajo ==========

# Whitenoise configuration for static files
# En DEBUG usamos el storage default (runserver sirve desde STATICFILES_DIRS
# con finders). En producción usamos CompressedManifestStaticFilesStorage
# que añade fingerprint a los nombres para Cache-Control: immutable.
# WHITENOISE_MANIFEST_STRICT=False tolera referencias a .map faltantes.
# Importante: requiere `collectstatic` antes del primer deploy para generar
# staticfiles.json; si se cambia a Manifest sin collectstatic, TODOS los
# {% static %} fallan (jquery, select2, etc.) y la app se rompe.
if DEBUG:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'
else:
    STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
    WHITENOISE_MANIFEST_STRICT = False
    WHITENOISE_MAX_AGE = 60 * 60 * 24 * 365   # 1 año para assets hasheados
    WHITENOISE_USE_FINDERS = False
WHITENOISE_AUTOREFRESH = DEBUG

# CSRF Failure View - redirige al login con mensaje en lugar de mostrar 403
CSRF_FAILURE_VIEW = 'retailmind.views.csrf_failure'

# CSRF Trusted Origins - SIEMPRE configurar en producción
CSRF_TRUSTED_ORIGINS = [
    "https://retail-ap-mh3y2.ondigitalocean.app",
    "https://*.ondigitalocean.app",
    "https://retail.webappsolutions.cl",
]

if 'RAILWAY_ENVIRONMENT' in os.environ:
    CSRF_TRUSTED_ORIGINS += [
        f"https://{os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')}",
        "https://*.railway.app",
        "https://*.up.railway.app",
    ]

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # HSTS a 1 año (requisito para el preload list). 86400 (1 día) era demasiado
    # corto para que un MITM no pudiera degradar a HTTP entre visitas.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Detrás del balanceador de Digital Ocean (y Railway) el TLS termina en el LB
    # y al backend le llega HTTP con la cabecera X-Forwarded-Proto. Sin esto,
    # request.is_secure() sería False y las cookies "secure"/los redirects de
    # seguridad no funcionarían correctamente.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # Redirige HTTP→HTTPS. Default OFF: con el health check de App Platform por
    # HTTP interno, forzarlo puede romper el chequeo. Actívalo (env var) solo si
    # confirmaste que el health check usa HTTPS o una ruta exenta.
    SECURE_SSL_REDIRECT = os.environ.get('SECURE_SSL_REDIRECT', 'False').lower() == 'true'

    # CSRF settings
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    # Endurecimiento de cookies: no accesibles por JS y enviadas solo en
    # navegación same-site (mitiga XSS-robo-de-sesión y CSRF cross-site).
    SESSION_COOKIE_HTTPONLY = True
    CSRF_COOKIE_HTTPONLY = False  # el front lee el token CSRF por JS (AJAX del POS)
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

# Configuración de autenticación
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'verHome'
LOGOUT_REDIRECT_URL = 'login'

# ========== CONFIGURACIÓN 2FA / PIN ==========
# True  → todos los usuarios deben ingresar un PIN al hacer login
# False → solo los usuarios con requiere_2fa=True en su perfil
REQUIRE_2FA_FOR_ALL = False
# 'session' → el PIN expira a los 10 minutos
# 'daily'   → el mismo PIN sirve durante todo el día
PIN_2FA_MODE = 'session'

# ========== CONFIGURACIÓN DE EMAIL ==========
# Ahora usa variables de entorno para mayor seguridad
#
# El backend por defecto es el SMTP normal de Django MÁS la captura del
# identificador que devuelve el relay en su respuesta final ("Message queued
# as ..."). Es un reemplazo directo: no cambia cómo se envía, solo permite
# correlacionar después los webhooks de entrega con el correo que los originó.
# Se puede volver al backend estándar con la env var EMAIL_BACKEND.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'app.mail_backends.TrazableEmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ===== INSTRUCCIONES =====
# Configura estas variables de entorno en tu servidor de producción:
#
# OPCIÓN 1 - MailerSend:
#   EMAIL_HOST=smtp.mailersend.net
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=True
#   EMAIL_HOST_USER=MS_xxx@trial-xxx.mlsender.net
#   EMAIL_HOST_PASSWORD=tu_token_mailersend
#   DEFAULT_FROM_EMAIL=MS_xxx@trial-xxx.mlsender.net
#
# OPCIÓN 2 - Gmail (Recomendado):
#   EMAIL_HOST=smtp.gmail.com
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=True
#   EMAIL_HOST_USER=tu-email@gmail.com
#   EMAIL_HOST_PASSWORD=xxxx-xxxx-xxxx-xxxx  # App Password de Gmail
#   DEFAULT_FROM_EMAIL=tu-email@gmail.com

# ========== SEGUIMIENTO DE CORREO ==========
# URL pública del sistema. La necesitan el píxel de apertura y los enlaces que
# van dentro de los correos: sin ella el correo sale igual, pero sin rastreo.
CORREO_BASE_URL = os.environ.get('CORREO_BASE_URL', '')

# Buzón genérico que recibe las respuestas de los proveedores. Cuando está
# definido, el Reply-To de los correos pasa a ser `buzon+<token>@dominio`
# (plus-addressing: Google Workspace lo entrega al buzón base sin configurar
# alias) y eso permite pegar cada respuesta en la ficha que la originó.
# Mientras esté vacío, el Reply-To sigue siendo el del usuario que envía.
CORREO_BUZON_RESPUESTAS = os.environ.get('CORREO_BUZON_RESPUESTAS', '')

# Remitente del módulo de requerimientos. Conviene que sea un buzón que exista
# de verdad: con `noreply@`, el proveedor que responde al remitente en vez de
# usar "Responder" escribe a un buzón que nadie lee.
REQUERIMIENTOS_FROM_EMAIL = os.environ.get(
    'REQUERIMIENTOS_FROM_EMAIL', DEFAULT_FROM_EMAIL or ''
)

# ========== LOGGING ==========
# En producción subimos los loggers internos a WARNING para dejar de escribir
# a disco en cada AJAX del POS (los INFO se iban acumulando en app.log).
_APP_LOG_LEVEL = 'DEBUG' if DEBUG else 'WARNING'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_app': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'app.log',
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_errors': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'app': {
            'handlers': ['console', 'file_app', 'file_errors'],
            'level': _APP_LOG_LEVEL,
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file_app', 'file_errors'],
            'level': _APP_LOG_LEVEL,
            'propagate': False,
        },
        'empresa_management': {
            'handlers': ['console', 'file_app', 'file_errors'],
            'level': _APP_LOG_LEVEL,
            'propagate': False,
        },
        'assistant': {
            'handlers': ['console', 'file_app', 'file_errors'],
            'level': _APP_LOG_LEVEL,
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file_errors'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file_errors'],
        'level': 'WARNING',
    },
}

# Crear directorio de logs si no existe
import os as _os
_logs_dir = BASE_DIR / 'logs'
if not _logs_dir.exists():
    _os.makedirs(_logs_dir, exist_ok=True)

# Configuración de seguridad / sesiones
PASSWORD_RESET_TIMEOUT = 86400  # 24 horas
SESSION_COOKIE_AGE = int(os.environ.get('SESSION_COOKIE_AGE', 28800))  # 8 h (un turno)
SESSION_EXPIRE_AT_BROWSER_CLOSE = os.environ.get(
    'SESSION_EXPIRE_AT_BROWSER_CLOSE', 'True'
).lower() == 'true'
# Inactividad máxima (segundos). El middleware SessionTimeoutMiddleware
# cierra la sesión si el usuario no interactúa en este periodo.
SESSION_INACTIVITY_TIMEOUT = int(os.environ.get('SESSION_INACTIVITY_TIMEOUT', 3600))
# Throttle de escritura del timestamp de actividad (evita UPDATE en cada AJAX del POS).
SESSION_ACTIVITY_THROTTLE = int(os.environ.get('SESSION_ACTIVITY_THROTTLE', 300))
SESSION_SAVE_EVERY_REQUEST = False

# ========== CACHES ==========
# LocMemCache por proceso: sirve para @cache_page en endpoints de catálogo
# (productos, vendedores, sucursales) y para @vary_on_cookie. NO usar para
# datos compartidos entre workers (para eso habría que migrar a Redis).
#
# El cache `ventas` usa Redis si está disponible (REDIS_URL env var),
# permitiendo compartir caché entre workers y hacer invalidación atómica
# por sucursal desde signals. Si no hay Redis, cae a LocMemCache.
REDIS_URL = os.environ.get('REDIS_URL', '').strip()

CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'retailmind-default',
        'TIMEOUT': 300,   # 5 minutos por defecto
        'OPTIONS': {
            'MAX_ENTRIES': 2000,
            'CULL_FREQUENCY': 4,
        },
    },
    # Cache dedicado para catálogo de productos (TTL largo, invalidación manual)
    'catalogo': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'retailmind-catalogo',
        'TIMEOUT': 900,   # 15 minutos
        'OPTIONS': {
            'MAX_ENTRIES': 5000,
            'CULL_FREQUENCY': 4,
        },
    },
    # Cache para el rate-limiting de la API de cliente (S2). LocMem por defecto;
    # se sube a Redis si hay REDIS_URL (abajo) para un tope EXACTO entre workers.
    'throttle': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'retailmind-throttle',
        'TIMEOUT': None,
        'OPTIONS': {
            'MAX_ENTRIES': 5000,
            'CULL_FREQUENCY': 4,
        },
    },
}

# Cache `ventas`: dashboards/indicadores globales del módulo ventas.
# TTL corto (30-120 s); la invalidación granular se maneja via signals.
if REDIS_URL:
    CACHES['ventas'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'TIMEOUT': 60,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'rm:ventas',
    }
else:
    CACHES['ventas'] = {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'retailmind-ventas',
        'TIMEOUT': 60,
        'OPTIONS': {
            'MAX_ENTRIES': 3000,
            'CULL_FREQUENCY': 4,
        },
    }

# R3/S2: con Redis, el catálogo (proxy) y el throttle de la API de cliente se
# comparten entre workers → un solo fetch al ecommerce sirve a todos, y el tope
# de rate-limit es EXACTO (no se multiplica por nº de workers). Sin Redis, ambos
# quedan en LocMem (definidos arriba) como degradación.
if REDIS_URL:
    CACHES['catalogo'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'TIMEOUT': 900,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'rm:catalogo',
    }
    CACHES['throttle'] = {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'TIMEOUT': None,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            'IGNORE_EXCEPTIONS': True,
        },
        'KEY_PREFIX': 'rm:throttle',
    }

# django-redis: cuando se producen excepciones de red, devolver None en vez de crashear
DJANGO_REDIS_IGNORE_EXCEPTIONS = True

# Configuración de archivos de medios
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ========== EVIDENCIA EN DIGITALOCEAN SPACES (opcional) ==========
# MEDIA_ROOT vive en el disco del contenedor, que es efímero: cada deploy se
# lleva las fotos. Para la evidencia de requerimientos —que es la prueba del
# reclamo al proveedor— eso no sirve, así que puede apuntarse a un Space.
#
# Se activa SOLO si están definidas SPACES_ACCESS_KEY y SPACES_SECRET_KEY; si
# no, todo sigue guardándose en MEDIA_ROOT (local y tests no cambian).
# Alcance actual: únicamente FotoRequerimiento.imagen (ver app/storage_backends.py).
SPACES_ACCESS_KEY = os.environ.get('SPACES_ACCESS_KEY', '').strip()
SPACES_SECRET_KEY = os.environ.get('SPACES_SECRET_KEY', '').strip()
SPACES_BUCKET = os.environ.get('SPACES_BUCKET', 'media-ecommerce').strip()
SPACES_REGION = os.environ.get('SPACES_REGION', 'sfo3').strip()
SPACES_ENDPOINT = os.environ.get(
    'SPACES_ENDPOINT', f'https://{SPACES_REGION}.digitaloceanspaces.com').strip()
# Carpeta propia dentro del bucket, para no mezclarse con lo del ecommerce.
SPACES_PREFIJO = os.environ.get('SPACES_PREFIJO', 'retailmind').strip('/ ')
# 'private' entrega URLs firmadas con vencimiento (la evidencia puede traer
# datos del cliente). Cambiar a 'public-read' solo si se necesita URL fija.
SPACES_ACL = os.environ.get('SPACES_ACL', 'private').strip()
SPACES_URL_EXPIRA_SEGUNDOS = int(os.environ.get('SPACES_URL_EXPIRA_SEGUNDOS', '3600'))
SPACES_HABILITADO = bool(SPACES_ACCESS_KEY and SPACES_SECRET_KEY)

# ========== QZ TRAY — IMPRESIÓN TÉRMICA SILENCIOSA ==========
# Generar con: openssl req -newkey rsa:2048 -nodes -keyout private-key.pem
#              -x509 -days 3650 -out digital-certificate.txt
QZ_PRIVATE_KEY_PATH = BASE_DIR / 'retailmind' / 'certs' / 'private-key.pem'
QZ_CERTIFICATE_PATH = BASE_DIR / 'retailmind' / 'certs' / 'digital-certificate.txt'

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    # Rates para los scopes de la API de clientes finales (app fidelización).
    # Solo aplican donde la vista declara ScopedRateThrottle + throttle_scope;
    # no afectan a los endpoints de staff/desktop.
    'DEFAULT_THROTTLE_RATES': {
        'otp_solicitar': '5/hour',
        'otp_verificar': '10/hour',
        'vincular_cliente': '5/hour',
        # Protección de carga de la app móvil (por cliente autenticado). Topan el
        # ritmo de requests para que un pico (o un cliente abusivo) no tumbe a
        # RetailMind ni, vía el proxy de catálogo, a los ecommerce.
        # NOTA: el cache de throttle es LocMem (por worker); para un tope GLOBAL
        # exacto se requiere un cache compartido (Redis). Aun así, capa por worker.
        'app_catalogo': '120/min',   # navegación de catálogo/categorías (proxy al ecommerce)
        'app_consulta': '90/min',    # saldo/movimientos/cotizar/estado (lecturas)
        'app_checkout': '20/min',    # reservar/iniciar (escrituras, tocan el ecommerce)
    },
}

# ========== APP DE CLIENTES FINALES (fidelización móvil) ==========
# OTP de login del cliente (ver app/models/cliente_app.py y cliente_app_service.py).
OTP_EXPIRACION_MINUTOS = 10   # vigencia de un código OTP
MAX_INTENTOS_OTP = 5          # intentos por código antes de invalidarlo
MAX_LOGIN_FALLIDOS = 5        # fallos antes de bloquear la cuenta
BLOQUEO_LOGIN_MINUTOS = 15    # duración del bloqueo por fuerza bruta

# ========== CONFIGURACIÓN JWT PARA APP DESKTOP ==========
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),  # 12 horas - el refresh token renueva
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # 7 días con rotación automática
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'retailmind',
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

# ========== CONFIGURACIÓN API DESKTOP ==========
DESKTOP_API_CONFIG = {
    'VERSION_MINIMA_APP': '1.0.0',
    'MAX_TICKETS_OFFLINE': 1000,
    'HORAS_EXPIRACION_TOKEN': 12,
    'DIAS_EXPIRACION_REFRESH': 7,
    'TIMESTAMP_TOLERANCE_MINUTES': 5,
}

# ========== CONFIGURACIÓN DEL ASISTENTE CONVERSACIONAL ==========
# API Key de Anthropic (Claude)
# Obtener en: https://console.anthropic.com/
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

# Configuración de Langfuse para tracing y observabilidad
# Obtener en: https://langfuse.com/
LANGFUSE_SECRET_KEY = os.environ.get('LANGFUSE_SECRET_KEY', '')
LANGFUSE_PUBLIC_KEY = os.environ.get('LANGFUSE_PUBLIC_KEY', '')
LANGFUSE_HOST = os.environ.get('LANGFUSE_HOST', 'https://cloud.langfuse.com')

# ========== API EXTERNA (VicentAllEcommercesConected) ==========
RETAILMIND_API_KEY = os.environ.get('RETAILMIND_API_KEY', '')

# Configuración del Asistente
ASSISTANT_MAX_MESSAGES_PER_SESSION = 50  # Máximo de mensajes por sesión
ASSISTANT_SESSION_TIMEOUT_HOURS = 24  # Tiempo de vida de una sesión

# ========== CONFIGURACIÓN CORS PARA APP DESKTOP (NEXO POS) ==========
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:1420",      # Tauri dev server
        "tauri://localhost",          # Tauri production
        "https://tauri.localhost",    # Tauri https
        "https://retail.webappsolutions.cl",
    ]
    if 'RAILWAY_PUBLIC_DOMAIN' in os.environ:
        CORS_ALLOWED_ORIGINS.append(f"https://{os.environ['RAILWAY_PUBLIC_DOMAIN']}")

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-device-id",
    "x-app-version",
    "x-sucursal-id",
    "x-request-timestamp",
    "x-api-key",
]


# ─────────────────────────────────────────────────────────────────────────────
# AllConnected — notificación de cambios de stock
# ─────────────────────────────────────────────────────────────────────────────
# URL del webhook de AllConnected que recibe actualizaciones de stock.
# Vacío = deshabilitado (no se notifica).
ALLCONNECTED_WEBHOOK_URL = os.environ.get('ALLCONNECTED_WEBHOOK_URL', '')
# ID del canal origen en AllConnected que representa a RetailMind.
# Cada empresa puede tener un canal distinto; se configura por empresa en la
# tabla Canal de AllConnected. Este es el ID por defecto.
ALLCONNECTED_CANAL_ORIGEN_ID = int(os.environ.get('ALLCONNECTED_CANAL_ORIGEN_ID', '0') or '0')

# ─────────────────────────────────────────────────────────────────────────────
# AllConnected — pull de pedidos (botón "Traer pedidos")
# ─────────────────────────────────────────────────────────────────────────────
# Permite que RetailMind salga a CONSULTAR pedidos pendientes a AllConnected
# (en vez de solo recibirlos por push). Vacío = pull deshabilitado: el botón
# solo refresca la tabla con los pedidos ya recibidos.
# Lo consume app/services/allconnected_pedidos_service.py
ALLCONNECTED_API_BASE_URL = os.environ.get('ALLCONNECTED_API_BASE_URL', '')        # ej: https://allconnected.host
ALLCONNECTED_API_KEY = os.environ.get('ALLCONNECTED_API_KEY', '')                  # key de auth saliente
ALLCONNECTED_API_HEADER_NAME = os.environ.get('ALLCONNECTED_API_HEADER_NAME', 'X-AllConnected-Key')
ALLCONNECTED_PEDIDOS_PATH = os.environ.get('ALLCONNECTED_PEDIDOS_PATH', '/app/pedidos/pendientes/')