"""
Django settings for retailmind project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv

# Cargar variables de entorno desde archivo .env (ruta por defecto)
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# Cargar .env desde el directorio del proyecto (funciona aunque se ejecute desde otra ruta)
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-u6k00%6(jlc5r(j2l34j7d=1mn8&_xaam4^t_*c3=oa7%_e-_7')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

# ALLOWED_HOSTS configuration
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# DigitalOcean
ALLOWED_HOSTS.append('retail-ap-mh3y2.ondigitalocean.app')
ALLOWED_HOSTS.append('*.ondigitalocean.app')

# Railway specific
if 'RAILWAY_ENVIRONMENT' in os.environ:
    ALLOWED_HOSTS.append(os.environ.get('RAILWAY_PUBLIC_DOMAIN', ''))
    ALLOWED_HOSTS.append('*.railway.app')
    ALLOWED_HOSTS.append('*.up.railway.app')
    ALLOWED_HOSTS.append('retail.webappsolutions.cl')

# Para desarrollo/testing - permite todos los hosts
if ALLOWED_HOSTS == ['*']:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    'corsheaders',  # CORS para App Desktop Tauri
    'rest_framework',  # Django REST Framework
    'rest_framework_simplejwt',  # JWT para API Desktop
    'rest_framework_simplejwt.token_blacklist',  # Blacklist de tokens
    'users',  # Nueva aplicación de usuarios
    'app',
    'empresa_management',
    'assistant',  # Asistente Conversacional con Claude
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # CORS - DEBE IR PRIMERO
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'app.middleware_permisos.PermisosMenuMiddleware',  # Verificación de permisos de menú
]

ROOT_URLCONF = 'retailmind.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS':  [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'app.context_processors.ecommerce_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'retailmind.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
# Configuración del modelo de usuario personalizado
AUTH_USER_MODEL = 'users.Usuario'

# Database configuration
if 'DATABASE_URL' in os.environ:
    # Railway PostgreSQL
    DATABASES = {
        'default': dj_database_url.config(
            default=os.environ.get('DATABASE_URL'),
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    # Local development - PostgreSQL local
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ.get('PG_DATABASE', 'retailmind'),
            'USER': os.environ.get('PG_USER', 'postgres'),
            'PASSWORD': os.environ.get('PG_PASSWORD', 'admin'),
            'HOST': os.environ.get('PG_HOST', 'localhost'),
            'PORT': os.environ.get('PG_PORT', '5432'),
        }
    }

# Nota: Las variables MYSQL_* se usan en migrate_from_laravel.py para conectar
# al servidor MySQL remoto (holdingtebes.cl) desde donde se migran los datos

 

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-cl'

TIME_ZONE = 'America/Santiago'



USE_I18N = True

USE_TZ = True  # (esto usualmente ya está activado)


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_NAME = 'retailmind'



STATICFILES_DIRS = [
    BASE_DIR / 'app' / 'static',  # Archivos estáticos de la app
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# ========== EMAIL configurado más abajo ==========

# Whitenoise configuration for static files
# CompressedStaticFilesStorage no valida referencias a .map faltantes
STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

# CSRF Failure View - redirige al login con mensaje en lugar de mostrar 403
CSRF_FAILURE_VIEW = 'retailmind.views.csrf_failure'

# CSRF Trusted Origins - SIEMPRE configurar en producción
CSRF_TRUSTED_ORIGINS = [
    "https://retail-ap-mh3y2.ondigitalocean.app",
    "https://*.ondigitalocean.app",
    "https://retail.webappsolutions.cl",
]

if 'RAILWAY_ENVIRONMENT' in os.environ:
    CSRF_TRUSTED_ORIGINS += [
        f"https://{os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')}",
        "https://*.railway.app",
        "https://*.up.railway.app",
    ]

# Security settings for production
if not DEBUG:
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 86400
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    
    # CSRF settings
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

# Configuración de autenticación
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'verHome'
LOGOUT_REDIRECT_URL = 'login'

# ========== CONFIGURACIÓN 2FA / PIN ==========
# True  → todos los usuarios deben ingresar un PIN al hacer login (recomendado)
# False → solo los usuarios con requiere_2fa=True en su perfil
REQUIRE_2FA_FOR_ALL = True
# 'session' → el PIN expira a los 10 minutos
# 'daily'   → el mismo PIN sirve durante todo el día
PIN_2FA_MODE = 'session'

# ========== CONFIGURACIÓN DE EMAIL ==========
# Ahora usa variables de entorno para mayor seguridad
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', EMAIL_HOST_USER)

# ===== INSTRUCCIONES =====
# Configura estas variables de entorno en tu servidor de producción:
#
# OPCIÓN 1 - MailerSend:
#   EMAIL_HOST=smtp.mailersend.net
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=True
#   EMAIL_HOST_USER=MS_xxx@trial-xxx.mlsender.net
#   EMAIL_HOST_PASSWORD=tu_token_mailersend
#   DEFAULT_FROM_EMAIL=MS_xxx@trial-xxx.mlsender.net
#
# OPCIÓN 2 - Gmail (Recomendado):
#   EMAIL_HOST=smtp.gmail.com
#   EMAIL_PORT=587
#   EMAIL_USE_TLS=True
#   EMAIL_HOST_USER=tu-email@gmail.com
#   EMAIL_HOST_PASSWORD=xxxx-xxxx-xxxx-xxxx  # App Password de Gmail
#   DEFAULT_FROM_EMAIL=tu-email@gmail.com

# ========== LOGGING ==========
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '[{asctime}] {levelname} {name} {module}.{funcName}:{lineno} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '[{levelname}] {name}: {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file_app': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'app.log',
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
        'file_errors': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'errors.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 10,
            'formatter': 'verbose',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'app': {
            'handlers': ['console', 'file_app', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'users': {
            'handlers': ['console', 'file_app', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'empresa_management': {
            'handlers': ['console', 'file_app', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'assistant': {
            'handlers': ['console', 'file_app', 'file_errors'],
            'level': 'INFO',
            'propagate': False,
        },
        'django': {
            'handlers': ['console', 'file_errors'],
            'level': 'WARNING',
            'propagate': False,
        },
        'django.request': {
            'handlers': ['console', 'file_errors'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console', 'file_errors'],
        'level': 'WARNING',
    },
}

# Crear directorio de logs si no existe
import os as _os
_logs_dir = BASE_DIR / 'logs'
if not _logs_dir.exists():
    _os.makedirs(_logs_dir, exist_ok=True)

# Configuración de seguridad
PASSWORD_RESET_TIMEOUT = 86400  # 24 horas
SESSION_COOKIE_AGE = 604800     # 7 días (dev-friendly; ajustar en producción)
SESSION_EXPIRE_AT_BROWSER_CLOSE = False
SESSION_SAVE_EVERY_REQUEST = True

# Configuración de archivos de medios
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# ========== QZ TRAY — IMPRESIÓN TÉRMICA SILENCIOSA ==========
# Generar con: openssl req -newkey rsa:2048 -nodes -keyout private-key.pem
#              -x509 -days 3650 -out digital-certificate.txt
QZ_PRIVATE_KEY_PATH = BASE_DIR / 'retailmind' / 'certs' / 'private-key.pem'
QZ_CERTIFICATE_PATH = BASE_DIR / 'retailmind' / 'certs' / 'digital-certificate.txt'

# Configuración de Django REST Framework
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# ========== CONFIGURACIÓN JWT PARA APP DESKTOP ==========
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=12),  # 12 horas - el refresh token renueva
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),  # 7 días con rotación automática
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'VERIFYING_KEY': None,
    'AUDIENCE': None,
    'ISSUER': 'retailmind',
    'JWK_URL': None,
    'LEEWAY': 0,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'USER_AUTHENTICATION_RULE': 'rest_framework_simplejwt.authentication.default_user_authentication_rule',

    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
    'TOKEN_USER_CLASS': 'rest_framework_simplejwt.models.TokenUser',

    'JTI_CLAIM': 'jti',
}

# ========== CONFIGURACIÓN API DESKTOP ==========
DESKTOP_API_CONFIG = {
    'VERSION_MINIMA_APP': '1.0.0',
    'MAX_TICKETS_OFFLINE': 1000,
    'HORAS_EXPIRACION_TOKEN': 12,
    'DIAS_EXPIRACION_REFRESH': 7,
    'TIMESTAMP_TOLERANCE_MINUTES': 5,
}

# ========== CONFIGURACIÓN DEL ASISTENTE CONVERSACIONAL ==========
# API Key de Anthropic (Claude)
# Obtener en: https://console.anthropic.com/
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')

# Configuración de Langfuse para tracing y observabilidad
# Obtener en: https://langfuse.com/
LANGFUSE_SECRET_KEY = os.environ.get('LANGFUSE_SECRET_KEY', '')
LANGFUSE_PUBLIC_KEY = os.environ.get('LANGFUSE_PUBLIC_KEY', '')
LANGFUSE_HOST = os.environ.get('LANGFUSE_HOST', 'https://cloud.langfuse.com')

# ========== API EXTERNA (VicentAllEcommercesConected) ==========
RETAILMIND_API_KEY = os.environ.get('RETAILMIND_API_KEY', '')

# Configuración del Asistente
ASSISTANT_MAX_MESSAGES_PER_SESSION = 50  # Máximo de mensajes por sesión
ASSISTANT_SESSION_TIMEOUT_HOURS = 24  # Tiempo de vida de una sesión

# ========== CONFIGURACIÓN CORS PARA APP DESKTOP (NEXO POS) ==========
if DEBUG:
    CORS_ALLOW_ALL_ORIGINS = True
else:
    CORS_ALLOW_ALL_ORIGINS = False
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:1420",      # Tauri dev server
        "tauri://localhost",          # Tauri production
        "https://tauri.localhost",    # Tauri https
        "https://retail.webappsolutions.cl",
    ]
    if 'RAILWAY_PUBLIC_DOMAIN' in os.environ:
        CORS_ALLOWED_ORIGINS.append(f"https://{os.environ['RAILWAY_PUBLIC_DOMAIN']}")

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "DELETE",
    "GET",
    "OPTIONS",
    "PATCH",
    "POST",
    "PUT",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
    "x-device-id",
    "x-app-version",
    "x-sucursal-id",
    "x-request-timestamp",
    "x-api-key",
]